package com.johnny.hotel.financeexpense;import org.apache.ibatis.annotations.*;import java.time.*;import java.util.*;import com.johnny.hotel.finance.FinanceOperationsModels.CategoryExpense;
@Mapper public interface HotelExpenseMapper{
 @Insert("INSERT INTO hotel_expense(amount,currency,category,description,reference_no,expense_date,service_date,status,created_by,related_type,related_id,employee_user_id,request_key) VALUES(#{amount},#{currency},#{category},#{description},#{referenceNo},#{expenseDate},#{serviceDate},#{status},#{createdBy},#{relatedType},#{relatedId},#{employeeUserId},#{requestKey})")@Options(useGeneratedKeys=true,keyProperty="id")int insert(HotelExpense e);
 @Select("SELECT * FROM hotel_expense WHERE created_by=#{actor} AND request_key=#{key}")HotelExpense byRequest(@Param("actor")Long actor,@Param("key")String key);@Select("SELECT * FROM hotel_expense WHERE id=#{id}")HotelExpense find(Long id);@Select("SELECT * FROM hotel_expense WHERE id=#{id} FOR UPDATE")HotelExpense lock(Long id);
 @Update("UPDATE hotel_expense SET status=1 WHERE id=#{id} AND status=0")int submit(Long id);
 @Update("UPDATE hotel_expense SET status=2,approved_by=#{actor},approved_at=#{at} WHERE id=#{id} AND status=1")int approve(@Param("id")Long id,@Param("actor")Long actor,@Param("at")LocalDateTime at);
 @Update("UPDATE hotel_expense SET status=4,rejected_by=#{actor},rejected_at=#{at},rejection_reason=#{reason} WHERE id=#{id} AND status=1")int reject(@Param("id")Long id,@Param("actor")Long actor,@Param("at")LocalDateTime at,@Param("reason")String reason);
 @Update("UPDATE hotel_expense SET status=5 WHERE id=#{id} AND status IN(0,1)")int cancel(Long id);
 @Update("UPDATE hotel_expense SET status=3,posting_business_date=#{date},paid_by=#{actor},paid_at=#{at},payment_method=#{method},external_reference=#{reference} WHERE id=#{id} AND status=2")int paid(@Param("id")Long id,@Param("date")LocalDate date,@Param("actor")Long actor,@Param("at")LocalDateTime at,@Param("method")String method,@Param("reference")String reference);
 @Insert("INSERT IGNORE INTO hotel_expense_action(expense_id,action_type,request_key,operator_user_id,reason) VALUES(#{id},#{type},#{key},#{actor},#{reason})")int action(@Param("id")Long id,@Param("type")String type,@Param("key")String key,@Param("actor")Long actor,@Param("reason")String reason);
 @Insert("INSERT INTO hotel_expense_reversal(expense_id,amount,reason,request_key,initiated_by,status) VALUES(#{expenseId},#{amount},#{reason},#{requestKey},#{initiatedBy},0)")@Options(useGeneratedKeys=true,keyProperty="id")int insertReversal(ExpenseReversal r);
 @Select("SELECT * FROM hotel_expense_reversal WHERE request_key=#{key}")ExpenseReversal reversalByKey(String key);@Select("SELECT * FROM hotel_expense_reversal WHERE id=#{id}")ExpenseReversal reversal(Long id);@Select("SELECT * FROM hotel_expense_reversal WHERE id=#{id} FOR UPDATE")ExpenseReversal lockReversal(Long id);
 @Select("SELECT * FROM hotel_expense_reversal WHERE expense_id=#{expense} ORDER BY id")List<ExpenseReversal> reversals(Long expense);
 @Select("SELECT COALESCE(SUM(amount),0) FROM hotel_expense_reversal WHERE expense_id=#{expense} AND status IN(0,1)")java.math.BigDecimal reservedReversal(Long expense);
 @Select("SELECT COALESCE(SUM(amount),0) FROM hotel_expense_reversal WHERE expense_id=#{expense} AND status=1")java.math.BigDecimal completedReversal(Long expense);
 @Update("UPDATE hotel_expense_reversal SET status=1,approved_by=#{actor},posting_business_date=#{date},reversed_at=#{at},external_reference=#{reference} WHERE id=#{id} AND status=0")int approveReversal(@Param("id")Long id,@Param("actor")Long actor,@Param("date")LocalDate date,@Param("at")LocalDateTime at,@Param("reference")String reference);
 @Update("UPDATE hotel_expense_reversal SET status=2,rejected_by=#{actor},rejection_reason=#{reason} WHERE id=#{id} AND status=0")int rejectReversal(@Param("id")Long id,@Param("actor")Long actor,@Param("reason")String reason);
 @Select("<script>SELECT * FROM hotel_expense <where><if test='from!=null'>expense_date&gt;=#{from}</if><if test='to!=null'> AND expense_date&lt;=#{to}</if><if test='status!=null'> AND status=#{status}</if><if test='category!=null'> AND category=#{category}</if><if test='createdBy!=null'> AND created_by=#{createdBy}</if></where> ORDER BY expense_date DESC,id DESC LIMIT #{offset},#{size}</script>")List<HotelExpense> page(@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("status")Integer status,@Param("category")String category,@Param("createdBy")Long createdBy,@Param("offset")int offset,@Param("size")int size);
 @Select("<script>SELECT COUNT(*) FROM hotel_expense <where><if test='from!=null'>expense_date&gt;=#{from}</if><if test='to!=null'> AND expense_date&lt;=#{to}</if><if test='status!=null'> AND status=#{status}</if><if test='category!=null'> AND category=#{category}</if><if test='createdBy!=null'> AND created_by=#{createdBy}</if></where></script>")long count(@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("status")Integer status,@Param("category")String category,@Param("createdBy")Long createdBy);
 @Select("SELECT category,SUM(amount) amount FROM (SELECT category,amount FROM hotel_expense WHERE status=3 AND posting_business_date BETWEEN #{from} AND #{to} UNION ALL SELECT e.category,-r.amount FROM hotel_expense_reversal r JOIN hotel_expense e ON e.id=r.expense_id WHERE r.status=1 AND r.posting_business_date BETWEEN #{from} AND #{to}) x GROUP BY category ORDER BY category")List<CategoryExpense> paidByCategory(@Param("from")LocalDate from,@Param("to")LocalDate to);
}
