package com.johnny.hotel.financeexpense;import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.time.*;
@RestController@RequestMapping("/api/finance/expenses")@RequiredArgsConstructor public class HotelExpenseController{private final HotelExpenseService service;
 @PostMapping @PreAuthorize("hasAnyRole('FINANCE','MANAGER','OWNER','SUPER_ADMIN')")public Result<HotelExpense>create(@Valid@RequestBody ExpenseCommands.Create c,Authentication a){return Result.success(service.create(c,actor(a)));}
 @PostMapping("/{id}/submit")@PreAuthorize("hasAnyRole('FINANCE','MANAGER','OWNER','SUPER_ADMIN')")public Result<HotelExpense>submit(@PathVariable Long id,@Valid@RequestBody ExpenseCommands.Action c,Authentication a){return Result.success(service.submit(id,c,actor(a)));}
 @PostMapping("/{id}/approve")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<HotelExpense>approve(@PathVariable Long id,@Valid@RequestBody ExpenseCommands.Action c,Authentication a){return Result.success(service.approve(id,c,actor(a)));}
 @PostMapping("/{id}/reject")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<HotelExpense>reject(@PathVariable Long id,@Valid@RequestBody ExpenseCommands.Action c,Authentication a){return Result.success(service.reject(id,c,actor(a)));}
 @PostMapping("/{id}/cancel")@PreAuthorize("hasAnyRole('FINANCE','MANAGER','OWNER','SUPER_ADMIN')")public Result<HotelExpense>cancel(@PathVariable Long id,@Valid@RequestBody ExpenseCommands.Action c,Authentication a){return Result.success(service.cancel(id,c,actor(a)));}
 @PostMapping("/{id}/pay")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<HotelExpense>pay(@PathVariable Long id,@Valid@RequestBody ExpenseCommands.Pay c,Authentication a){return Result.success(service.pay(id,c,actor(a)));}
 @PostMapping("/{id}/reversals")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<ExpenseReversal>requestReversal(@PathVariable Long id,@Valid@RequestBody ExpenseReversalCommands.Request c,Authentication a){return Result.success(service.requestReversal(id,c,actor(a)));}
 @PostMapping("/reversals/{id}/approve")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<ExpenseReversal>approveReversal(@PathVariable Long id,@Valid@RequestBody ExpenseReversalCommands.Approve c,Authentication a){return Result.success(service.approveReversal(id,c,actor(a)));}
 @PostMapping("/reversals/{id}/reject")@PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")public Result<ExpenseReversal>rejectReversal(@PathVariable Long id,@Valid@RequestBody ExpenseReversalCommands.Reject c,Authentication a){return Result.success(service.rejectReversal(id,c,actor(a)));}
 @GetMapping("/{id}")@PreAuthorize("hasAnyRole('FINANCE','MANAGER','OWNER','SUPER_ADMIN')")public Result<ExpenseDetail>detail(@PathVariable Long id,Authentication a){return Result.success(service.detail(id,actor(a)));}
 @GetMapping @PreAuthorize("hasAnyRole('FINANCE','MANAGER','OWNER','SUPER_ADMIN')")public Result<PageResult<HotelExpense>>list(@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,@RequestParam(required=false)Integer status,@RequestParam(required=false)String category,@RequestParam(required=false)Long createdBy,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize,Authentication a){return Result.success(service.query(from,to,status,category,createdBy,page,pageSize,actor(a)));}
 private Long actor(Authentication a){if(a==null||!(a.getDetails() instanceof Long id))throw new org.springframework.security.access.AccessDeniedException("Authenticated user id required");return id;}
}
