package com.johnny.hotel.extras;
import com.johnny.hotel.dto.FolioItemCommand;import com.johnny.hotel.entity.*;import com.johnny.hotel.enums.BookingStatus;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.mapper.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.service.FolioService;import com.johnny.hotel.task.HotelTaskService;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;import static com.johnny.hotel.service.support.BillingRules.*;
@Service@RequiredArgsConstructor public class GuestExtrasServiceImpl implements GuestExtrasService{
 private final ExtrasMapper db;private final ExtrasAccess access;private final BookingMapper bookings;private final com.johnny.hotel.stay.StayContext stayContext; private final com.johnny.hotel.stay.StayMapper stays;private final FolioMapper folios;private final FolioService ledger;private final HotelTaskService tasks;private final PaginationSupport pagination;private final Clock clock;
 private String text(String s,int max,boolean required){if(s==null||s.isBlank()){if(required)throw new BusinessException("Required text is missing");return null;}s=s.trim();require(s.length()<=max,"Text is too long");return s;}private BigDecimal qty(BigDecimal q){q=money(q,10);require(q.signum()>0,"Quantity must be positive");return q;}private BigDecimal amount(BigDecimal q,BigDecimal p){return money(q.multiply(p),12);}private LocalDate today(){return LocalDate.now(clock);}private void oneRow(int n){one(n);}private Booking booking(Long id,ExtrasAccess.Actor a){var b=stayContext.lockReservation(id);require(b!=null,"Booking does not exist");if(a.customer()&&!a.id().equals(b.getUserId()))throw new BusinessException(404,"Resource not found");require(stays.byBooking(b.getId())!=null && stays.byBooking(b.getId()).getStatus()==1,"Guest extras require a checked-in booking");var f=folios.selectByStayIdForUpdate(id);require(f!=null&&f.getClosedTime()==null,"Folio is missing or finalized");return b;}private void visible(Long customer,ExtrasAccess.Actor a){if(a.customer()&&!a.id().equals(customer))throw new BusinessException(404,"Resource not found");}
 @Override@Transactional public ChargeCatalog createCatalog(ExtrasRequests.Catalog r){var a=access.actor();access.manager(a);var c=catalog(r,null);c.setStatus(1);oneRow(db.insertCatalog(c));return db.catalog(c.getId());}
 @Override@Transactional public ChargeCatalog updateCatalog(Long id,ExtrasRequests.Catalog r){var a=access.actor();access.manager(a);require(db.lockCatalog(id)!=null,"Catalog item does not exist");var c=catalog(r,id);oneRow(db.updateCatalog(c));return db.catalog(id);}
 private BigDecimal positivePrice(BigDecimal value){var p=money(value,12);require(p.signum()>0,"Catalog price must be positive");return p;}
 private ChargeCatalog catalog(ExtrasRequests.Catalog r,Long id){require(r!=null&&r.getType()!=null,"Catalog request is required");return ChargeCatalog.builder().id(id).code(text(r.getCode(),50,true).toUpperCase(Locale.ROOT)).name(text(r.getName(),120,true)).chargeType(r.getType().getCode()).category(text(r.getCategory(),80,true)).unitPrice(positivePrice(r.getUnitPrice())).description(text(r.getDescription(),500,false)).build();}
 @Override@Transactional public ChargeCatalog setCatalogStatus(Long id,boolean active){var a=access.actor();access.manager(a);var c=db.lockCatalog(id);require(c!=null,"Catalog item does not exist");if(c.getStatus()!=(active?1:0))oneRow(db.catalogStatus(id,c.getStatus(),active?1:0));return db.catalog(id);}
 @Override public PageResult<ChargeCatalog> catalogs(Integer type,Integer status,String query,Integer page,Integer size){var a=access.actor();String q=text(query,120,false);if(a.customer()||a.staff()&&!a.manager()){status=1;}if(type!=null)ChargeType.fromCode(type);if(status!=null)require(status==0||status==1,"Invalid catalog status");boolean search=type!=null||status!=null||q!=null;var w=pagination.window(page,size,search);int limit=pagination.limit(w);return pagination.result(w,limit==0?List.of():db.catalogPage(type,status,q,w.offset(),limit),db.catalogCount(type,status,q));}
 @Override@Transactional public GuestServiceOrder createService(Long stayId,ExtrasRequests.ServiceOrder r){var a=access.actor();if(a.finance())throw access.denied();require(r!=null,"Service request is required");var b=booking(stayId,a);String key=text(r.getRequestKey(),60,true);var old=db.serviceByKey(a.id(),key);if(old!=null){require(old.getStayId().equals(stayId)&&old.getCatalogId().equals(r.getCatalogId())&&old.getQuantity().compareTo(qty(r.getQuantity()))==0,"Request key already represents another service");return old;}var c=db.lockCatalog(r.getCatalogId());require(c!=null&&c.getStatus()==1&&c.getChargeType()==0,"Active service catalog item required");var q=qty(r.getQuantity());var task=tasks.createGuestService(stayId,"GUEST_SERVICE:"+a.id()+":"+key,c.getName(),text(r.getNote(),500,false),a.id());var f=folios.selectByStayIdForUpdate(stayId);var o=GuestServiceOrder.builder().stayId(stayId).folioId(f.getId()).customerUserId(b.getUserId()).catalogId(c.getId()).taskId(task.getId()).catalogCodeSnapshot(c.getCode()).nameSnapshot(c.getName()).unitPriceSnapshot(c.getUnitPrice()).quantity(q).amount(amount(q,c.getUnitPrice())).requestNote(text(r.getNote(),500,false)).requestKey(key).status(0).requestedBy(a.id()).build();oneRow(db.insertService(o));return db.service(o.getId());}
 private GuestServiceOrder service(Long id,ExtrasAccess.Actor a,boolean lock){var o=lock?db.lockService(id):db.service(id);require(o!=null,"Service order does not exist");visible(o.getCustomerUserId(),a);return o;}
 @Override@Transactional public GuestServiceOrder claimService(Long id){var a=access.actor();access.operator(a);var o=service(id,a,true);require(o.getStatus()==0,"Service is not pending");tasks.claimGuestService(o.getTaskId());return db.service(id);}
 @Override@Transactional public GuestServiceOrder completeService(Long id,String note,boolean force){var a=access.actor();access.operator(a);var o=service(id,a,true);if(o.getStatus()==2)return o;require(o.getStatus()==1||force&&o.getStatus()==0,"Service must be in progress");booking(o.getStayId(),a);tasks.completeGuestService(o.getTaskId(),text(note,500,false),force);var item=ledger.addItem(folios.selectById(o.getFolioId()).getStayId(),FolioItemCommand.builder().itemType("SERVICE_CHARGE").description(o.getNameSnapshot()).businessDate(today()).quantity(o.getQuantity()).unitPrice(o.getUnitPriceSnapshot()).amount(o.getAmount()).sourceType("GUEST_SERVICE_ORDER").sourceId(o.getId()).refundable(true).eventKey("GUEST_SERVICE_ORDER:"+o.getId()).build(),a.id());oneRow(db.completeService(id,item.getId(),a.id()));return db.service(id);}
 @Override@Transactional public GuestServiceOrder cancelService(Long id,String note){var a=access.actor();var o=service(id,a,true);if(o.getStatus()==3)return o;if(a.customer()){require(o.getRequestedBy().equals(a.id())&&o.getStatus()==0,"Customer may only cancel their own pending service");}else access.operator(a);tasks.cancelGuestService(o.getTaskId(),text(note,500,false));oneRow(db.cancelService(id,a.id()));return db.service(id);}
 @Override public PageResult<GuestServiceOrder> services(Long booking,Integer status,Integer page,Integer size){var a=access.actor();if(status!=null)require(status>=0&&status<=3,"Invalid service status");Long customer=a.customer()?a.id():null;if(a.customer()&&booking!=null){var b=stayContext.reservation(booking);if(b==null||!a.id().equals(b.getUserId()))throw new BusinessException(404,"Resource not found");}boolean search=booking!=null||status!=null||customer!=null;var w=pagination.window(page,size,search);int limit=pagination.limit(w);return pagination.result(w,limit==0?List.of():db.servicePage(booking,customer,status,w.offset(),limit),db.serviceCount(booking,customer,status));}
 @Override@Transactional public GuestPurchase createPurchase(Long stayId,ExtrasRequests.Purchase r){var a=access.actor();if(a.finance())throw access.denied();require(r!=null&&r.getItems()!=null&&!r.getItems().isEmpty(),"Purchase items are required");var b=booking(stayId,a);String key=text(r.getRequestKey(),100,true);var old=db.purchaseByKey(a.id(),key);if(old!=null){require(old.getStayId().equals(stayId)&&samePurchase(old,r),"Request key already represents another purchase");return old;}var seen=new HashSet<Long>();var lines=new ArrayList<GuestPurchaseItem>();BigDecimal total=BigDecimal.ZERO;for(var x:r.getItems()){require(x!=null&&x.getCatalogId()!=null&&seen.add(x.getCatalogId()),"Product lines must be unique");var c=db.lockCatalog(x.getCatalogId());require(c!=null&&c.getStatus()==1&&c.getChargeType()==1,"Active product catalog item required");var q=qty(x.getQuantity());var sum=amount(q,c.getUnitPrice());total=total.add(sum);lines.add(GuestPurchaseItem.builder().catalogId(c.getId()).catalogCodeSnapshot(c.getCode()).nameSnapshot(c.getName()).unitPriceSnapshot(c.getUnitPrice()).quantity(q).amount(sum).build());}var f=folios.selectByStayIdForUpdate(stayId);var p=GuestPurchase.builder().stayId(stayId).folioId(f.getId()).customerUserId(b.getUserId()).requestKey(key).status(0).totalAmount(money(total,12)).requestedBy(a.id()).build();oneRow(db.insertPurchase(p));for(var x:lines){x.setPurchaseId(p.getId());oneRow(db.insertPurchaseItem(x));}return db.purchase(p.getId());}
 private boolean samePurchase(GuestPurchase p,ExtrasRequests.Purchase r){var persisted=db.purchaseItems(p.getId());if(persisted.size()!=r.getItems().size())return false;var requested=new HashMap<Long,BigDecimal>();for(var x:r.getItems()){if(x==null||x.getCatalogId()==null)return false;requested.put(x.getCatalogId(),qty(x.getQuantity()));}return persisted.stream().allMatch(x->requested.containsKey(x.getCatalogId())&&requested.get(x.getCatalogId()).compareTo(x.getQuantity())==0);}
 private GuestPurchase purchase(Long id,ExtrasAccess.Actor a,boolean lock){var p=lock?db.lockPurchase(id):db.purchase(id);require(p!=null,"Purchase does not exist");visible(p.getCustomerUserId(),a);return p;}
 @Override@Transactional public GuestPurchase confirmPurchase(Long id){var a=access.actor();access.operator(a);var p=purchase(id,a,true);if(p.getStatus()==1)return p;require(p.getStatus()==0,"Purchase is not pending");booking(p.getStayId(),a);var lines=db.purchaseItems(id);var commands=lines.stream().map(x->FolioItemCommand.builder().itemType("SERVICE_CHARGE").description(x.getNameSnapshot()).businessDate(today()).quantity(x.getQuantity()).unitPrice(x.getUnitPriceSnapshot()).amount(x.getAmount()).sourceType("GUEST_PURCHASE_ITEM").sourceId(x.getId()).refundable(true).eventKey("GUEST_PURCHASE_ITEM:"+x.getId()).build()).toList();var items=ledger.addItems(folios.selectById(p.getFolioId()).getStayId(),commands,a.id());for(int i=0;i<lines.size();i++)oneRow(db.linkPurchaseItem(lines.get(i).getId(),items.get(i).getId()));oneRow(db.confirmPurchase(id,a.id()));return db.purchase(id);}
 @Override@Transactional public GuestPurchase cancelPurchase(Long id){var a=access.actor();var p=purchase(id,a,true);if(p.getStatus()==2)return p;if(a.customer())require(p.getRequestedBy().equals(a.id())&&p.getStatus()==0,"Customer may only cancel their own pending purchase");else access.operator(a);oneRow(db.cancelPurchase(id,a.id()));return db.purchase(id);}
 @Override public PageResult<GuestPurchase> purchases(Long booking,Integer status,Integer page,Integer size){var a=access.actor();if(status!=null)require(status>=0&&status<=2,"Invalid purchase status");Long customer=a.customer()?a.id():null;if(a.customer()&&booking!=null){var b=stayContext.reservation(booking);if(b==null||!a.id().equals(b.getUserId()))throw new BusinessException(404,"Resource not found");}boolean search=booking!=null||status!=null||customer!=null;var w=pagination.window(page,size,search);int limit=pagination.limit(w);return pagination.result(w,limit==0?List.of():db.purchasePage(booking,customer,status,w.offset(),limit),db.purchaseCount(booking,customer,status));}
 @Override public List<GuestPurchaseItem> purchaseItems(Long id){var a=access.actor();purchase(id,a,false);return db.purchaseItems(id);}
}
