package com.johnny.hotel.extras;import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.List;
@RestController@RequiredArgsConstructor@RequestMapping("/api/extras")@PreAuthorize("hasAnyRole('CUSTOMER','STAFF','FINANCE','MANAGER','OWNER','SUPER_ADMIN')") public class GuestExtrasController{private final GuestExtrasService service;
 @GetMapping("/catalog")public Result<PageResult<ChargeCatalog>> catalogs(@RequestParam(required=false)Integer type,@RequestParam(required=false)Integer status,@RequestParam(required=false)String query,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.catalogs(type,status,query,page,pageSize));}
 @PostMapping("/catalog")@PreAuthorize("hasAnyRole('MANAGER','OWNER','SUPER_ADMIN')")public Result<ChargeCatalog> createCatalog(@Valid@RequestBody ExtrasRequests.Catalog r){return Result.success(service.createCatalog(r));}
 @PutMapping("/catalog/{id}")@PreAuthorize("hasAnyRole('MANAGER','OWNER','SUPER_ADMIN')")public Result<ChargeCatalog> updateCatalog(@PathVariable Long id,@Valid@RequestBody ExtrasRequests.Catalog r){return Result.success(service.updateCatalog(id,r));}
 @PostMapping("/catalog/{id}/enable")@PreAuthorize("hasAnyRole('MANAGER','OWNER','SUPER_ADMIN')")public Result<ChargeCatalog> enable(@PathVariable Long id){return Result.success(service.setCatalogStatus(id,true));}
 @PostMapping("/catalog/{id}/disable")@PreAuthorize("hasAnyRole('MANAGER','OWNER','SUPER_ADMIN')")public Result<ChargeCatalog> disable(@PathVariable Long id){return Result.success(service.setCatalogStatus(id,false));}
 @PostMapping("/stays/{stayId}/service-orders")@PreAuthorize("hasAnyRole('CUSTOMER','STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestServiceOrder> createService(@PathVariable Long stayId,@Valid@RequestBody ExtrasRequests.ServiceOrder r){return Result.success(service.createService(stayId,r));}
 @GetMapping("/service-orders")public Result<PageResult<GuestServiceOrder>> services(@RequestParam(required=false)Long stayId,@RequestParam(required=false)Integer status,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.services(stayId,status,page,pageSize));}
 @PostMapping("/service-orders/{id}/claim")@PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestServiceOrder> claim(@PathVariable Long id){return Result.success(service.claimService(id));}
 @PostMapping("/service-orders/{id}/complete")@PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestServiceOrder> complete(@PathVariable Long id,@Valid@RequestBody(required=false)ExtrasRequests.Note r,@RequestParam(defaultValue="false")boolean force){return Result.success(service.completeService(id,r==null?null:r.getNote(),force));}
 @PostMapping("/service-orders/{id}/cancel")@PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestServiceOrder> cancel(@PathVariable Long id,@Valid@RequestBody(required=false)ExtrasRequests.Note r){return Result.success(service.cancelService(id,r==null?null:r.getNote()));}
 @PostMapping("/stays/{stayId}/purchases")@PreAuthorize("hasAnyRole('CUSTOMER','STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestPurchase> createPurchase(@PathVariable Long stayId,@Valid@RequestBody ExtrasRequests.Purchase r){return Result.success(service.createPurchase(stayId,r));}
 @GetMapping("/purchases")public Result<PageResult<GuestPurchase>> purchases(@RequestParam(required=false)Long stayId,@RequestParam(required=false)Integer status,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.purchases(stayId,status,page,pageSize));}
 @GetMapping("/purchases/{id}/items")public Result<List<GuestPurchaseItem>> purchaseItems(@PathVariable Long id){return Result.success(service.purchaseItems(id));}
 @PostMapping("/purchases/{id}/confirm")@PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestPurchase> confirm(@PathVariable Long id){return Result.success(service.confirmPurchase(id));}
 @PostMapping("/purchases/{id}/cancel")@PreAuthorize("hasAnyRole('CUSTOMER','STAFF','MANAGER','OWNER','SUPER_ADMIN')")public Result<GuestPurchase> cancelPurchase(@PathVariable Long id){return Result.success(service.cancelPurchase(id));}
}
