package com.johnny.hotel.finance;
import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.finance.FinanceOperationsModels.*;import com.johnny.hotel.financeexpense.HotelExpenseMapper;import com.johnny.hotel.pagination.*;import com.johnny.hotel.payment.HotelTransactionRecord;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true) public class FinanceOperationsService {
 private static final Set<String>DIRECTIONS=Set.of("EXTERNAL_IN","EXTERNAL_OUT","INTERNAL_TRANSFER");private final FinanceOperationsMapper db;private final HotelExpenseMapper expenses;private final com.johnny.hotel.ar.ArMapper ar;private final PaginationSupport pages;
 public Dashboard dashboard(LocalDate from,LocalDate to){range(from,to);var d=db.dashboard(from,to);var total=paidExpenses(from,to).stream().map(CategoryExpense::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);d.setTotalPaidExpense(total);d.setNetCashOperatingMovement(d.getNetExternalCashMovement());d.setArOutstanding(ar.totalOutstanding());return d;}
 public List<CategoryExpense> paidExpenses(LocalDate from,LocalDate to){range(from,to);return expenses.paidByCategory(from,to);}
 public PageResult<DailyFinancialSummary> summaries(LocalDate from,LocalDate to,Integer page,Integer size){range(from,to);var w=pages.window(page,size,true);return pages.result(w,db.summaryPage(from,to,w.offset(),pages.limit(w)),db.summaryCount(from,to));}
 public PageResult<RevenueRecognition> revenue(LocalDate rf,LocalDate rt,LocalDate bf,LocalDate bt,String category,String sourceType,Long stayId,Long folioId,Integer page,Integer size){optionalRange(rf,rt);optionalRange(bf,bt);var w=pages.window(page,size,true);String c=norm(category),s=norm(sourceType);return pages.result(w,db.revenuePage(rf,rt,bf,bt,c,s,stayId,folioId,w.offset(),pages.limit(w)),db.revenueCount(rf,rt,bf,bt,c,s,stayId,folioId));}
 public PageResult<HotelTransactionRecord> movements(LocalDate bf,LocalDate bt,LocalDateTime of,LocalDateTime ot,String direction,String method,String provider,String sourceType,String businessType,Long businessId,Integer page,Integer size){optionalRange(bf,bt);if(of!=null&&ot!=null&&!of.isBefore(ot))throw new BusinessException("occurredFrom must be before occurredTo");String d=norm(direction);if(d!=null&&!DIRECTIONS.contains(d))throw new BusinessException("Unsupported money movement direction");var w=pages.window(page,size,true);return pages.result(w,db.movementPage(bf,bt,of,ot,d,norm(method),norm(provider),norm(sourceType),norm(businessType),businessId,w.offset(),pages.limit(w)),db.movementCount(bf,bt,of,ot,d,norm(method),norm(provider),norm(sourceType),norm(businessType),businessId));}
 public PageResult<FinanceException> exceptions(Integer page,Integer size){var w=pages.window(page,size,true);return pages.result(w,db.exceptionPage(w.offset(),pages.limit(w)),db.exceptionCount());}
 private void range(LocalDate from,LocalDate to){if(from==null||to==null)throw new BusinessException("Business date range is required");optionalRange(from,to);}private void optionalRange(LocalDate from,LocalDate to){if(from!=null&&to!=null&&from.isAfter(to))throw new BusinessException("Date range is invalid");}private String norm(String v){return v==null||v.isBlank()?null:v.trim().toUpperCase(Locale.ROOT);}
}
