package com.johnny.hotel.finance;
import com.johnny.hotel.common.Result;import com.johnny.hotel.finance.FinanceOperationsModels.*;import com.johnny.hotel.pagination.PageResult;import com.johnny.hotel.payment.HotelTransactionRecord;import lombok.RequiredArgsConstructor;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.*;
import java.util.List;
@RestController @RequestMapping("/api/finance/operations") @RequiredArgsConstructor @PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')") public class FinanceOperationsController {private final FinanceOperationsService service;
 @GetMapping("/dashboard")public Result<Dashboard> dashboard(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){return Result.success(service.dashboard(from,to));}
 @GetMapping("/expense-by-category")public Result<List<CategoryExpense>> expenses(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){return Result.success(service.paidExpenses(from,to));}
 @GetMapping("/daily-summaries")public Result<PageResult<DailyFinancialSummary>> summaries(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.summaries(from,to,page,pageSize));}
 @GetMapping("/revenue")public Result<PageResult<RevenueRecognition>> revenue(@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate revenueFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate revenueTo,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate recognitionFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate recognitionTo,@RequestParam(required=false)String category,@RequestParam(required=false)String sourceType,@RequestParam(required=false)Long stayId,@RequestParam(required=false)Long folioId,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.revenue(revenueFrom,revenueTo,recognitionFrom,recognitionTo,category,sourceType,stayId,folioId,page,pageSize));}
 @GetMapping("/money-movements")public Result<PageResult<HotelTransactionRecord>> movements(@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate businessFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate businessTo,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime occurredFrom,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime occurredTo,@RequestParam(required=false)String direction,@RequestParam(required=false)String paymentMethod,@RequestParam(required=false)String provider,@RequestParam(required=false)String sourceType,@RequestParam(required=false)String businessReferenceType,@RequestParam(required=false)Long businessReferenceId,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.movements(businessFrom,businessTo,occurredFrom,occurredTo,direction,paymentMethod,provider,sourceType,businessReferenceType,businessReferenceId,page,pageSize));}
 @GetMapping("/exceptions")public Result<PageResult<FinanceException>> exceptions(@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.exceptions(page,pageSize));}
}
