server:
  port: 8080

spring:
  application:
    name: hotel-backend

  datasource:
    url: ${DB_URL}?useUnicode=true&characterEncoding=utf-8&serverTimezone=America/Toronto
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial existing database

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.johnny.hotel.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.johnny.hotel: debug

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000