package com.johnny.hotel.task;
import com.johnny.hotel.entity.*; import com.johnny.hotel.exception.BusinessException; import com.johnny.hotel.mapper.*;
import lombok.RequiredArgsConstructor; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor public class HotelTaskServiceImpl implements HotelTaskService {
 private final HotelTaskMapper tasks; private final TaskAssignmentMapper assignments; private final TaskRecordMapper records; private final SysUserMapper users; private final SysRoleMapper roles; private final SysAuditLogMapper audits; private final Clock clock;
 private record Actor(Long id,boolean manager){}
 private Actor actor(){var a=SecurityContextHolder.getContext().getAuthentication();if(a==null||!a.isAuthenticated()||!(a.getDetails() instanceof Long id))throw denied();return actor(id);}
 private Actor actor(Long id){var u=users.selectById(id);var rs=roles.selectRolesByUserId(id).stream().map(SysRole::getRoleCode).collect(Collectors.toSet());if(u==null||!Integer.valueOf(1).equals(u.getStatus())||rs.contains("CUSTOMER")||rs.contains("HR_ADMIN"))throw denied();boolean manager=rs.stream().anyMatch(Set.of("MANAGER","OWNER","SUPER_ADMIN")::contains);if(!manager&&!rs.contains("STAFF"))throw denied();return new Actor(id,manager);}
 private AccessDeniedException denied(){return new AccessDeniedException("Hotel task access denied");} private void require(boolean ok,String msg){if(!ok)throw new BusinessException(msg);} private void conflict(boolean ok){if(!ok)throw new BusinessException(409,"Task state changed or transition is not allowed");}
 private HotelTask found(HotelTask t){if(t==null)throw new BusinessException(404,"Task does not exist");return t;} private LocalDateTime now(){return LocalDateTime.now(clock).truncatedTo(ChronoUnit.MICROS);} private void manager(Actor a){if(!a.manager())throw denied();}
 private void record(Long task,Long assignment,TaskRecordType type,Long actor,String detail){conflict(records.insert(TaskRecord.builder().taskId(task).assignmentId(assignment).recordType(type.getCode()).actorUserId(actor).detail(normalize(detail)).build())==1);}
 private String normalize(String text){if(text==null||text.isBlank())return null;String v=text.trim();require(v.length()<=500,"Note must be at most 500 characters");return v;}
 private void audit(Long actor,Long task,String action){conflict(audits.insert(SysAuditLog.builder().operatorId(actor).action(action).detail("Hotel task "+task).build())==1);}
 @Override @Transactional public HotelTask createGeneral(TaskRequests.CreateGeneral r){var a=actor();String key=r.getRequestKey().trim(),title=r.getTitle().trim();var old=tasks.byRequest(a.id(),key);if(old!=null){require(old.getTitle().equals(title),"Request key already represents another task");return old;}var t=HotelTask.builder().taskType(TaskType.GENERAL.getCode()).status(TaskStatus.PENDING.getCode()).assignmentMode(TaskAssignmentMode.CLAIMABLE.getCode()).title(title).description(normalize(r.getDescription())).requestKey(key).createdBy(a.id()).build();conflict(tasks.insert(t)==1);record(t.getId(),null,TaskRecordType.TASK_CREATED,a.id(),"General task created");audit(a.id(),t.getId(),"CREATE_TASK");return tasks.find(t.getId());}
 @Override @Transactional(propagation=Propagation.MANDATORY) public HotelTask createTurnover(Long roomId,Long assignmentId,Long actorId){actor(actorId);String key="ROOM_TURNOVER_ASSIGNMENT:"+assignmentId;var old=tasks.bySourceForUpdate(key);if(old!=null)return old;var t=HotelTask.builder().taskType(0).status(0).assignmentMode(0).title("Room turnover for assignment "+assignmentId).description("Room "+roomId+" after assignment "+assignmentId).sourceKey(key).createdBy(actorId).build();conflict(tasks.insert(t)==1);record(t.getId(),null,TaskRecordType.TASK_CREATED,actorId,"Turnover task created");return t;}
 @Override public List<HotelTask> list(Integer status,Integer type,Integer page,Integer size){actor();if(status!=null)require(status>=0&&status<=3,"Invalid task status");if(type!=null)require(type>=0&&type<=1,"Invalid task type");int p=page==null?1:page,s=size==null?50:size;require(p>0&&s>0&&s<=100&&((long)p-1)*s<=Integer.MAX_VALUE,"Invalid pagination");return tasks.page(status,type,(p-1)*s,s);}
 @Override public TaskView get(Long id){actor();return view(found(tasks.find(id)));} @Override public List<TaskAssignment> myTodo(){return assignments.todo(actor().id());}
 private TaskView view(HotelTask t){return TaskView.builder().task(t).assignments(assignments.byTask(t.getId())).records(records.byTask(t.getId())).build();}
 @Override @Transactional public TaskView claim(Long id){var a=actor();var t=found(tasks.lock(id));conflict(t.getStatus()==0&&t.getAssignmentMode()==0&&assignments.currentCount(id)==0);var n=now();var x=TaskAssignment.builder().taskId(id).assigneeUserId(a.id()).assignedBy(a.id()).status(1).assignmentRound(assignments.maxRound(id)+1).isCurrent(1).acceptedTime(n).build();conflict(assignments.insert(x)==1);conflict(tasks.transition(id,0,1,n)==1);record(id,x.getId(),TaskRecordType.TASK_CLAIMED,a.id(),null);audit(a.id(),id,"CLAIM_TASK");return view(tasks.find(id));}
 @Override @Transactional public TaskView accept(Long id){var a=actor();var t=found(tasks.lock(id));conflict(t.getStatus()==0||t.getStatus()==1);var x=assignments.currentForUser(id,a.id());if(x==null)throw denied();conflict(x.getStatus()==0);var n=now();conflict(assignments.accept(x.getId(),n)==1);if(t.getStatus()==0)conflict(tasks.transition(id,0,1,n)==1);record(id,x.getId(),TaskRecordType.TASK_ACCEPTED,a.id(),null);audit(a.id(),id,"ACCEPT_TASK");return view(tasks.find(id));}
 @Override @Transactional public TaskView complete(Long id,String note){var a=actor();var t=found(tasks.lock(id));var x=assignments.currentForUser(id,a.id());if(x==null)throw denied();conflict(t.getStatus()==1&&x.getStatus()==1);var n=now();conflict(assignments.complete(x.getId(),n)==1);record(id,x.getId(),TaskRecordType.TASK_COMPLETED,a.id(),note);if(assignments.incompleteCount(id)==0)conflict(tasks.transition(id,1,2,n)==1);audit(a.id(),id,"COMPLETE_TASK");return view(tasks.find(id));}
 private List<Long> targets(TaskRequests.Assign r){var ids=new LinkedHashSet<>(r.getAssigneeUserIds());require(!ids.isEmpty()&&ids.size()==r.getAssigneeUserIds().size(),"Assignees must be unique");for(Long id:ids)actor(id);return new ArrayList<>(ids);}
 private void addAssignments(HotelTask t,List<Long> ids,Actor a,int round,TaskRecordType event,String note){require(t.getTaskType()!=0||ids.size()==1,"Room turnover only allows one assignee");int mode=ids.size()==1?1:2;conflict(tasks.resetAssignment(t.getId(),0,mode)==1);for(Long id:ids){var x=TaskAssignment.builder().taskId(t.getId()).assigneeUserId(id).assignedBy(a.id()).status(0).assignmentRound(round).isCurrent(1).build();conflict(assignments.insert(x)==1);record(t.getId(),x.getId(),event,a.id(),note);}}
 @Override @Transactional public TaskView assign(Long id,TaskRequests.Assign r){var a=actor();manager(a);var t=found(tasks.lock(id));conflict((t.getStatus()==0||t.getStatus()==1)&&assignments.currentCount(id)==0);addAssignments(t,targets(r),a,assignments.maxRound(id)+1,TaskRecordType.TASK_ASSIGNED,r.getNote());audit(a.id(),id,"ASSIGN_TASK");return view(tasks.find(id));}
 @Override @Transactional public TaskView reassign(Long id,TaskRequests.Assign r){var a=actor();manager(a);var t=found(tasks.lock(id));conflict(t.getStatus()==0||t.getStatus()==1);var ids=targets(r);var n=now();assignments.endCurrent(id,n);addAssignments(t,ids,a,assignments.maxRound(id)+1,TaskRecordType.TASK_REASSIGNED,r.getNote());audit(a.id(),id,"REASSIGN_TASK");return view(tasks.find(id));}
 @Override @Transactional public TaskView cancel(Long id,String note){var a=actor();manager(a);var t=found(tasks.lock(id));conflict(t.getStatus()==0||t.getStatus()==1);var n=now();assignments.endCurrent(id,n);conflict(tasks.transition(id,t.getStatus(),3,n)==1);record(id,null,TaskRecordType.TASK_CANCELLED,a.id(),note);audit(a.id(),id,"CANCEL_TASK");return view(tasks.find(id));}
 @Override @Transactional public TaskView forceComplete(Long id,String note){var a=actor();manager(a);var t=found(tasks.lock(id));conflict(t.getStatus()==0||t.getStatus()==1);var n=now();assignments.forceComplete(id,n);conflict(tasks.forceComplete(id,n)==1);record(id,null,TaskRecordType.TASK_FORCE_COMPLETED,a.id(),note);audit(a.id(),id,"FORCE_COMPLETE_TASK");return view(tasks.find(id));}
}
