package com.johnny.hotel.wallet;
import com.johnny.hotel.cleaning.*;import com.johnny.hotel.exception.*;import com.johnny.hotel.service.RoomTurnoverTaskService;import com.johnny.hotel.task.*;import org.junit.jupiter.api.*;import org.junit.jupiter.params.ParameterizedTest;import org.junit.jupiter.params.provider.ValueSource;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.dao.DataAccessException;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.context.SecurityContextHolder;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class CleaningDevelopmentTest extends FinancialDevelopmentFixture {
 @Autowired CleaningService cleaning;@Autowired HotelTaskService tasks;@Autowired RoomTurnoverTaskService turnovers;
 CleaningRequests.Create request(String key){return CleaningRequests.Create.builder().requestKey(key).notes("Guest requested housekeeping").build();}
 StayoverCleaningRequest create(long b,String key,String role,boolean customer){as(role);return cleaning.requestStayover(sid(b),request(key),uid(role),customer);}
 long todo(long task){return jdbc.queryForObject("SELECT id FROM todo WHERE task_id=? AND is_active=1",Long.class,task);}
 CleaningRecord finish(StayoverCleaningRequest r){as("STAFF");tasks.claim(r.getTaskId());tasks.updateTodo(todo(r.getTaskId()),"ACKNOWLEDGE",null);return cleaning.complete(r.getTaskId(),"cleaned",false);}
 @Test void migrationSchemaAndEnums(){assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM flyway_schema_history WHERE version='21' AND success=1",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM flyway_schema_history WHERE version='22' AND success=1",Integer.class));assertEquals(0,CleaningType.STAYOVER.getCode());assertEquals(1,CleaningType.TURNOVER.getCode());}
 @Test void checkedInBookingRequestsStayoverWithoutChangingRoom(){long b=stay();int before=roomStatus(room1);var r=create(b,"clean-01","CUSTOMER",true);assertEquals(before,roomStatus(room1));assertEquals(active(b),r.getAssignmentId());assertEquals(room1,r.getRoomId());assertEquals(4,taskType(r.getTaskId()));as("STAFF");assertTrue(tasks.list(0,4,1,50).stream().anyMatch(t->t.getId().equals(r.getTaskId())));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));}
 @ParameterizedTest @ValueSource(ints={0,1,2,3,4}) void roomStatusNeverDeterminesStayoverEligibility(int status){long b=stay();jdbc.update("UPDATE room SET status=? WHERE id=?",status,room1);var r=create(b,"status-"+status,"STAFF",false);assertNotNull(r);assertEquals(status,roomStatus(room1));}
 @Test void repeatedHttpRequestIsIdempotentButStayAllowsMany(){long b=stay();var a=create(b,"clean-02","CUSTOMER",true);var retry=create(b,"clean-02","CUSTOMER",true);var next=create(b,"clean-03","CUSTOMER",true);assertEquals(a.getId(),retry.getId());assertNotEquals(a.getTaskId(),next.getTaskId());}
 @Test void customerCannotRequestBeforeOrAfterStay(){long b=createBooking("CUSTOMER");as("CUSTOMER");assertThrows(BusinessException.class,()->cleaning.requestStayover(Long.MAX_VALUE,request("clean-04"),uid("CUSTOMER"),true));var a=new com.johnny.hotel.dto.ApproveBookingRequest();a.setAssignedRoomId(room1);bookings.approveBooking(b,a,uid("MANAGER"));register(b);bookings.checkIn(b,uid("MANAGER"));pay(b,"300");clock.day(3);checkout(b);assertThrows(BusinessException.class,()->create(b,"clean-05","CUSTOMER",true));}
 @Test void customerOwnershipIsEnforced(){long b=stay();assertThrows(AccessDeniedException.class,()->cleaning.requestStayover(sid(b),request("clean-06"),uid("STAFF"),true));}
 @Test void staffCanRequestForGuestAndHrCannot(){long b=stay();assertNotNull(create(b,"clean-07","STAFF",false));assertThrows(AccessDeniedException.class,()->create(b,"clean-08","HR_ADMIN",false));}
 @Test void claimAcknowledgeAndCompleteCreatesExactlyOneRecord(){long b=stay();var r=create(b,"clean-09","STAFF",false);var c=finish(r);assertEquals(CleaningType.STAYOVER.getCode(),c.getCleaningType());assertEquals(uid("STAFF"),c.getCompletedBy());assertNotNull(c.getStartedTime());assertEquals(2,taskStatus(r.getTaskId()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));}
 @Test void blockedCreatesNoRecordThenResumeCompletesOnce(){long b=stay();var r=create(b,"clean-10","STAFF",false);as("STAFF");tasks.claim(r.getTaskId());long todo=todo(r.getTaskId());tasks.updateTodo(todo,"ACKNOWLEDGE",null);tasks.updateTodo(todo,"BLOCK","supply missing");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));tasks.updateTodo(todo,"RESUME",null);cleaning.complete(r.getTaskId(),null,false);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));}
 @Test void genericCompletionCannotBypassCleaningHandler(){long b=stay();var r=create(b,"clean-11","STAFF",false);as("STAFF");tasks.claim(r.getTaskId());tasks.updateTodo(todo(r.getTaskId()),"ACKNOWLEDGE",null);assertThrows(BusinessException.class,()->tasks.updateTodo(todo(r.getTaskId()),"COMPLETE",null));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));}
 @Test void completionRetryAndConcurrentCompleteProduceOneRecord() throws Exception {long b=stay();var r=create(b,"clean-12","STAFF",false);as("STAFF");tasks.claim(r.getTaskId());tasks.updateTodo(todo(r.getTaskId()),"ACKNOWLEDGE",null);var pool=Executors.newFixedThreadPool(2);try{var fs=List.of(pool.submit(()->completeWorker(r.getTaskId())),pool.submit(()->completeWorker(r.getTaskId())));for(var f:fs)assertNull(f.get(20,TimeUnit.SECONDS));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));}finally{pool.shutdownNow();}}
 @Test void cancelCreatesNoRecordAndNeverChangesRoom(){long b=stay();int state=roomStatus(room1);var r=create(b,"clean-13","STAFF",false);as("MANAGER");cleaning.cancel(r.getTaskId(),"guest declined");assertEquals(3,taskStatus(r.getTaskId()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,r.getTaskId()));assertEquals(state,roomStatus(room1));}
 @Test void roomChangeBindsNewRequestAndKeepsOldRecord(){long b=stay();var old=create(b,"clean-14","STAFF",false);finish(old);clock.day(1);var move=new com.johnny.hotel.dto.ChangeRoomDuringStayRequest();move.setNewRoomId(room3);move.setReason("guest move");bookings.changeRoomDuringStay(b,move,uid("MANAGER"));var next=create(b,"clean-15","STAFF",false);assertNotEquals(old.getAssignmentId(),next.getAssignmentId());assertEquals(room3,next.getRoomId());var history=cleaning.stayHistory(sid(b));assertEquals(room1,history.get(0).getRoomId());}
 @Test void turnoverCompletionCreatesRecordAndRoomRemainsMaintenance(){long b=stay();pay(b,"300");clock.day(3);checkout(b);var t=jdbc.queryForObject("SELECT id FROM room_turnover_task WHERE stay_id=(SELECT id FROM stay WHERE booking_id=?)",Long.class,b);var task=jdbc.queryForObject("SELECT task_id FROM room_turnover_task WHERE id=?",Long.class,t);as("MANAGER");turnovers.complete(t,"turnover done");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=? AND cleaning_type=1",Integer.class,task));assertEquals(3,roomStatus(room1));turnovers.complete(t,"retry");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM cleaning_record WHERE task_id=?",Integer.class,task));}
 @Test void cleaningHistoryQueriesAndResponsibilityTrace(){long b=stay();var r=create(b,"clean-16","STAFF",false);finish(r);as("STAFF");assertEquals(1,cleaning.roomHistory(room1).size());assertEquals(1,cleaning.assignmentHistory(r.getAssignmentId()).size());assertFalse(tasks.get(r.getTaskId()).getAssignments().isEmpty());assertTrue(tasks.get(r.getTaskId()).getRecords().stream().anyMatch(x->x.getRecordType()==TaskRecordType.CLEANING_COMPLETED.getCode()));}
 @Test void customerHistoryOnlyReturnsOwnedStayover(){long b=stay();var r=create(b,"clean-17","CUSTOMER",true);finish(r);as("CUSTOMER");assertEquals(1,cleaning.customerHistory(sid(b),uid("CUSTOMER")).size());assertThrows(AccessDeniedException.class,()->cleaning.customerHistory(sid(b),uid("STAFF")));}
 @Test void cleaningRecordHasNoMutationApiAndDatabaseUniqueTask(){long b=stay();var r=create(b,"clean-18","STAFF",false);var c=finish(r);assertThrows(DataAccessException.class,()->jdbc.update("INSERT INTO cleaning_record(room_id,stay_id,assignment_id,task_id,cleaning_type,completed_by,completed_time) VALUES(?,?,?,?,0,?,NOW())",room1,sid(b),r.getAssignmentId(),r.getTaskId(),uid("STAFF")));assertEquals(c.getId(),cleaning.get(c.getId()).getId());}
 @Test void securityHttpBoundaries() throws Exception {mvc.perform(get("/api/housekeeping/rooms/1/cleaning-records")).andExpect(status().isUnauthorized());mvc.perform(get("/api/housekeeping/rooms/1/cleaning-records").with(authentication(auth("HR_ADMIN")))).andExpect(status().isForbidden());mvc.perform(get("/api/housekeeping/rooms/1/cleaning-records").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden());}
 Throwable completeWorker(long task){as("STAFF");try{cleaning.complete(task,"parallel",false);return null;}catch(Throwable t){return t;}finally{SecurityContextHolder.clearContext();}}
 long active(long b){return jdbc.queryForObject("SELECT id FROM stay_room_assignment WHERE stay_id=(SELECT id FROM stay WHERE booking_id=?) AND end_time IS NULL",Long.class,b);}int roomStatus(long r){return jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,r);}int taskStatus(long t){return jdbc.queryForObject("SELECT status FROM hotel_task WHERE id=?",Integer.class,t);}int taskType(long t){return jdbc.queryForObject("SELECT task_type FROM hotel_task WHERE id=?",Integer.class,t);}
}
