package com.johnny.hotel.wallet;
import com.johnny.hotel.damage.*;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.pagination.PaginationProperties;import com.johnny.hotel.workorder.*;import org.flywaydb.core.Flyway;import org.junit.jupiter.api.*;import org.junit.jupiter.params.ParameterizedTest;import org.junit.jupiter.params.provider.ValueSource;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.security.access.AccessDeniedException;import java.math.BigDecimal;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class DamageAssessmentDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired DamageAssessmentService damage;@Autowired RoomWorkOrderService workOrders;@Autowired PaginationProperties pagination;@Autowired Flyway flyway;int sequence;
 @BeforeEach void financeActor(){long id=users.registerEmployee(employeeRequest("FINANCE")).getId();created.add(id);actors.put("FINANCE",id);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",id);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='FINANCE'",id);}
 long assignment(long booking){return jdbc.queryForObject("SELECT id FROM booking_room_assignment WHERE booking_id=? ORDER BY id DESC LIMIT 1",Long.class,booking);}
 RoomWorkOrder source(long room,String actualCost){as("STAFF");var w=workOrders.report(WorkOrderRequests.Report.builder().roomId(room).requestKey("damage-source-"+(sequence++)).damageType("FIXTURE").description("Physical room damage").severity(WorkOrderSeverity.HIGH).blocksRoomRelease(true).estimatedCost(actualCost==null?null:new BigDecimal(actualCost)).build());if(actualCost!=null)jdbc.update("UPDATE room_work_order SET actual_cost=? WHERE id=?",new BigDecimal(actualCost),w.getId());return w;}
 DamageRequests.Report report(long booking,long source,String key){return DamageRequests.Report.builder().bookingId(booking).assignmentId(assignment(booking)).sourceType(DamageSourceType.WORK_ORDER).sourceId(source).description("Guest damaged television").requestKey(key).build();}
 DamageAssessment pending(long booking){var w=source(room1,"900.00");as("STAFF");return damage.report(report(booking,w.getId(),"assessment-"+UUID.randomUUID()));}
 DamageRequests.Assess decision(DamageResponsibility responsibility,String amount){return DamageRequests.Assess.builder().responsibility(responsibility).chargeAmount(amount==null?null:new BigDecimal(amount)).reason(responsibility==DamageResponsibility.CUSTOMER?"Evidence confirms guest responsibility":"Hotel policy decision").build();}
 @Test void migrationEnumsAndSchema(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='28'",Integer.class));assertEquals(0,DamageResponsibility.PENDING.getCode());assertEquals(1,DamageResponsibility.CUSTOMER.getCode());assertEquals(2,DamageAssessmentStatus.UNPOSTED_CLOSED_FOLIO.getCode());}
 @Test void staffReportsPendingAndRetryIsIdempotent(){long b=stay();var w=source(room1,null);as("STAFF");var r=report(b,w.getId(),"stable-key");var a=damage.report(r);var same=damage.report(r);assertEquals(a.getId(),same.getId());assertEquals(0,a.getStatus());assertEquals(0,a.getResponsibility());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM damage_assessment WHERE source_type=0 AND source_id=?",Integer.class,w.getId()));}
 @Test void sourceMustMatchActualAssignmentRoom(){long b=stay();var w=source(room2,null);as("STAFF");assertThrows(BusinessException.class,()->damage.report(report(b,w.getId(),"wrong-room")));}
 @ParameterizedTest@ValueSource(strings={"CUSTOMER","HR_ADMIN","FINANCE"})void forbiddenRolesCannotReport(String role){long b=stay();var w=source(room1,null);as(role);assertThrows(AccessDeniedException.class,()->damage.report(report(b,w.getId(),"denied-"+role)));}
 @ParameterizedTest@ValueSource(strings={"FINANCE","MANAGER","OWNER","SUPER_ADMIN"})void authorizedRolesCanResolveHotelLiability(String role){long b=stay();var a=pending(b);as(role);var done=damage.assess(a.getId(),decision(DamageResponsibility.HOTEL,null));assertEquals(1,done.getStatus());assertEquals(2,done.getResponsibility());assertNull(done.getFolioItemId());}
 @Test void staffCannotAssess(){long b=stay();var a=pending(b);as("STAFF");assertThrows(AccessDeniedException.class,()->damage.assess(a.getId(),decision(DamageResponsibility.HOTEL,null)));}
 @Test void customerLiabilityRequiresReasonAndPositivePreciseCharge(){long b=stay();var a=pending(b);as("FINANCE");assertThrows(BusinessException.class,()->damage.assess(a.getId(),DamageRequests.Assess.builder().responsibility(DamageResponsibility.CUSTOMER).chargeAmount(BigDecimal.TEN).build()));assertThrows(BusinessException.class,()->damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"0.00")));assertThrows(BusinessException.class,()->damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"1.001")));}
 @Test void customerChargePostsOneTraceableFolioItemIndependentOfRepairCost(){long b=stay();var a=pending(b);as("FINANCE");var done=damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"125.50"));var row=jdbc.queryForMap("SELECT item_type,amount,source_type,source_id FROM folio_item WHERE id=?",done.getFolioItemId());assertEquals("DAMAGE_CHARGE",row.get("item_type"));assertEquals("DAMAGE_ASSESSMENT",row.get("source_type"));assertEquals(a.getId(),((Number)row.get("source_id")).longValue());assertEquals(0,new BigDecimal("125.50").compareTo((BigDecimal)row.get("amount")));assertEquals(0,new BigDecimal("900.00").compareTo(jdbc.queryForObject("SELECT actual_cost FROM room_work_order WHERE id=?",BigDecimal.class,a.getSourceId())));}
 @Test void assessRetryDoesNotDuplicateCharge(){long b=stay();var a=pending(b);as("MANAGER");var d=decision(DamageResponsibility.CUSTOMER,"25.00");damage.assess(a.getId(),d);damage.assess(a.getId(),d);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='DAMAGE_ASSESSMENT' AND source_id=?",Integer.class,a.getId()));}
 @Test void folioWriteFailureRollsBackAssessment(){long b=stay();var a=pending(b);as("FINANCE");String old=Thread.currentThread().getName();Thread.currentThread().setName("damage-fail");gate.arm("damage-fail","FolioItemMapper.insert",true);try{assertThrows(RuntimeException.class,()->damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"30.00")));}finally{gate.clear();Thread.currentThread().setName(old);}assertEquals(0,jdbc.queryForObject("SELECT status FROM damage_assessment WHERE id=?",Integer.class,a.getId()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='DAMAGE_ASSESSMENT' AND source_id=?",Integer.class,a.getId()));}
 @Test void concurrentAssessmentPostsOnce()throws Exception{long b=stay();var a=pending(b);var pool=Executors.newFixedThreadPool(2);try{var calls=List.of(worker(pool,"damage-1",()->damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"40.00"))),worker(pool,"damage-2",()->damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"40.00"))));assertNull(result(calls.get(0)));assertNull(result(calls.get(1)));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='DAMAGE_ASSESSMENT' AND source_id=?",Integer.class,a.getId()));}finally{pool.shutdownNow();}}
 @Test void closedFolioRecordsUnpostedWithoutChangingLedger(){long b=stay();pay(b,"300.00");clock.day(3);checkout(b);int before=jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=?",Integer.class,folio(b));var a=pending(b);as("FINANCE");var done=damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"80.00"));assertEquals(2,done.getStatus());assertNull(done.getFolioItemId());assertEquals(before,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=?",Integer.class,folio(b)));assertNotNull(jdbc.queryForObject("SELECT closed_time FROM folio WHERE id=?",java.sql.Timestamp.class,folio(b)));}
 @Test void pendingBlocksCheckoutAndHotelResolutionUnblocks(){long b=stay();var a=pending(b);pay(b,"300.00");clock.day(3);assertThrows(BusinessException.class,()->checkout(b));assertEquals(2,bookingState(b));as("MANAGER");damage.assess(a.getId(),decision(DamageResponsibility.HOTEL,null));checkout(b);assertEquals(3,bookingState(b));}
 @Test void chargedDamageRequiresPaymentThenCheckout(){long b=stay();var a=pending(b);as("FINANCE");damage.assess(a.getId(),decision(DamageResponsibility.CUSTOMER,"50.00"));pay(b,"350.00");clock.day(3);checkout(b);assertEquals(3,bookingState(b));}
 @Test void paginationUsesSharedBrowseSearchRules(){long b=stay();pending(b);as("FINANCE");assertEquals(1,damage.list(b,null,null,null,null,1,1).getItems().size());assertTrue(damage.list(b,null,null,null,null,1,1).isSearchMode());assertThrows(BusinessException.class,()->damage.list(null,null,null,null,null,1,pagination.getMaxPageSize()+1));}
 @Test void httpSecurityBoundaries()throws Exception{mvc.perform(get("/api/damage-assessments").with(anonymous())).andExpect(status().isUnauthorized());mvc.perform(get("/api/damage-assessments").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden());mvc.perform(get("/api/damage-assessments").with(authentication(auth("HR_ADMIN")))).andExpect(status().isForbidden());mvc.perform(get("/api/damage-assessments").with(authentication(auth("FINANCE")))).andExpect(status().isOk());}
}
