package com.johnny.hotel.wallet;

import com.johnny.hotel.organization.*;
import com.johnny.hotel.task.*;
import com.johnny.hotel.exception.BusinessException;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.*;
import java.util.concurrent.*;
import static com.johnny.hotel.organization.OrganizationRequestType.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;

class DepartmentGroupTaskDevelopmentTest extends WalletDevelopmentFixture {
 @Autowired OrganizationService org;
 @Autowired HotelTaskService tasks;
 @Autowired TodoService todoService;
 @Autowired org.flywaydb.core.Flyway flyway;
 final List<Long> departments=new ArrayList<>();
 int keys;
 OrganizationRequests.Change change(OrganizationRequestType type,Long department,Long user,Long manager){return OrganizationRequests.Change.builder().type(type).departmentId(department).targetUserId(user).proposedManagerId(manager).reason("Department task test").requestKey("dg-"+keys++).build();}
 long department(){as("SUPER_ADMIN");var r=change(CREATE_DEPARTMENT,null,null,null);r.setDepartmentName(run+"-"+keys++);long id=org.direct(r).getNewDepartmentId();departments.add(id);return id;}
 void manager(long d,String role){as("SUPER_ADMIN");org.direct(change(CHANGE_DEPARTMENT_MANAGER,d,null,role==null?null:uid(role)));}
 void join(long d,String role){as("SUPER_ADMIN");org.direct(change(MOVE_EMPLOYEE_TO_DEPARTMENT,d,uid(role),null));}
 HotelTask root(Long... ids){as("MANAGER");return tasks.createGeneral(TaskRequests.CreateGeneral.builder().title("Hotel coordinated work").requestKey("root-"+keys++).executionType(TaskExecutionType.GROUP_GROUP).departmentIds(List.of(ids)).build());}
 long branch(long root,long d){return jdbc.queryForObject("SELECT id FROM hotel_task WHERE parent_task_id=? AND department_id=? AND department_branch=1",Long.class,root,d);}
 long todo(long task){return jdbc.queryForObject("SELECT id FROM todo WHERE task_id=? AND is_active=1",Long.class,task);}
 int state(long task){return jdbc.queryForObject("SELECT status FROM hotel_task WHERE id=?",Integer.class,task);}
 int active(long task){return jdbc.queryForObject("SELECT COUNT(*) FROM task_assignment WHERE task_id=? AND is_current=1",Integer.class,task);}
 Long assignee(long task){return jdbc.queryForObject("SELECT assignee_user_id FROM task_assignment WHERE task_id=? AND is_current=1",Long.class,task);}
 TaskRequests.Assign assign(String role){return TaskRequests.Assign.builder().assigneeUserIds(List.of(uid(role))).build();}
 HotelTask child(long branch,TaskExecutionType type,String... roles){return tasks.subtask(branch,TaskRequests.CreateGeneral.builder().title("Department child").requestKey("child-"+keys++).executionType(type).assigneeUserIds(roles.length==0?null:Arrays.stream(roles).map(this::uid).toList()).build());}
 @AfterEach void cleanupDepartmentTest(){
  gate.clear();for(long u:created)jdbc.update("DELETE FROM organization_change_history WHERE operator_user_id=? OR request_id IN (SELECT id FROM organization_change_request WHERE requested_by=?)",u,u);
  for(long u:created)jdbc.update("DELETE FROM organization_change_request WHERE requested_by=?",u);
  var ids=new ArrayList<Long>();for(long u:created)ids.addAll(jdbc.queryForList("SELECT id FROM hotel_task WHERE created_by=?",Long.class,u));ids.sort(Comparator.reverseOrder());
  for(long id:ids){jdbc.update("DELETE FROM task_record WHERE task_id=?",id);jdbc.update("DELETE FROM todo WHERE task_id=?",id);jdbc.update("DELETE FROM task_assignment WHERE task_id=?",id);jdbc.update("DELETE FROM hotel_task WHERE id=?",id);}
  for(long d:departments)jdbc.update("UPDATE department SET manager_user_id=NULL WHERE id=?",d);
  for(long u:created){jdbc.update("UPDATE sys_user SET department_id=NULL WHERE id=?",u);jdbc.update("DELETE FROM organization_change_history WHERE operator_user_id=?",u);}
  for(long d:departments)jdbc.update("DELETE FROM department WHERE id=?",d);
 }
 @Test void migrationAndSnapshotUnique(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='30'",Integer.class));long a=department(),b=department();var r=root(a,b);department();assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE parent_task_id=?",Integer.class,r.getId()));long branch=branch(r.getId(),a);assertThrows(org.springframework.dao.DuplicateKeyException.class,()->jdbc.update("INSERT INTO hotel_task(task_type,status,assignment_mode,execution_type,title,created_by,parent_task_id,department_id,department_branch) VALUES(1,0,1,3,'duplicate',?,?,?,1)",uid("MANAGER"),r.getId(),a));assertEquals(0,active(branch));}
 @Test void managerRoutesPendingTodo(){long d=department();manager(d,"STAFF");long b=branch(root(d).getId(),d);assertEquals(uid("STAFF"),assignee(b));assertEquals(0,state(b));assertEquals(0,jdbc.queryForObject("SELECT status FROM todo WHERE id=?",Integer.class,todo(b)));as("STAFF");todoService.acknowledge(todo(b),null);assertEquals(1,state(b));}
 @Test void vacancyHasNoTodoAndCannotBeClaimed(){long d=department();join(d,"STAFF");long b=branch(root(d).getId(),d);assertEquals(0,active(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM todo WHERE task_id=?",Integer.class,b));as("STAFF");assertThrows(BusinessException.class,()->tasks.claim(b));assertThrows(AccessDeniedException.class,()->tasks.assign(b,assign("STAFF")));}
 @Test void managerAppointmentRoutesVacancy(){long d=department();long b=branch(root(d).getId(),d);manager(d,"STAFF");assertEquals(uid("STAFF"),assignee(b));assertEquals(0,jdbc.queryForObject("SELECT status FROM todo WHERE id=?",Integer.class,todo(b)));}
 @Test void handoffRetiresOldTodoAndPreservesChildren(){long d=department();manager(d,"STAFF");join(d,"OWNER");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.PERSONAL,"OWNER");long old=todo(b);manager(d,"OWNER");assertEquals(uid("OWNER"),assignee(b));assertEquals(0,jdbc.queryForObject("SELECT is_active FROM todo WHERE id=?",Integer.class,old));assertEquals(1,active(c.getId()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE parent_task_id=?",Integer.class,b));assertTrue(jdbc.queryForObject("SELECT COUNT(*) FROM task_record WHERE task_id=? AND record_type=6",Integer.class,b)>=2);}
 @Test void removalReturnsUnassignedWithoutRemovingChildren(){long d=department();manager(d,"STAFF");join(d,"OWNER");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.PERSONAL,"OWNER");manager(d,null);assertEquals(0,active(b));assertEquals(0,state(b));assertEquals(1,active(c.getId()));}
 @Test void overrideSurvivesManagerChangeAndDoesNotGrantManagerRole(){long d=department();join(d,"STAFF");long b=branch(root(d).getId(),d);as("MANAGER");tasks.assign(b,assign("STAFF"));manager(d,"OWNER");assertEquals(uid("STAFF"),assignee(b));assertEquals(1,jdbc.queryForObject("SELECT routing_source FROM hotel_task WHERE id=?",Integer.class,b));as("STAFF");assertThrows(AccessDeniedException.class,()->child(b,TaskExecutionType.PERSONAL,"STAFF"));}
 @Test void crossDepartmentAssignmentAndDecompositionRejected(){long a=department(),b=department();manager(a,"STAFF");join(b,"OWNER");long branch=branch(root(a).getId(),a);as("STAFF");assertThrows(BusinessException.class,()->child(branch,TaskExecutionType.PERSONAL,"OWNER"));as("OWNER");assertThrows(BusinessException.class,()->tasks.reassign(branch,assign("OWNER")));}
 @Test void ordinaryStaffCannotDecomposeOtherDepartment(){long a=department(),b=department();manager(a,"STAFF");long branch=branch(root(b).getId(),b);as("STAFF");assertThrows(AccessDeniedException.class,()->child(branch,TaskExecutionType.PERSONAL,"STAFF"));}
 @Test void groupIndividualSnapshotsCurrentMembers(){long d=department();manager(d,"STAFF");join(d,"OWNER");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.GROUP_INDIVIDUAL);assertEquals(2,active(c.getId()));join(d,"MANAGER");assertEquals(2,active(c.getId()));as("SUPER_ADMIN");org.direct(change(REMOVE_EMPLOYEE_FROM_DEPARTMENT,d,uid("OWNER"),null));assertEquals(2,active(c.getId()));}
 @Test void childrenDoNotAutoConfirmBranchAndRootWaitsForAll(){long a=department(),b=department();manager(a,"STAFF");manager(b,"OWNER");var root=root(a,b);long ba=branch(root.getId(),a),bb=branch(root.getId(),b);as("STAFF");todoService.acknowledge(todo(ba),null);var c=child(ba,TaskExecutionType.PERSONAL,"STAFF");assertThrows(BusinessException.class,()->tasks.complete(ba,null));todoService.acknowledge(todo(c.getId()),null);todoService.complete(todo(c.getId()),null);assertEquals(1,state(ba));tasks.complete(ba,null);assertNotEquals(2,state(root.getId()));as("OWNER");todoService.acknowledge(todo(bb),null);tasks.complete(bb,null);assertEquals(2,state(root.getId()));}
 @Test void managerCanAssignScopedChildThroughExistingWorkAssign(){long d=department();manager(d,"STAFF");join(d,"OWNER");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.PERSONAL,"OWNER");tasks.reassign(c.getId(),assign("STAFF"));assertEquals(uid("STAFF"),assignee(c.getId()));}
 @Test void disableBlockedByOpenVacantBranch(){long d=department();long b=branch(root(d).getId(),d);as("SUPER_ADMIN");assertThrows(BusinessException.class,()->org.direct(change(DISABLE_DEPARTMENT,d,null,null)));tasks.cancel(b,"No longer required");org.direct(change(DISABLE_DEPARTMENT,d,null,null));}
 @Test void createRetryPreservesBranches(){long d=department();as("MANAGER");var req=TaskRequests.CreateGeneral.builder().title("retry").requestKey("same").executionType(TaskExecutionType.GROUP_GROUP).departmentIds(List.of(d)).build();var r=tasks.createGeneral(req);assertEquals(r.getId(),tasks.createGeneral(req).getId());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE parent_task_id=?",Integer.class,r.getId()));}
 @Test void handoffFailureRollsBackOrganizationAndTasks(){long d=department();manager(d,"STAFF");long b=branch(root(d).getId(),d);gate.arm(Thread.currentThread().getName(),"TodoMapper.insert",true);assertThrows(RuntimeException.class,()->manager(d,"OWNER"));gate.clear();assertEquals(uid("STAFF"),jdbc.queryForObject("SELECT manager_user_id FROM department WHERE id=?",Long.class,d));assertEquals(uid("STAFF"),assignee(b));assertEquals(1,active(b));}
 @Test void concurrentManagerChangesLeaveOneCurrentResponsibility()throws Exception{long d=department();long b=branch(root(d).getId(),d);var pool=Executors.newFixedThreadPool(2);try{var calls=new ArrayList<Future<?>>();for(String role:List.of("STAFF","OWNER"))calls.add(pool.submit(()->{as("SUPER_ADMIN");try{org.direct(OrganizationRequests.Change.builder().type(CHANGE_DEPARTMENT_MANAGER).departmentId(d).proposedManagerId(uid(role)).reason("concurrent manager change").build());}finally{SecurityContextHolder.clearContext();}}));for(var f:calls)f.get(20,TimeUnit.SECONDS);assertEquals(1,active(b));assertEquals(jdbc.queryForObject("SELECT manager_user_id FROM department WHERE id=?",Long.class,d),assignee(b));}finally{pool.shutdownNow();}}
 @Test void httpBoundariesAndDepartmentManagerWorkAssign()throws Exception{mvc.perform(get("/api/tasks").with(anonymous())).andExpect(status().isUnauthorized());for(String role:List.of("HR_ADMIN","CUSTOMER"))mvc.perform(get("/api/tasks").with(authentication(auth(role)))).andExpect(status().isForbidden());long d=department();manager(d,"STAFF");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.PERSONAL,"STAFF");mvc.perform(post("/api/admin/tasks/"+c.getId()+"/reassign").with(authentication(auth("STAFF"))).contentType("application/json").content("{\"assigneeUserIds\":["+uid("STAFF")+"]}")).andExpect(status().isOk());}
 @Test void staffCannotCreateDepartmentRoot(){long d=department();as("STAFF");assertThrows(AccessDeniedException.class,()->tasks.createGeneral(TaskRequests.CreateGeneral.builder().title("denied").requestKey("denied").executionType(TaskExecutionType.GROUP_GROUP).departmentIds(List.of(d)).build()));}
 @Test void hrApprovalAtomicallyRoutesWithoutGrantingOperationalAccess(){long d=department();manager(d,"STAFF");long b=branch(root(d).getId(),d);as("OWNER");var r=org.create(change(CHANGE_DEPARTMENT_MANAGER,d,null,uid("OWNER")));as("HR_ADMIN");org.approve(r.getId());assertEquals(uid("OWNER"),assignee(b));assertThrows(AccessDeniedException.class,()->tasks.assign(b,assign("HR_ADMIN")));}
 @Test void sharedChildKeepsDepartmentScopeAndUnifiedCompletion(){long d=department();manager(d,"STAFF");join(d,"OWNER");long b=branch(root(d).getId(),d);as("STAFF");var c=child(b,TaskExecutionType.SHARED,"STAFF","OWNER");assertEquals(2,active(c.getId()));long mine=jdbc.queryForObject("SELECT id FROM todo WHERE task_id=? AND user_id=? AND is_active=1",Long.class,c.getId(),uid("STAFF"));todoService.acknowledge(mine,null);todoService.complete(mine,"Shared outcome complete");assertEquals(2,state(c.getId()));assertNotEquals(2,state(b));}
 @Test void completedBranchesAreNotReassigned(){long d=department();manager(d,"STAFF");long b=branch(root(d).getId(),d);as("STAFF");todoService.acknowledge(todo(b),null);tasks.complete(b,null);manager(d,"OWNER");assertEquals(uid("STAFF"),assignee(b));assertEquals(2,state(b));}
 @Test void inactiveDepartmentManagerCreatesNoFalseTodo(){long d=department();manager(d,"STAFF");jdbc.update("UPDATE sys_user SET status=0 WHERE id=?",uid("STAFF"));long b=branch(root(d).getId(),d);assertEquals(0,active(b));assertEquals(0,state(b));}
 @Test void concurrentRootCreationIsIdempotent()throws Exception{long d=department();var req=TaskRequests.CreateGeneral.builder().title("Concurrent departments").requestKey("concurrent-root").executionType(TaskExecutionType.GROUP_GROUP).departmentIds(List.of(d)).build();var pool=Executors.newFixedThreadPool(2);try{Callable<Long> action=()->{as("MANAGER");try{return tasks.createGeneral(req).getId();}finally{SecurityContextHolder.clearContext();}};var a=pool.submit(action);var b=pool.submit(action);long id=a.get(20,TimeUnit.SECONDS);assertEquals(id,b.get(20,TimeUnit.SECONDS));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE parent_task_id=?",Integer.class,id));}finally{pool.shutdownNow();}}
 @Test void simultaneousBranchConfirmationsCompleteRootExactlyOnce()throws Exception{long a=department(),b=department();manager(a,"STAFF");manager(b,"OWNER");var r=root(a,b);long ba=branch(r.getId(),a),bb=branch(r.getId(),b);as("STAFF");todoService.acknowledge(todo(ba),null);as("OWNER");todoService.acknowledge(todo(bb),null);var pool=Executors.newFixedThreadPool(2);try{var first=pool.submit(()->{as("STAFF");try{tasks.complete(ba,null);}finally{SecurityContextHolder.clearContext();}});var second=pool.submit(()->{as("OWNER");try{tasks.complete(bb,null);}finally{SecurityContextHolder.clearContext();}});first.get(20,TimeUnit.SECONDS);second.get(20,TimeUnit.SECONDS);assertEquals(2,state(r.getId()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM task_record WHERE task_id=? AND record_type=4",Integer.class,r.getId()));}finally{pool.shutdownNow();}}
 @Test void branchCreationFailureRollsBackWholeRoot(){long d=department();manager(d,"STAFF");gate.arm(Thread.currentThread().getName(),"TodoMapper.insert",true);assertThrows(RuntimeException.class,()->root(d));gate.clear();assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE created_by=?",Integer.class,uid("MANAGER")));}
 @Test void fullLengthDepartmentAndOverrideNoteRemainValid(){as("SUPER_ADMIN");var request=change(CREATE_DEPARTMENT,null,null,null);String name=run+"D".repeat(120-run.length());request.setDepartmentName(name);long d=org.direct(request).getNewDepartmentId();departments.add(d);manager(d,"STAFF");long b=branch(root(d).getId(),d);assertEquals(name,tasks.get(b).getTask().getTitle());as("MANAGER");tasks.reassign(b,TaskRequests.Assign.builder().assigneeUserIds(List.of(uid("STAFF"))).note("N".repeat(500)).build());as("STAFF");var c=child(b,TaskExecutionType.PERSONAL,"STAFF");assertEquals(state(c.getId()),c.getStatus());assertEquals(1,jdbc.queryForObject("SELECT routing_source FROM hotel_task WHERE id=?",Integer.class,b));}
}
