package com.johnny.hotel.wallet;
import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.pricing.*;import com.johnny.hotel.service.PricingService;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.security.access.AccessDeniedException;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;
class DynamicPricingDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired DynamicPricingService policies;@Autowired ManualRateService overrides;@Autowired PricingService pricing;@Autowired PricingMapper pricingDb;@Autowired com.johnny.hotel.walkin.WalkInBookingService walkIns;
 @BeforeEach void pricingOff(){as("OWNER");policies.disable(uid("OWNER"));}
 PricingRequests.PolicySave policy(String name,String adjustment){return PricingRequests.PolicySave.builder().name(name).minimumMultiplier(new BigDecimal("0.80")).maximumMultiplier(new BigDecimal("2.00")).occupancyBands(List.of(PricingRequests.Occupancy.builder().label("all").lowerInclusive(0).upperExclusive(101).build())).bookingWindowBands(List.of(PricingRequests.Window.builder().label("all days").minDays(0).maxDays(null).build())).cells(List.of(PricingRequests.Cell.builder().occupancyIndex(0).windowIndex(0).adjustmentPercent(new BigDecimal(adjustment)).build())).build();}
 PricingRequests.Override override(Long type,LocalDate date,String mode,String value){return PricingRequests.Override.builder().roomTypeId(type).startDate(date).endDate(date).overrideType(mode).value(new BigDecimal(value)).reason("front desk revenue decision").build();}
 @Test void migrationSeedsDisabledCompleteDefaultMatrix(){assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM flyway_schema_history WHERE version='37' AND success=1",Integer.class));long id=jdbc.queryForObject("SELECT id FROM dynamic_pricing_policy WHERE version_no=1",Long.class);var v=policies.get(id,uid("OWNER"));assertEquals(5,v.getOccupancyBands().size());assertEquals(4,v.getBookingWindowBands().size());assertEquals(20,v.getCells().size());assertTrue(v.isValid());assertNull(policies.active(uid("OWNER")));}
 @Test void configurableBandsAndMatrixValidation(){var good=policies.create(policy("configurable "+run,"20"),uid("OWNER"));assertTrue(good.isValid());var gap=policy("gap "+run,"10");gap.setOccupancyBands(List.of(PricingRequests.Occupancy.builder().label("bad").lowerInclusive(1).upperExclusive(101).build()));var draft=policies.create(gap,uid("OWNER"));assertFalse(draft.isValid());assertThrows(BusinessException.class,()->policies.activate(draft.getPolicy().getId(),uid("OWNER")));var missing=policy("missing "+run,"10");missing.setCells(List.of());var incomplete=policies.create(missing,uid("OWNER"));assertThrows(BusinessException.class,()->policies.activate(incomplete.getPolicy().getId(),uid("OWNER")));}
 @Test void overlappingAndGappedWindowOrOccupancyBandsCannotActivate(){var overlap=policy("overlap "+run,"1");overlap.setOccupancyBands(List.of(PricingRequests.Occupancy.builder().label("a").lowerInclusive(0).upperExclusive(60).build(),PricingRequests.Occupancy.builder().label("b").lowerInclusive(50).upperExclusive(101).build()));overlap.setCells(List.of(PricingRequests.Cell.builder().occupancyIndex(0).windowIndex(0).adjustmentPercent(BigDecimal.ZERO).build(),PricingRequests.Cell.builder().occupancyIndex(1).windowIndex(0).adjustmentPercent(BigDecimal.ZERO).build()));var a=policies.create(overlap,uid("OWNER"));assertFalse(a.isValid());assertThrows(BusinessException.class,()->policies.activate(a.getPolicy().getId(),uid("OWNER")));var windows=policy("window-gap "+run,"1");windows.setBookingWindowBands(List.of(PricingRequests.Window.builder().label("first").minDays(0).maxDays(2).build(),PricingRequests.Window.builder().label("gap").minDays(4).maxDays(null).build()));windows.setCells(List.of(PricingRequests.Cell.builder().occupancyIndex(0).windowIndex(0).adjustmentPercent(BigDecimal.ZERO).build(),PricingRequests.Cell.builder().occupancyIndex(0).windowIndex(1).adjustmentPercent(BigDecimal.ZERO).build()));var w=policies.create(windows,uid("OWNER"));assertFalse(w.isValid());assertThrows(BusinessException.class,()->policies.activate(w.getPolicy().getId(),uid("OWNER")));}
 @Test void dynamicCalculationUsesLivePropertyInventoryAndFloorCeiling(){var p=policy("active "+run,"250");p.setMaximumMultiplier(new BigDecimal("1.50"));policies.activate(policies.create(p,uid("OWNER")).getPolicy().getId(),uid("OWNER"));var d=pricing.explain(type1,arrival,arrival.plusDays(1)).get(0);assertEquals(pricingDb.sellable(),d.getSellableRoomCount());assertEquals(pricingDb.committed(arrival),d.getCommittedRoomCount());assertEquals(0,new BigDecimal("150.00").compareTo(d.getFinalRate()));assertEquals("DYNAMIC",d.getRateSource());assertEquals(d.getFinalRate(),pricing.quoteRoomType(type1,arrival,arrival.plusDays(1)).getNightlyRates().get(0).getPrice());}
 @Test void floorAndNightlyExplanationAreAppliedPerDate(){var p=policy("floor "+run,"-90");policies.activate(policies.create(p,uid("OWNER")).getPolicy().getId(),uid("OWNER"));var ds=pricing.explain(type1,arrival,arrival.plusDays(3));assertEquals(3,ds.size());assertTrue(ds.stream().allMatch(x->new BigDecimal("80.00").compareTo(x.getFinalRate())==0));assertEquals(List.of(0,1,2),ds.stream().map(PricingDecision::getLeadDays).toList());overrides.save(override(type1,arrival,"FIXED_RATE","50"),uid("STAFF"));assertEquals(0,new BigDecimal("50.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));overrides.cancel(type1,arrival,"event ended",uid("STAFF"));assertEquals(0,new BigDecimal("80.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));}
 @Test void disabledUsesBaseAndManualModesHaveCorrectPriority(){assertEquals(0,new BigDecimal("100.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));var p=policies.create(policy("manual "+run,"30"),uid("OWNER"));policies.activate(p.getPolicy().getId(),uid("OWNER"));overrides.save(override(type1,arrival,"FIXED_RATE","560"),uid("STAFF"));var fixed=pricing.explain(type1,arrival,arrival.plusDays(1)).get(0);assertEquals("MANUAL_FIXED",fixed.getRateSource());assertEquals(0,new BigDecimal("560.00").compareTo(fixed.getFinalRate()));assertEquals(0,new BigDecimal("195.00").compareTo(pricing.explain(type2,arrival,arrival.plusDays(1)).get(0).getFinalRate()));overrides.save(override(type1,arrival,"PERCENT_OF_RECOMMENDED","-10"),uid("STAFF"));assertEquals(0,new BigDecimal("117.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));assertTrue(jdbc.queryForObject("SELECT COUNT(*) FROM sys_audit_log WHERE operator_id=? AND action='MANUAL_RATE_OVERRIDE'",Integer.class,uid("STAFF"))>0);}
 @Test void bookingSnapshotIsImmutableAcrossPolicyAndOverrideChanges(){var p=policies.create(policy("snapshot "+run,"20"),uid("OWNER"));policies.activate(p.getPolicy().getId(),uid("OWNER"));long b=createBooking("CUSTOMER");var before=jdbc.queryForList("SELECT rate_amount,rate_source,dynamic_policy_id,manual_override_id FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date",b);overrides.save(override(type1,arrival,"FIXED_RATE","777"),uid("STAFF"));policies.disable(uid("OWNER"));var after=jdbc.queryForList("SELECT rate_amount,rate_source,dynamic_policy_id,manual_override_id FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date",b);assertEquals(before,after);assertEquals(0,new BigDecimal("777.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));}
 @Test void portalAndWalkInLockQuotesFromTheSameEngine(){var p=policies.create(policy("shared-engine "+run,"20"),uid("OWNER"));policies.activate(p.getPolicy().getId(),uid("OWNER"));long portal=createBooking("CUSTOMER");var profile=com.johnny.hotel.guest.GuestRequests.Profile.builder().firstName("Walk").lastName("In").nationality("CA").documentType("PASSPORT").documentNumber(run+"shared").build();var request=com.johnny.hotel.walkin.WalkInRequests.Create.builder().requestKey(run+"shared01").bookerProfile(profile).roomTypeId(type1).reservedRoomId(room1).guestCount(1).checkInDate(arrival).checkOutDate(arrival.plusDays(3)).build();var walk=walkIns.create(request,uid("STAFF"));bookingIds.add(walk.bookingId());BigDecimal portalRate=jdbc.queryForObject("SELECT rate_amount FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date LIMIT 1",BigDecimal.class,portal);BigDecimal walkRate=jdbc.queryForObject("SELECT rate_amount FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date LIMIT 1",BigDecimal.class,walk.bookingId());assertEquals(0,portalRate.compareTo(walkRate));assertEquals(0,new BigDecimal("120.00").compareTo(walkRate));}
 @Test void permissionsFollowRevenueBoundary(){long finance=users.registerEmployee(employeeRequest("FINANCE")).getId();created.add(finance);actors.put("FINANCE",finance);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",finance);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='FINANCE'",finance);assertThrows(AccessDeniedException.class,()->policies.create(policy("staff", "1"),uid("STAFF")));assertThrows(AccessDeniedException.class,()->policies.create(policy("manager", "1"),uid("MANAGER")));assertDoesNotThrow(()->policies.history(1,20,uid("FINANCE")));assertThrows(AccessDeniedException.class,()->policies.history(1,20,uid("CUSTOMER")));assertThrows(AccessDeniedException.class,()->overrides.save(override(type1,arrival,"FIXED_RATE","90"),uid("FINANCE")));assertDoesNotThrow(()->overrides.save(override(type1,arrival,"FIXED_RATE","90"),uid("STAFF")));}
 @Test void concurrentActivationAndOverrideKeepSingleFacts()throws Exception{var a=policies.create(policy("A "+run,"10"),uid("OWNER"));var b=policies.create(policy("B "+run,"20"),uid("OWNER"));var pool=Executors.newFixedThreadPool(2);try{var f1=pool.submit(()->policies.activate(a.getPolicy().getId(),uid("OWNER")));var f2=pool.submit(()->policies.activate(b.getPolicy().getId(),uid("SUPER_ADMIN")));for(var f:List.of(f1,f2))try{f.get(20,TimeUnit.SECONDS);}catch(ExecutionException ignored){}assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM dynamic_pricing_policy WHERE active_slot=1",Integer.class));var o1=pool.submit(()->overrides.save(override(type1,arrival,"FIXED_RATE","111"),uid("STAFF")));var o2=pool.submit(()->overrides.save(override(type1,arrival,"FIXED_RATE","112"),uid("MANAGER")));o1.get(20,TimeUnit.SECONDS);o2.get(20,TimeUnit.SECONDS);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM manual_rate_override WHERE room_type_id=? AND stay_date=? AND active_slot=1",Integer.class,type1,arrival));}finally{pool.shutdownNow();}}
 @Test void calculatedFractionalCentsAreRoundedBeforeNightlySnapshot(){jdbc.update("UPDATE room_type SET base_price=199.99 WHERE id=?",type1);var p=policies.create(policy("fractional "+run,"15"),uid("OWNER"));policies.activate(p.getPolicy().getId(),uid("OWNER"));
  assertEquals(0,new BigDecimal("229.99").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));
  long booking=createBooking("CUSTOMER");assertEquals(0,new BigDecimal("229.99").compareTo(jdbc.queryForObject("SELECT rate_amount FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date LIMIT 1",BigDecimal.class,booking)));
  overrides.save(override(type1,arrival,"PERCENT_OF_RECOMMENDED","-10"),uid("STAFF"));assertEquals(0,new BigDecimal("206.99").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));
  overrides.save(override(type1,arrival,"FIXED_RATE","500.00"),uid("STAFF"));assertEquals(0,new BigDecimal("500.00").compareTo(pricing.explain(type1,arrival,arrival.plusDays(1)).get(0).getFinalRate()));
  assertEquals(0,new BigDecimal("229.99").compareTo(jdbc.queryForObject("SELECT rate_amount FROM booking_nightly_rate WHERE booking_id=? ORDER BY stay_date LIMIT 1",BigDecimal.class,booking)));}
}
