package com.johnny.hotel.wallet;
import com.johnny.hotel.invoice.*;import com.johnny.hotel.exception.BusinessException;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.security.access.AccessDeniedException;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class FinanceInvoiceDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired InvoiceService invoices;@Autowired FinanceReadService financeReads;@Autowired RefundAccess refundAccess;@Autowired com.johnny.hotel.service.support.BillingAccess billingAccess;@Autowired org.flywaydb.core.Flyway flyway;
 @BeforeEach void finance(){long id=users.registerEmployee(employeeRequest("FINANCE")).getId();created.add(id);actors.put("FINANCE",id);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",id);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='FINANCE'",id);}
 InvoiceRequests.Issue request(String key){return InvoiceRequests.Issue.builder().requestKey(key).recipientName("Guest Billing Recipient").recipientEmail("billing@example.test").billingAddress("Test address").taxIdentifier("TAX-TEST").build();}
 long closed(){long b=stay();pay(b,"300");clock.day(3);checkout(b);return b;}
 @Test void migrationRoleAndSchema(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='24'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='25'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM sys_role WHERE role_code='FINANCE'",Integer.class));assertEquals(0,InvoiceStatus.ISSUED.getCode());assertEquals(1,InvoiceStatus.VOIDED.getCode());}
 @Test void issueRequiresClosedSettledFolio(){long b=stay();as("FINANCE");assertThrows(BusinessException.class,()->invoices.issue(folio(b),request("inv-open")));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM invoice WHERE folio_id=?",Integer.class,folio(b)));}
 @Test void invoiceIsAtomicFolioItemSnapshot(){long b=closed();long f=folio(b);as("FINANCE");var v=invoices.issue(f,request("inv-snapshot"));assertEquals(0,v.getInvoice().getStatus());assertEquals(v.getInvoice().getTotalAmount(),v.getInvoice().getSubtotal());assertFalse(v.getLines().isEmpty());assertEquals(jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=?",Integer.class,f),v.getLines().size());assertTrue(v.getInvoice().getInvoiceNumber().matches("INV-[0-9]{8}-[0-9]{12}"));}
 @Test void issueRetryReturnsSameInvoice(){long b=closed();as("FINANCE");var a=invoices.issue(folio(b),request("inv-retry"));var c=invoices.issue(folio(b),request("inv-retry"));assertEquals(a.getInvoice().getId(),c.getInvoice().getId());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM invoice WHERE request_key='inv-retry'",Integer.class));}
 @Test void voidIsIdempotentAndReissuePreservesHistory(){long b=closed();as("FINANCE");var a=invoices.issue(folio(b),request("inv-void"));var r=InvoiceRequests.Void.builder().reason("Incorrect recipient details").build();assertEquals(1,invoices.voidInvoice(a.getInvoice().getId(),r).getInvoice().getStatus());assertEquals(1,invoices.voidInvoice(a.getInvoice().getId(),r).getInvoice().getStatus());var second=invoices.issue(folio(b),request("inv-reissue"));assertNotEquals(a.getInvoice().getId(),second.getInvoice().getId());assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM invoice WHERE folio_id=?",Integer.class,folio(b)));}
 @Test void customerOwnershipAndStaffRead(){long b=closed();as("FINANCE");var i=invoices.issue(folio(b),request("inv-owner"));as("CUSTOMER");assertEquals(i.getInvoice().getId(),invoices.get(i.getInvoice().getId()).getInvoice().getId());as("OTHER_CUSTOMER");assertThrows(BusinessException.class,()->invoices.get(i.getInvoice().getId()));as("STAFF");assertNotNull(invoices.get(i.getInvoice().getId()));}
 @Test void staffHrCustomerCannotIssueOrVoid(){long b=closed();for(String role:List.of("STAFF","HR_ADMIN","CUSTOMER")){as(role);assertThrows(AccessDeniedException.class,()->invoices.issue(folio(b),request("denied-"+role)));}}
 @Test void financeCanReadFolioWalletAndOperationalViews(){long b=closed();as("FINANCE");assertEquals(folio(b),queries.byBookingForOperations(b).id());assertNotNull(service.byUser(uid("CUSTOMER")));assertFalse(financeReads.read("bookings",1,20).isEmpty());assertFalse(financeReads.read("rooms",1,20).isEmpty());}
 @Test void financeCannotWriteOperationalHttp()throws Exception{mvc.perform(post("/api/admin/bookings/1/check-in").with(authentication(auth("FINANCE")))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/rooms/1/available").with(authentication(auth("FINANCE")))).andExpect(status().isForbidden());mvc.perform(post("/api/housekeeping/inspections/1/decision").with(authentication(auth("FINANCE"))).contentType("application/json").content("{\"passed\":true}")).andExpect(status().isForbidden());mvc.perform(post("/api/work-orders").with(authentication(auth("FINANCE"))).contentType("application/json").content("{\"roomId\":1,\"requestKey\":\"finance-denied\",\"damageType\":\"TEST\",\"description\":\"Denied operation\",\"severity\":\"LOW\",\"blocksRoomRelease\":false}")).andExpect(status().isForbidden());}
 @Test void hrStillCannotReadBilling(){long b=closed();as("HR_ADMIN");assertThrows(AccessDeniedException.class,()->queries.byBookingForOperations(b));}
 @Test void financeIsAuthorizedByBillingAndRefundBoundariesButHrIsNot(){as("FINANCE");assertEquals(uid("FINANCE"),billingAccess.currentOperational());assertDoesNotThrow(()->refundAccess.operational(uid("FINANCE"),true));as("HR_ADMIN");assertThrows(AccessDeniedException.class,billingAccess::currentOperational);assertThrows(AccessDeniedException.class,()->refundAccess.operational(uid("HR_ADMIN"),true));}
 @Test void concurrentSameRequestCreatesOneInvoice()throws Exception{long b=closed();long f=folio(b);var pool=Executors.newFixedThreadPool(2);try{var fs=List.of(pool.submit(()->issueWorker(f,"inv-parallel")),pool.submit(()->issueWorker(f,"inv-parallel")));Long first=fs.get(0).get(20,TimeUnit.SECONDS),second=fs.get(1).get(20,TimeUnit.SECONDS);assertEquals(first,second);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM invoice WHERE request_key='inv-parallel'",Integer.class));}finally{pool.shutdownNow();}}
 Long issueWorker(long f,String key){try{as("FINANCE");return invoices.issue(f,request(key)).getInvoice().getId();}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}}
 @Test void numbersAreUniqueAcrossInvoices(){long b=closed();as("MANAGER");var x=invoices.issue(folio(b),request("inv-num-a"));invoices.voidInvoice(x.getInvoice().getId(),InvoiceRequests.Void.builder().reason("Reissue number test").build());var y=invoices.issue(folio(b),request("inv-num-b"));assertNotEquals(x.getInvoice().getInvoiceNumber(),y.getInvoice().getInvoiceNumber());}
}
