package com.johnny.hotel.wallet;

import com.johnny.hotel.dto.ApproveBookingRequest;
import com.johnny.hotel.exception.BusinessException;
import com.johnny.hotel.guest.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.AccessDeniedException;
import java.util.*;import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class GuestManagementDevelopmentTest extends FinancialDevelopmentFixture {
 @Autowired GuestService guestService;
 GuestRequests.Profile profile(String suffix){return GuestRequests.Profile.builder().firstName("Alex").lastName("Guest"+suffix).phone("555"+suffix).email("guest"+suffix+"@example.test").dateOfBirth(java.time.LocalDate.of(1990,1,1)).nationality("CA").documentType("PASSPORT").documentNumber("P"+run+suffix).build();}
 GuestRequests.Add add(GuestRole role,String suffix){return GuestRequests.Add.builder().role(role).profile(profile(suffix)).build();}
 long approved(){long b=createBooking("CUSTOMER");var a=new ApproveBookingRequest();a.setAssignedRoomId(room1);bookings.approveBooking(b,a,uid("MANAGER"));return b;}

 @Test void migrationAndSchema(){assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM flyway_schema_history WHERE version='20' AND success=1",Integer.class));assertEquals(3,jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('guest_profile','booking_guest','guest_registration')",Integer.class));}
 @Test void profileCanBeDetachedFromUser(){var p=guestService.create(profile("01"),uid("STAFF"));assertNull(p.linkedUserId());}
 @Test void customerCreatesAndReadsOwnProfile(){var p=guestService.saveMe(uid("CUSTOMER"),profile("02"));assertEquals(uid("CUSTOMER"),p.linkedUserId());assertEquals(p.id(),guestService.me(uid("CUSTOMER")).id());}
 @Test void oneUserHasOnlyOneProfileAndUpdateIsStable(){var a=guestService.saveMe(uid("CUSTOMER"),profile("03"));var b=guestService.saveMe(uid("CUSTOMER"),profile("04"));assertEquals(a.id(),b.id());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM guest_profile WHERE linked_user_id=?",Integer.class,uid("CUSTOMER")));}
 @Test void customerCannotUseAnotherCustomersIdentity(){assertThrows(AccessDeniedException.class,()->guestService.me(uid("STAFF")));long b=approved();var foreign=guestService.create(profile("05"),uid("STAFF"));assertThrows(BusinessException.class,()->guestService.preRegister(b,GuestRequests.Add.builder().guestId(foreign.id()).role(GuestRole.PRIMARY).build(),uid("CUSTOMER")));}
 @Test void bookingOwnerNeedNotBePrimaryGuest(){long b=approved();var e=guestService.addToBooking(b,add(GuestRole.PRIMARY,"06"),uid("STAFF"));assertNull(e.guest().linkedUserId());assertNotEquals(uid("CUSTOMER"),e.guest().linkedUserId());}
 @Test void onlyOnePrimary(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"07"),uid("STAFF"));assertThrows(BusinessException.class,()->guestService.addToBooking(b,add(GuestRole.PRIMARY,"08"),uid("STAFF")));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM booking_guest WHERE booking_id=? AND guest_role=0",Integer.class,b));}
 @Test void accompanyingGuestsAndCapacity(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"09"),uid("STAFF"));guestService.addToBooking(b,add(GuestRole.ACCOMPANYING,"10"),uid("STAFF"));assertEquals(2,guestService.bookingGuests(b,uid("STAFF")).size());assertThrows(BusinessException.class,()->guestService.addToBooking(b,add(GuestRole.ACCOMPANYING,"11"),uid("STAFF")));}
 @Test void sameGuestCannotRepeat(){long b=approved();var p=guestService.create(profile("12"),uid("STAFF"));var a=GuestRequests.Add.builder().guestId(p.id()).role(GuestRole.PRIMARY).build();guestService.addToBooking(b,a,uid("STAFF"));assertThrows(BusinessException.class,()->guestService.addToBooking(b,GuestRequests.Add.builder().guestId(p.id()).role(GuestRole.ACCOMPANYING).build(),uid("STAFF")));}
 @Test void missingPrimaryCannotCheckIn(){long b=approved();assertThrows(BusinessException.class,()->bookings.checkIn(b,uid("MANAGER")));assertUnchanged(b);}
 @Test void incompletePrimaryCannotConfirmOrCheckIn(){long b=approved();var p=GuestRequests.Profile.builder().firstName("A").lastName("B").build();guestService.addToBooking(b,GuestRequests.Add.builder().role(GuestRole.PRIMARY).profile(p).build(),uid("STAFF"));assertThrows(BusinessException.class,()->guestService.confirm(b,uid("STAFF")));assertThrows(BusinessException.class,()->bookings.checkIn(b,uid("MANAGER")));assertUnchanged(b);}
 @Test void unconfirmedCannotCheckIn(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"13"),uid("STAFF"));assertThrows(BusinessException.class,()->bookings.checkIn(b,uid("MANAGER")));assertUnchanged(b);}
 @Test void staffConfirmationEnablesCheckIn(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"14"),uid("STAFF"));var r=guestService.confirm(b,uid("STAFF"));assertTrue(r.confirmed());bookings.checkIn(b,uid("MANAGER"));assertEquals(2,bookingState(b));}
 @Test void customerCannotConfirmAndHrCannotOperate(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"15"),uid("STAFF"));assertThrows(AccessDeniedException.class,()->guestService.confirm(b,uid("CUSTOMER")));assertThrows(AccessDeniedException.class,()->guestService.search(null,uid("HR_ADMIN")));}
 @Test void customerOwnerScopeForBookingGuests(){long b=approved();assertTrue(guestService.myBookingGuests(b,uid("CUSTOMER")).isEmpty());assertThrows(AccessDeniedException.class,()->guestService.myBookingGuests(b,uid("STAFF")));}
 @Test void customerPreRegistrationCreatesPrimary(){long b=approved();var e=guestService.preRegister(b,add(GuestRole.PRIMARY,"16"),uid("CUSTOMER"));assertEquals(uid("CUSTOMER"),e.guest().linkedUserId());assertEquals(GuestRole.PRIMARY,e.role());}
 @Test void confirmedListIsImmutableButCheckedInMayAddAccompanying(){long b=approved();var e=guestService.addToBooking(b,add(GuestRole.PRIMARY,"17"),uid("STAFF"));guestService.confirm(b,uid("MANAGER"));assertThrows(BusinessException.class,()->guestService.removeFromBooking(b,e.relationId(),uid("STAFF")));bookings.checkIn(b,uid("MANAGER"));guestService.addToBooking(b,add(GuestRole.ACCOMPANYING,"18"),uid("STAFF"));assertEquals(2,guestService.bookingGuests(b,uid("STAFF")).size());}
 @Test void checkoutHistoryCannotBeChangedAndGuestHistoryUsesAssignment(){long b=approved();var e=guestService.addToBooking(b,add(GuestRole.PRIMARY,"19"),uid("STAFF"));guestService.confirm(b,uid("STAFF"));bookings.checkIn(b,uid("MANAGER"));pay(b,"300");clock.day(3);checkout(b);assertEquals(1,guestService.stays(e.guest().id(),uid("STAFF")).size());assertThrows(BusinessException.class,()->guestService.addToBooking(b,add(GuestRole.ACCOMPANYING,"20"),uid("STAFF")));assertEquals(uid("CUSTOMER"),jdbc.queryForObject("SELECT user_id FROM stay_history WHERE folio_id=?",Long.class,folio(b)));}
 @Test void duplicateDetectionStrongDocumentButDoesNotMergeNames(){var p=guestService.create(profile("21"),uid("STAFF"));var same=profile("21");assertEquals(p.id(),guestService.duplicateCandidates(same,uid("STAFF")).get(0).id());var nameOnly=profile("22");nameOnly.setFirstName(p.firstName());nameOnly.setLastName(p.lastName());nameOnly.setDateOfBirth(null);nameOnly.setPhone(null);nameOnly.setEmail(null);assertTrue(guestService.duplicateCandidates(nameOnly,uid("STAFF")).isEmpty());var second=guestService.create(nameOnly,uid("STAFF"));assertNotEquals(p.id(),second.id());}
 @Test void concurrentPrimaryAllowsOne(){long b=approved();var pool=Executors.newFixedThreadPool(2);try{var fs=List.of(pool.submit(()->attempt(()->guestService.addToBooking(b,add(GuestRole.PRIMARY,"23"),uid("STAFF")))),pool.submit(()->attempt(()->guestService.addToBooking(b,add(GuestRole.PRIMARY,"24"),uid("MANAGER")))));assertEquals(1,fs.stream().map(this::await).filter(Objects::isNull).count());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM booking_guest WHERE booking_id=? AND guest_role=0",Integer.class,b));}finally{pool.shutdownNow();}}
 @Test void concurrentConfirmationCreatesOne(){long b=approved();guestService.addToBooking(b,add(GuestRole.PRIMARY,"25"),uid("STAFF"));var pool=Executors.newFixedThreadPool(2);try{var fs=List.of(pool.submit(()->attempt(()->guestService.confirm(b,uid("STAFF")))),pool.submit(()->attempt(()->guestService.confirm(b,uid("MANAGER")))));fs.forEach(this::await);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM guest_registration WHERE booking_id=?",Integer.class,b));}finally{pool.shutdownNow();}}
 @Test void securityEndpoints(){assertDoesNotThrow(()->mvc.perform(get("/api/admin/guests").with(authentication(auth("STAFF")))).andExpect(status().isOk()));assertDoesNotThrow(()->mvc.perform(get("/api/admin/guests").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden()));assertDoesNotThrow(()->mvc.perform(get("/api/admin/guests").with(authentication(auth("HR_ADMIN")))).andExpect(status().isForbidden()));assertDoesNotThrow(()->mvc.perform(get("/api/guests/me")).andExpect(status().isUnauthorized()));}
 @Test void registrationValidationFailureNeverChangesBookingRoomOrAssignment(){long b=approved();assertThrows(BusinessException.class,()->bookings.checkIn(b,uid("MANAGER")));assertUnchanged(b);assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=?",Integer.class,folio(b)));}

 void assertUnchanged(long b){assertEquals(1,bookingState(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM booking_room_assignment WHERE booking_id=?",Integer.class,b));assertNotEquals(4,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
 Throwable attempt(Runnable r){try{r.run();return null;}catch(Throwable t){return t;}}Throwable await(Future<Throwable> f){try{return f.get(20,TimeUnit.SECONDS);}catch(Exception e){throw new AssertionError(e);}}
}
