package com.johnny.hotel.wallet;
import com.johnny.hotel.extras.*;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.pagination.PaginationProperties;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.security.access.AccessDeniedException;import java.math.BigDecimal;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;
class GuestExtrasDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired GuestExtrasService extras;@Autowired PaginationProperties pagination;@Autowired com.johnny.hotel.task.HotelTaskService taskService;
 @BeforeEach void financeActor(){long id=users.registerEmployee(employeeRequest("FINANCE")).getId();created.add(id);actors.put("FINANCE",id);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",id);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='FINANCE'",id);}
 ChargeCatalog catalog(ChargeType type,String suffix,String price){as("MANAGER");return extras.createCatalog(ExtrasRequests.Catalog.builder().code(("EX"+run+suffix).toUpperCase(Locale.ROOT)).name(type+suffix).type(type).category("TEST").unitPrice(new BigDecimal(price)).description("test catalog").build());}
 ExtrasRequests.ServiceOrder serviceReq(long c,String key){return ExtrasRequests.ServiceOrder.builder().catalogId(c).quantity(new BigDecimal("2.00")).requestKey(key).note("please deliver").build();}
 ExtrasRequests.Purchase purchaseReq(String key,long... ids){var lines=Arrays.stream(ids).mapToObj(i->ExtrasRequests.PurchaseLine.builder().catalogId(i).quantity(new BigDecimal("2.00")).build()).toList();return ExtrasRequests.Purchase.builder().requestKey(key).items(lines).build();}
 void claimAndAcknowledge(GuestServiceOrder order){extras.claimService(order.getId());assertEquals(0,jdbc.queryForObject("SELECT status FROM todo WHERE task_id=? AND is_active=1",Integer.class,order.getTaskId()));assertEquals(0,jdbc.queryForObject("SELECT status FROM guest_service_order WHERE id=?",Integer.class,order.getId()));long todo=jdbc.queryForObject("SELECT id FROM todo WHERE task_id=? AND is_active=1",Long.class,order.getTaskId());taskService.updateTodo(todo,"ACKNOWLEDGE",null);assertEquals(1,jdbc.queryForObject("SELECT status FROM guest_service_order WHERE id=?",Integer.class,order.getId()));}
 GuestServiceOrder order(long booking){var c=catalog(ChargeType.SERVICE,UUID.randomUUID().toString().substring(0,5),"12.50");as("CUSTOMER");return extras.createService(booking,serviceReq(c.getId(),"svc-"+UUID.randomUUID()));}
 @Test void migrationAndEnums(){assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='27'",Integer.class));assertEquals(0,ChargeType.SERVICE.getCode());assertEquals(1,ChargeType.PRODUCT.getCode());assertEquals(6,com.johnny.hotel.task.TaskType.GUEST_SERVICE.getCode());}
 @Test void managerMaintainsCatalogStaffOnlyReads(){var c=catalog(ChargeType.PRODUCT,"A","5.00");as("STAFF");assertEquals(1,extras.catalogs(null,null,null,1,20).getItems().stream().filter(x->x.getId().equals(c.getId())).count());assertThrows(AccessDeniedException.class,()->extras.createCatalog(ExtrasRequests.Catalog.builder().code("NO").name("No").type(ChargeType.PRODUCT).category("T").unitPrice(BigDecimal.ONE).build()));as("MANAGER");extras.setCatalogStatus(c.getId(),false);as("STAFF");assertFalse(extras.catalogs(null,null,null,1,100).getItems().stream().anyMatch(x->x.getId().equals(c.getId())));}
 @Test void serviceCreatesTaskAndSnapshotsPrice(){long b=stay();var o=order(b);assertEquals(0,o.getStatus());assertEquals(6,jdbc.queryForObject("SELECT task_type FROM hotel_task WHERE id=?",Integer.class,o.getTaskId()));assertEquals(0,new BigDecimal("25.00").compareTo(o.getAmount()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_SERVICE_ORDER' AND source_id=?",Integer.class,o.getId()));}
 @Test void serviceClaimRequiresExplicitTodoAcknowledge(){long b=stay();var o=order(b);as("STAFF");extras.claimService(o.getId());assertEquals(0,jdbc.queryForObject("SELECT status FROM todo WHERE task_id=? AND is_active=1",Integer.class,o.getTaskId()));assertEquals(0,jdbc.queryForObject("SELECT status FROM guest_service_order WHERE id=?",Integer.class,o.getId()));assertThrows(BusinessException.class,()->extras.completeService(o.getId(),"too early",false));long todo=jdbc.queryForObject("SELECT id FROM todo WHERE task_id=? AND is_active=1",Long.class,o.getTaskId());taskService.updateTodo(todo,"ACKNOWLEDGE",null);assertEquals(1,jdbc.queryForObject("SELECT status FROM guest_service_order WHERE id=?",Integer.class,o.getId()));extras.completeService(o.getId(),"done",false);}
 @Test void serviceCompletionPostsExactlyOnce(){long b=stay();var o=order(b);as("STAFF");claimAndAcknowledge(o);var done=extras.completeService(o.getId(),"done",false);var retry=extras.completeService(o.getId(),"done",false);assertEquals(2,done.getStatus());assertEquals(done.getFolioItemId(),retry.getFolioItemId());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_SERVICE_ORDER' AND source_id=?",Integer.class,o.getId()));assertEquals(0,new BigDecimal("25.00").compareTo(jdbc.queryForObject("SELECT amount FROM folio_item WHERE id=?",BigDecimal.class,done.getFolioItemId())));}
 @Test void cancelledServiceNeverCharges(){long b=stay();var o=order(b);as("STAFF");extras.cancelService(o.getId(),"cancelled");assertEquals(3,extras.services(b,null,1,20).getItems().get(0).getStatus());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_SERVICE_ORDER' AND source_id=?",Integer.class,o.getId()));}
 @Test void purchaseSupportsMultipleProductsAndSnapshot(){long b=stay();var a=catalog(ChargeType.PRODUCT,"B","3.25");var c=catalog(ChargeType.PRODUCT,"C","7.00");as("CUSTOMER");var p=extras.createPurchase(b,purchaseReq("buy-"+UUID.randomUUID(),a.getId(),c.getId()));assertEquals(0,new BigDecimal("20.50").compareTo(p.getTotalAmount()));assertEquals(2,extras.purchaseItems(p.getId()).size());as("MANAGER");extras.updateCatalog(a.getId(),ExtrasRequests.Catalog.builder().code(a.getCode()).name("Changed").type(ChargeType.PRODUCT).category("NEW").unitPrice(new BigDecimal("99.00")).build());as("STAFF");extras.confirmPurchase(p.getId());assertEquals(0,new BigDecimal("20.50").compareTo(jdbc.queryForObject("SELECT SUM(amount) FROM folio_item WHERE source_type='GUEST_PURCHASE_ITEM' AND source_id IN (SELECT id FROM guest_purchase_item WHERE purchase_id=?)",BigDecimal.class,p.getId())));}
 @Test void purchaseCreateAndConfirmRetriesAreIdempotent(){long b=stay();var c=catalog(ChargeType.PRODUCT,"D","4.00");String key="buy-"+UUID.randomUUID();as("CUSTOMER");var a=extras.createPurchase(b,purchaseReq(key,c.getId()));var same=extras.createPurchase(b,purchaseReq(key,c.getId()));assertEquals(a.getId(),same.getId());as("STAFF");extras.confirmPurchase(a.getId());extras.confirmPurchase(a.getId());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_PURCHASE_ITEM' AND source_id IN (SELECT id FROM guest_purchase_item WHERE purchase_id=?)",Integer.class,a.getId()));}
 @Test void purchaseRetryWithDifferentContentIsRejected(){long b=stay();var a=catalog(ChargeType.PRODUCT,"D1","4.00");var c=catalog(ChargeType.PRODUCT,"D2","5.00");String key="buy-"+UUID.randomUUID();as("CUSTOMER");extras.createPurchase(b,purchaseReq(key,a.getId()));assertThrows(BusinessException.class,()->extras.createPurchase(b,purchaseReq(key,c.getId())));}
 @Test void cancelledPurchaseNeverCharges(){long b=stay();var c=catalog(ChargeType.PRODUCT,"E","4.00");as("CUSTOMER");var p=extras.createPurchase(b,purchaseReq("buy-"+UUID.randomUUID(),c.getId()));extras.cancelPurchase(p.getId());assertEquals(2,extras.purchases(b,null,1,20).getItems().get(0).getStatus());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_PURCHASE_ITEM' AND source_id IN (SELECT id FROM guest_purchase_item WHERE purchase_id=?)",Integer.class,p.getId()));}
 @Test void customerOwnershipAndHrBoundary(){long a=stay(),other=createBooking("OTHER_CUSTOMER");var c=catalog(ChargeType.PRODUCT,"F","2.00");as("CUSTOMER");assertThrows(BusinessException.class,()->extras.createPurchase(other,purchaseReq("idor",c.getId())));as("HR_ADMIN");assertThrows(AccessDeniedException.class,()->extras.catalogs(null,null,null,1,20));}
 @Test void httpSecurityBoundaries()throws Exception{mvc.perform(get("/api/extras/catalog")).andExpect(status().isUnauthorized());mvc.perform(get("/api/extras/catalog").with(authentication(auth("HR_ADMIN")))).andExpect(status().isForbidden());mvc.perform(get("/api/extras/catalog").with(authentication(auth("CUSTOMER")))).andExpect(status().isOk());mvc.perform(post("/api/extras/catalog").with(authentication(auth("STAFF"))).contentType("application/json").content("{\"code\":\"DENIED\",\"name\":\"Denied\",\"type\":\"PRODUCT\",\"category\":\"T\",\"unitPrice\":1.00}")) .andExpect(status().isForbidden());mvc.perform(get("/api/extras/catalog").with(authentication(auth("FINANCE")))).andExpect(status().isOk());}
 @Test void financeReadsButCannotOperate(){long b=stay();var c=catalog(ChargeType.PRODUCT,"G","2.00");as("FINANCE");assertFalse(extras.catalogs(null,null,null,1,20).getItems().isEmpty());assertThrows(AccessDeniedException.class,()->extras.createPurchase(b,purchaseReq("finance",c.getId())));}
 @Test void paginationUsesSharedLimits(){catalog(ChargeType.PRODUCT,"H1","1.00");catalog(ChargeType.PRODUCT,"H2","1.00");as("FINANCE");var page=extras.catalogs(1,null,null,1,1);assertEquals(1,page.getItems().size());assertTrue(page.isHasNext());assertThrows(BusinessException.class,()->extras.catalogs(null,null,null,1,pagination.getMaxPageSize()+1));}
 @Test void folioFailureRollsBackServiceAndTaskCompletion(){long b=stay();var o=order(b);as("STAFF");claimAndAcknowledge(o);String old=Thread.currentThread().getName();gate.arm("extras-fail","FolioItemMapper.insert",true);Thread.currentThread().setName("extras-fail");try{assertThrows(RuntimeException.class,()->extras.completeService(o.getId(),"done",false));}finally{Thread.currentThread().setName(old);gate.clear();}assertEquals(1,jdbc.queryForObject("SELECT status FROM guest_service_order WHERE id=?",Integer.class,o.getId()));assertEquals(1,jdbc.queryForObject("SELECT status FROM hotel_task WHERE id=?",Integer.class,o.getTaskId()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_SERVICE_ORDER' AND source_id=?",Integer.class,o.getId()));}
 @Test void concurrentPurchaseConfirmPostsOnce()throws Exception{long b=stay();var c=catalog(ChargeType.PRODUCT,"I","2.00");as("CUSTOMER");var p=extras.createPurchase(b,purchaseReq("buy-"+UUID.randomUUID(),c.getId()));var pool=Executors.newFixedThreadPool(2);try{var fs=List.of(worker(pool,"pc1",()->extras.confirmPurchase(p.getId())),worker(pool,"pc2",()->extras.confirmPurchase(p.getId())));assertNull(result(fs.get(0)));assertNull(result(fs.get(1)));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_PURCHASE_ITEM' AND source_id IN (SELECT id FROM guest_purchase_item WHERE purchase_id=?)",Integer.class,p.getId()));}finally{pool.shutdownNow();}}
 @Test void concurrentServiceCompletionPostsOnce()throws Exception{long b=stay();var o=order(b);as("STAFF");claimAndAcknowledge(o);var pool=Executors.newFixedThreadPool(2);try{var calls=new ArrayList<Future<Throwable>>();for(int i=0;i<2;i++){final int n=i;calls.add(pool.submit(()->{Thread.currentThread().setName("sc"+n);as("STAFF");try{extras.completeService(o.getId(),"done",false);return null;}catch(Throwable e){return e;}}));}assertNull(result(calls.get(0)));assertNull(result(calls.get(1)));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE source_type='GUEST_SERVICE_ORDER' AND source_id=?",Integer.class,o.getId()));}finally{pool.shutdownNow();}}
 @Test void extrasNeverChangeBookingContract(){long b=stay();var price=jdbc.queryForObject("SELECT total_price FROM booking WHERE id=?",BigDecimal.class,b);var out=jdbc.queryForObject("SELECT check_out_date FROM booking WHERE id=?",java.sql.Date.class,b);var o=order(b);as("STAFF");claimAndAcknowledge(o);extras.completeService(o.getId(),null,false);assertEquals(0,price.compareTo(jdbc.queryForObject("SELECT total_price FROM booking WHERE id=?",BigDecimal.class,b)));assertEquals(out,jdbc.queryForObject("SELECT check_out_date FROM booking WHERE id=?",java.sql.Date.class,b));}
 @Test void checkoutComposesExtrasAndExpenseValidators(){long b=stay();var o=order(b);as("STAFF");claimAndAcknowledge(o);extras.completeService(o.getId(),null,false);var expense=expenses.register(folio(b),expense("10.00"));expenses.confirm(folio(b),expense.id());pay(b,"335.00");clock.day(3);checkout(b);assertEquals(3,bookingState(b));}
 @Test void checkoutBlocksUnresolvedExtras(){long b=stay();order(b);pay(b,"300.00");clock.day(3);assertThrows(BusinessException.class,()->checkout(b));assertEquals(2,bookingState(b));}
}
