package com.johnny.hotel.wallet;
import com.johnny.hotel.task.*; import com.johnny.hotel.exception.BusinessException;
import org.junit.jupiter.api.*; import org.junit.jupiter.params.ParameterizedTest; import org.junit.jupiter.params.provider.ValueSource; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.security.access.AccessDeniedException;
import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
@org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
class HotelTaskDevelopmentTest extends FinancialDevelopmentFixture {
 @Autowired HotelTaskService tasks; @Autowired org.flywaydb.core.Flyway flyway;
 TaskRequests.CreateGeneral request(String key){return TaskRequests.CreateGeneral.builder().title("Prepare lobby").description("Operational preparation").requestKey(key).build();}
 HotelTask general(String role,String key){as(role);return tasks.createGeneral(request(key));}
 TaskRequests.Assign assign(Long... ids){return TaskRequests.Assign.builder().assigneeUserIds(List.of(ids)).note("Manager assignment").build();}
 void secondStaff(){long id=users.registerEmployee(employeeRequest("STAFF")).getId();created.add(id);actors.put("OTHER_STAFF",id);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",id);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='STAFF'",id);}
 int records(long id,int type){return jdbc.queryForObject("SELECT COUNT(*) FROM task_record WHERE task_id=? AND record_type=?",Integer.class,id,type);}
 @Test void migrationBackfillsV14Turnover(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='15'",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task r LEFT JOIN hotel_task t ON t.id=r.task_id WHERE t.id IS NULL OR t.task_type<>0 OR t.assignment_mode<>0",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE task_id IS NULL",Integer.class));}
 @Test void staffCreatesOnlyClaimablePendingGeneralAndRetryIsStable(){var t=general("STAFF","general_01");assertEquals(1,t.getTaskType());assertEquals(0,t.getStatus());assertEquals(0,t.getAssignmentMode());assertEquals(t.getId(),tasks.createGeneral(request("general_01")).getId());assertEquals(1,records(t.getId(),0));}
 @Test void staffCannotUseManagerOperations(){var t=general("STAFF","general_01");as("STAFF");assertThrows(AccessDeniedException.class,()->tasks.assign(t.getId(),assign(uid("OTHER_CUSTOMER"))));assertThrows(AccessDeniedException.class,()->tasks.reassign(t.getId(),assign(uid("STAFF"))));assertThrows(AccessDeniedException.class,()->tasks.cancel(t.getId(),null));assertThrows(AccessDeniedException.class,()->tasks.forceComplete(t.getId(),null));}
 @ParameterizedTest @ValueSource(strings={"MANAGER","OWNER","SUPER_ADMIN"}) void managerSingleAssignmentRequiresAcceptance(String role){var t=general(role,"general_01");as(role);var v=tasks.assign(t.getId(),assign(uid("STAFF")));assertEquals(0,v.getTask().getStatus());assertEquals(1,v.getTask().getAssignmentMode());assertEquals(0,v.getAssignments().get(0).getStatus());as("STAFF");assertEquals(1,tasks.accept(t.getId()).getTask().getStatus());assertEquals(1,tasks.myTodo().size());assertEquals(2,tasks.complete(t.getId(),"Done").getTask().getStatus());assertTrue(tasks.myTodo().isEmpty());}
 @Test void multiAssignmentCompletesOnlyAfterAllCurrentAssigneesFinish(){secondStaff();var t=general("MANAGER","general_01");as("MANAGER");var v=tasks.assign(t.getId(),assign(uid("STAFF"),uid("OTHER_STAFF")));assertEquals(2,v.getTask().getAssignmentMode());as("STAFF");tasks.accept(t.getId());tasks.complete(t.getId(),null);assertEquals(1,tasks.get(t.getId()).getTask().getStatus());as("OTHER_STAFF");tasks.accept(t.getId());assertEquals(2,tasks.complete(t.getId(),null).getTask().getStatus());assertEquals(2,records(t.getId(),3));assertEquals(2,records(t.getId(),4));}
 @Test void todoIsOwnedAndContainsOnlyUnfinishedCurrentAssignments(){secondStaff();var t=general("MANAGER","general_01");as("MANAGER");tasks.assign(t.getId(),assign(uid("STAFF"),uid("OTHER_STAFF")));as("STAFF");assertEquals(uid("STAFF"),tasks.myTodo().get(0).getAssigneeUserId());tasks.accept(t.getId());tasks.complete(t.getId(),null);assertTrue(tasks.myTodo().isEmpty());as("OTHER_STAFF");assertEquals(uid("OTHER_STAFF"),tasks.myTodo().get(0).getAssigneeUserId());}
 @Test void employeeCanOnlyAcceptAndCompleteOwnAssignment(){secondStaff();var t=general("MANAGER","general_01");as("MANAGER");tasks.assign(t.getId(),assign(uid("STAFF")));as("OTHER_STAFF");assertThrows(AccessDeniedException.class,()->tasks.accept(t.getId()));as("STAFF");assertThrows(BusinessException.class,()->tasks.complete(t.getId(),null));tasks.accept(t.getId());as("OTHER_STAFF");assertThrows(AccessDeniedException.class,()->tasks.complete(t.getId(),null));}
 @Test void claimCreatesAcceptedAssignmentAndConcurrentClaimHasOneWinner(){secondStaff();var t=general("MANAGER","general_01");assertInstanceOf(BusinessException.class,serialized("HotelTaskMapper.transition",()->{as("STAFF");tasks.claim(t.getId());},()->{as("OTHER_STAFF");tasks.claim(t.getId());}));as("MANAGER");var v=tasks.get(t.getId());assertEquals(1,v.getTask().getStatus());assertEquals(1,v.getAssignments().size());assertEquals(1,v.getAssignments().get(0).getStatus());assertEquals(1,records(t.getId(),1));}
 @Test void assignedTaskCannotBeClaimed(){var t=general("MANAGER","general_01");as("MANAGER");tasks.assign(t.getId(),assign(uid("STAFF")));as("OTHER_CUSTOMER");assertThrows(AccessDeniedException.class,()->tasks.claim(t.getId()));as("STAFF");assertThrows(BusinessException.class,()->tasks.claim(t.getId()));}
 @Test void reassignKeepsHistoryAndCreatesNewRound(){secondStaff();var t=general("MANAGER","general_01");as("MANAGER");tasks.assign(t.getId(),assign(uid("STAFF")));tasks.reassign(t.getId(),assign(uid("OTHER_STAFF")));var v=tasks.get(t.getId());assertEquals(2,v.getAssignments().size());assertEquals(0,v.getAssignments().get(0).getIsCurrent());assertNotNull(v.getAssignments().get(0).getEndedTime());assertEquals(1,v.getAssignments().get(1).getIsCurrent());assertEquals(2,v.getAssignments().get(1).getAssignmentRound());assertEquals(1,records(t.getId(),6));}
 @Test void cancelAndForceCompleteAreTerminalAndRecorded(){var cancelled=general("MANAGER","cancel_01");as("MANAGER");tasks.cancel(cancelled.getId(),"No longer needed");assertEquals(3,tasks.get(cancelled.getId()).getTask().getStatus());assertEquals(1,records(cancelled.getId(),7));assertThrows(BusinessException.class,()->tasks.claim(cancelled.getId()));var done=general("MANAGER","done_01");tasks.assign(done.getId(),assign(uid("STAFF")));tasks.forceComplete(done.getId(),"Supervisor verified");var v=tasks.get(done.getId());assertEquals(2,v.getTask().getStatus());assertEquals(2,v.getAssignments().get(0).getStatus());assertEquals(1,records(done.getId(),5));}
 @Test void roomTurnoverAllowsOnlyOneResponsibleEmployeeAndRoomStaysMaintenance(){long b=stay();pay(b,"300");clock.day(3);checkout(b);long core=jdbc.queryForObject("SELECT task_id FROM room_turnover_task WHERE booking_id=?",Long.class,b);as("MANAGER");assertThrows(BusinessException.class,()->tasks.assign(core,assign(uid("STAFF"),uid("MANAGER"))));as("STAFF");tasks.claim(core);tasks.complete(core,"Cleaned");assertEquals(2,tasks.get(core).getTask().getStatus());assertEquals(3,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
 @Test void checkoutAndRoomChangeCreateCoreTaskAndRecords(){long b=stay();long first=jdbc.queryForObject("SELECT id FROM booking_room_assignment WHERE booking_id=?",Long.class,b);clock.day(1);var r=new com.johnny.hotel.dto.ChangeRoomDuringStayRequest();r.setNewRoomId(room2);r.setReason("Move");bookings.changeRoomDuringStay(b,r,uid("MANAGER"));pay(b,"300");clock.day(3);checkout(b);assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE booking_id=?",Integer.class,b));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task h JOIN room_turnover_task r ON r.task_id=h.id WHERE r.booking_id=? AND h.task_type=0 AND h.status=0",Integer.class,b));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE assignment_id=?",Integer.class,first));}
 @ParameterizedTest @ValueSource(strings={"HotelTaskMapper.insert","TaskRecordMapper.insert","RoomTurnoverTaskMapper.insert"}) void taskCreationFailureRollsBackCheckout(String statement){long b=stay();pay(b,"300");clock.day(3);long assignment=jdbc.queryForObject("SELECT id FROM booking_room_assignment WHERE booking_id=?",Long.class,b);gate.arm(Thread.currentThread().getName(),statement,true);assertThrows(Exception.class,()->checkout(b));assertEquals(2,bookingState(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE booking_id=?",Integer.class,b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_task WHERE source_key=?",Integer.class,"ROOM_TURNOVER_ASSIGNMENT:"+assignment));assertNull(jdbc.queryForObject("SELECT end_time FROM booking_room_assignment WHERE booking_id=?",java.time.LocalDateTime.class,b));}
 @ParameterizedTest @ValueSource(strings={"CUSTOMER","HR_ADMIN"}) void forbiddenRolesCannotReadOrMutate(String role)throws Exception{var t=general("MANAGER","general_01");as(role);assertThrows(AccessDeniedException.class,()->tasks.list(null,null,1,50));mvc.perform(get("/api/tasks").with(authentication(auth(role)))).andExpect(status().isForbidden());mvc.perform(post("/api/tasks/general").with(authentication(auth(role))).contentType("application/json").content("{\"title\":\"x\",\"requestKey\":\"key_123\"}")).andExpect(status().isForbidden());}
 @Test void unauthenticatedIs401AndStaffAdminApiIs403()throws Exception{var t=general("STAFF","general_01");mvc.perform(get("/api/tasks").with(anonymous())).andExpect(status().isUnauthorized());mvc.perform(post("/api/admin/tasks/"+t.getId()+"/cancel").with(authentication(auth("STAFF")))).andExpect(status().isForbidden());}
 @Test void httpCreateAssignAcceptCompleteAndTodoUseJwtIdentity()throws Exception{mvc.perform(post("/api/tasks/general").with(authentication(auth("STAFF"))).contentType("application/json").content("{\"title\":\"Prepare lobby\",\"requestKey\":\"http_general_01\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.assignmentMode").value(0));long id=jdbc.queryForObject("SELECT id FROM hotel_task WHERE request_key='http_general_01' AND created_by=?",Long.class,uid("STAFF"));mvc.perform(post("/api/admin/tasks/"+id+"/assign").with(authentication(auth("MANAGER"))).contentType("application/json").content("{\"assigneeUserIds\":["+uid("STAFF")+"]}")).andExpect(status().isOk());mvc.perform(get("/api/tasks/my-todo").with(authentication(auth("STAFF")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(1));mvc.perform(post("/api/tasks/"+id+"/accept").with(authentication(auth("STAFF")))).andExpect(status().isOk());mvc.perform(post("/api/tasks/"+id+"/complete").with(authentication(auth("STAFF")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.task.status").value(2));mvc.perform(get("/api/tasks/my-todo").with(authentication(auth("STAFF")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(0));}
 @Test void taskRecordIsAppendOnlyThroughPublicApi(){var t=general("STAFF","general_01");as("STAFF");tasks.claim(t.getId());tasks.complete(t.getId(),"Done");assertEquals(List.of(0,1,4),jdbc.queryForList("SELECT record_type FROM task_record WHERE task_id=? ORDER BY id",Integer.class,t.getId()));assertThrows(Exception.class,()->jdbc.update("DELETE FROM hotel_task WHERE id=?",t.getId()));}
}
