package com.johnny.hotel.wallet;
import com.johnny.hotel.cleaning.*;import com.johnny.hotel.inspection.*;import com.johnny.hotel.service.RoomTurnoverTaskService;import com.johnny.hotel.task.*;import com.johnny.hotel.exception.BusinessException;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import java.util.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class InspectionDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired InspectionService inspections;@Autowired RoomTurnoverTaskService turnovers;@Autowired CleaningService cleaning;@Autowired HotelTaskService tasks;@Autowired com.johnny.hotel.repair.RepairOrderService repairs;@Autowired org.flywaydb.core.Flyway flyway;
 RoomInspection pending(){long b=stay();pay(b,"300");clock.day(3);checkout(b);long turnover=jdbc.queryForObject("SELECT id FROM room_turnover_task WHERE stay_id=(SELECT id FROM stay WHERE booking_id=?)",Long.class,b);as("MANAGER");turnovers.complete(turnover,"clean");return inspections.room(room1).get(0);}
 InspectionRequests.Decide pass(){return InspectionRequests.Decide.builder().passed(true).build();}InspectionRequests.Decide fail(InspectionFailureReason r){return InspectionRequests.Decide.builder().passed(false).failureReason(r).notes("inspection issue requires follow-up").build();}
 @Test void migrationEnumsAndTurnoverCreatesOnePendingInspection(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='23'",Integer.class));var i=pending();assertEquals(0,i.getStatus());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM housekeeping_inspection WHERE cleaning_record_id=?",Integer.class,i.getCleaningRecordId()));assertEquals(2,CleaningType.REWORK.getCode());assertEquals(5,TaskType.ROOM_REPAIR.getCode());}
 @Test void passQualifiesReleaseButCannotBypassActiveFollowups(){var i=pending();as("STAFF");inspections.decide(i.getId(),pass());rooms.setRoomAvailable(room1);assertEquals(1,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
 @Test void cleaningIncompleteCreatesReworkAndCompletionCreatesNextInspection(){var i=pending();as("STAFF");var failed=inspections.decide(i.getId(),fail(InspectionFailureReason.CLEANING_INCOMPLETE));assertEquals(2,failed.getStatus());assertEquals(4,jdbc.queryForObject("SELECT task_type FROM hotel_task WHERE id=?",Integer.class,failed.getFollowupTaskId()));as("MANAGER");cleaning.complete(failed.getFollowupTaskId(),"reworked",true);assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM housekeeping_inspection WHERE turnover_task_id=?",Integer.class,i.getTurnoverTaskId()));assertEquals(2,jdbc.queryForObject("SELECT cleaning_type FROM cleaning_record WHERE task_id=?",Integer.class,failed.getFollowupTaskId()));assertThrows(BusinessException.class,()->rooms.setRoomAvailable(room1));}
 @Test void facilityDamageCreatesBlockingWorkOrder(){var i=pending();as("STAFF");var f=inspections.decide(i.getId(),fail(InspectionFailureReason.FACILITY_DAMAGE));assertEquals(3,jdbc.queryForObject("SELECT task_type FROM hotel_task WHERE id=?",Integer.class,f.getFollowupTaskId()));assertEquals(1,jdbc.queryForObject("SELECT blocks_room_release FROM room_work_order WHERE task_id=?",Integer.class,f.getFollowupTaskId()));assertThrows(BusinessException.class,()->rooms.setRoomAvailable(room1));}
 @Test void structuralDamageCreatesRepairAndBlocksRelease(){var i=pending();as("MANAGER");var f=inspections.decide(i.getId(),fail(InspectionFailureReason.STRUCTURAL_DAMAGE));assertEquals(5,jdbc.queryForObject("SELECT task_type FROM hotel_task WHERE id=?",Integer.class,f.getFollowupTaskId()));assertThrows(BusinessException.class,()->rooms.setRoomAvailable(room1));long repair=jdbc.queryForObject("SELECT id FROM room_repair_task WHERE task_id=?",Long.class,f.getFollowupTaskId());repairs.complete(repair,null,true);assertThrows(BusinessException.class,()->rooms.setRoomAvailable(room1));}
 @Test void failedRequiresReasonAndNotes(){var i=pending();as("STAFF");assertThrows(BusinessException.class,()->inspections.decide(i.getId(),InspectionRequests.Decide.builder().passed(false).build()));assertThrows(BusinessException.class,()->inspections.decide(i.getId(),InspectionRequests.Decide.builder().passed(false).failureReason(InspectionFailureReason.CLEANING_INCOMPLETE).build()));}
 @Test void customerHrAndAnonymousAreDenied()throws Exception{mvc.perform(get("/api/housekeeping/inspections?roomId=1")).andExpect(status().isUnauthorized());mvc.perform(get("/api/housekeeping/inspections?roomId=1").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden());mvc.perform(get("/api/housekeeping/inspections?roomId=1").with(authentication(auth("HR_ADMIN")))).andExpect(status().isForbidden());}
 @Test void concurrentDecisionHasExactlyOneWinner()throws Exception{var i=pending();var pool=Executors.newFixedThreadPool(2);try{var calls=List.of(pool.submit(()->decision(i.getId(),true)),pool.submit(()->decision(i.getId(),false)));int ok=0;for(var c:calls)if(c.get(20,TimeUnit.SECONDS)==null)ok++;assertEquals(1,ok);assertNotEquals(0,inspections.get(i.getId()).getStatus());}finally{pool.shutdownNow();}}
 Throwable decision(long id,boolean p){try{as("STAFF");inspections.decide(id,p?pass():fail(InspectionFailureReason.STRUCTURAL_DAMAGE));return null;}catch(Throwable t){return t;}finally{org.springframework.security.core.context.SecurityContextHolder.clearContext();}}
}
