package com.johnny.hotel.wallet;import com.johnny.hotel.workorder.*;import com.johnny.hotel.task.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.exception.BusinessException;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.test.context.TestPropertySource;import org.springframework.security.access.AccessDeniedException;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@TestPropertySource(properties={"hotel.pagination.max-page-size=3","hotel.pagination.browse-limit=5"}) class PaginationDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired RoomWorkOrderService work;@Autowired HotelTaskService tasks;@Autowired org.flywaydb.core.Flyway flyway;int n;
 @Autowired com.johnny.hotel.guest.GuestService guests;@Autowired com.johnny.hotel.mapper.SysAuditLogMapper audits;
 void seed(int count){as("STAFF");for(int i=0;i<count;i++)work.report(WorkOrderRequests.Report.builder().roomId(i%2==0?room1:room2).requestKey("page-"+(n++)).damageType("PAGINATION").description("Pagination record "+i).severity(WorkOrderSeverity.LOW).blocksRoomRelease(false).build());}
 @Test void migrationAndConfiguredLimits(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='26'",Integer.class));seed(1);assertThrows(BusinessException.class,()->work.page(null,null,1,4));}
 @Test void browsePagesWithinFiveAndCannotEscape(){seed(8);var a=work.page(null,null,1,3);var b=work.page(null,null,2,3);var c=work.page(null,null,3,3);assertEquals(5,a.getTotal());assertEquals(3,a.getItems().size());assertEquals(2,b.getItems().size());assertTrue(c.getItems().isEmpty());assertTrue(a.isHasNext());assertFalse(b.isHasNext());}
 @Test void searchCanReachBeyondBrowseLimitButStillPages(){seed(8);var p=work.page(null,room1,2,3);assertTrue(p.isSearchMode());assertEquals(4,p.getTotal());assertEquals(1,p.getItems().size());}
 @Test void stableDescendingOrder(){seed(5);var p=work.page(null,null,1,3).getItems();assertTrue(p.get(0).getId()>p.get(1).getId()&&p.get(1).getId()>p.get(2).getId());}
 @Test void statusAndRoomFiltersWork(){seed(6);assertEquals(3,work.page(0,room1,1,3).getTotal());assertEquals(0,work.page(1,room1,1,3).getTotal());}
 @Test void taskRecordPagingAndActorFilter(){seed(1);long task=work.page(null,room1,1,1).getItems().get(0).getTaskId();var p=tasks.records(task,0,uid("STAFF"),1,3);assertTrue(p.isSearchMode());assertEquals(1,p.getTotal());}
 @Test void rbcaRemainsAtServiceBoundary(){seed(1);as("HR_ADMIN");assertThrows(AccessDeniedException.class,()->work.page(null,null,1,2));assertThrows(AccessDeniedException.class,()->tasks.records(1L,null,null,1,2));}
 @Test void bookingOwnershipAndTaskPoolUseStandardPages(){for(int i=0;i<4;i++)createBooking("CUSTOMER");var mine=bookings.pageMyBookings(uid("CUSTOMER"),2,3);assertEquals(4,mine.getTotal());assertEquals(1,mine.getItems().size());assertEquals(2,mine.getPage());as("STAFF");for(int i=0;i<4;i++)tasks.createGeneral(TaskRequests.CreateGeneral.builder().title("Paged task").requestKey("paged-task-"+i).build());var pool=tasks.page(0,1,null,null,null,null,1,3);assertEquals(4,pool.getTotal());assertEquals(3,pool.getItems().size());assertTrue(pool.isHasNext());as("HR_ADMIN");assertThrows(AccessDeniedException.class,()->tasks.page(null,null,null,null,null,null,1,3));}
 @Test void coreHttpListsExposePageMetadataAndKeepPermissions()throws Exception{createBooking("CUSTOMER");mvc.perform(get("/api/bookings/my").param("page","1").param("pageSize","3").with(authentication(auth("CUSTOMER")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.items").isArray()).andExpect(jsonPath("$.data.total").isNumber()).andExpect(jsonPath("$.data.pageSize").value(3));mvc.perform(get("/api/admin/bookings").param("pageSize","4").with(authentication(auth("STAFF")))).andExpect(status().isBadRequest());mvc.perform(get("/api/admin/users/pending").param("pageSize","3").with(authentication(auth("HR_ADMIN")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.items").isArray());mvc.perform(get("/api/admin/users/pending").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden());}
 @Test void auditGuestAndOrganizationGrowthListsUseStandardPages()throws Exception{as("STAFF");for(int i=0;i<4;i++)guests.create(com.johnny.hotel.guest.GuestRequests.Profile.builder().firstName("Paged").lastName("Guest"+i).build(),uid("STAFF"));for(int i=0;i<4;i++)audits.insert(com.johnny.hotel.entity.SysAuditLog.builder().operatorId(uid("OWNER")).action("PAGED_AUDIT").detail("row "+i).build());mvc.perform(get("/api/admin/guests").param("q","Paged").param("page","2").param("pageSize","3").with(authentication(auth("STAFF")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(4)).andExpect(jsonPath("$.data.items.length()").value(1));mvc.perform(get("/api/admin/guests").with(authentication(auth("CUSTOMER")))).andExpect(status().isForbidden());mvc.perform(get("/api/admin/audit-logs").param("action","PAGED_AUDIT").param("pageSize","3").with(authentication(auth("OWNER")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(4)).andExpect(jsonPath("$.data.items.length()").value(3));mvc.perform(get("/api/admin/audit-logs").with(authentication(auth("MANAGER")))).andExpect(status().isForbidden());mvc.perform(get("/api/organization/requests").param("pageSize","3").with(authentication(auth("HR_ADMIN")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.items").isArray()).andExpect(jsonPath("$.data.total").isNumber());mvc.perform(get("/api/organization/requests").param("pageSize","4").with(authentication(auth("HR_ADMIN")))).andExpect(status().isBadRequest());}
}
