package com.johnny.hotel.wallet;import com.johnny.hotel.workorder.*;import com.johnny.hotel.task.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.exception.BusinessException;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.test.context.TestPropertySource;import org.springframework.security.access.AccessDeniedException;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
@TestPropertySource(properties={"hotel.pagination.max-page-size=3","hotel.pagination.browse-limit=5"}) class PaginationDevelopmentTest extends FinancialDevelopmentFixture{
 @Autowired RoomWorkOrderService work;@Autowired HotelTaskService tasks;@Autowired org.flywaydb.core.Flyway flyway;int n;
 void seed(int count){as("STAFF");for(int i=0;i<count;i++)work.report(WorkOrderRequests.Report.builder().roomId(i%2==0?room1:room2).requestKey("page-"+(n++)).damageType("PAGINATION").description("Pagination record "+i).severity(WorkOrderSeverity.LOW).blocksRoomRelease(false).build());}
 @Test void migrationAndConfiguredLimits(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='26'",Integer.class));seed(1);assertThrows(BusinessException.class,()->work.page(null,null,1,4));}
 @Test void browsePagesWithinFiveAndCannotEscape(){seed(8);var a=work.page(null,null,1,3);var b=work.page(null,null,2,3);var c=work.page(null,null,3,3);assertEquals(5,a.getTotal());assertEquals(3,a.getItems().size());assertEquals(2,b.getItems().size());assertTrue(c.getItems().isEmpty());assertTrue(a.isHasNext());assertFalse(b.isHasNext());}
 @Test void searchCanReachBeyondBrowseLimitButStillPages(){seed(8);var p=work.page(null,room1,2,3);assertTrue(p.isSearchMode());assertEquals(4,p.getTotal());assertEquals(1,p.getItems().size());}
 @Test void stableDescendingOrder(){seed(5);var p=work.page(null,null,1,3).getItems();assertTrue(p.get(0).getId()>p.get(1).getId()&&p.get(1).getId()>p.get(2).getId());}
 @Test void statusAndRoomFiltersWork(){seed(6);assertEquals(3,work.page(0,room1,1,3).getTotal());assertEquals(0,work.page(1,room1,1,3).getTotal());}
 @Test void taskRecordPagingAndActorFilter(){seed(1);long task=work.page(null,room1,1,1).getItems().get(0).getTaskId();var p=tasks.records(task,0,uid("STAFF"),1,3);assertTrue(p.isSearchMode());assertEquals(1,p.getTotal());}
 @Test void rbcaRemainsAtServiceBoundary(){seed(1);as("HR_ADMIN");assertThrows(AccessDeniedException.class,()->work.page(null,null,1,2));assertThrows(AccessDeniedException.class,()->tasks.records(1L,null,null,1,2));}
}
