package com.johnny.hotel.wallet;

import com.johnny.hotel.dto.ChangeRoomDuringStayRequest;
import com.johnny.hotel.entity.RoomTurnoverTask;
import com.johnny.hotel.enums.TurnoverTaskStatus;
import com.johnny.hotel.exception.BusinessException;
import com.johnny.hotel.service.RoomTurnoverTaskService;
import com.johnny.hotel.stay.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.transaction.support.TransactionTemplate;
import java.time.LocalDateTime;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;

@org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
class RoomTurnoverDevelopmentTest extends FinancialDevelopmentFixture {
    @Autowired RoomTurnoverTaskService tasks;
    @Autowired StayAdjustmentService stays;
    @Autowired org.flywaydb.core.Flyway flyway;
    static final String URL="/api/admin/turnover-tasks";
    int count(long b){return jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE booking_id=?",Integer.class,b);}
    long assignment(long b){return jdbc.queryForObject("SELECT id FROM booking_room_assignment WHERE booking_id=? ORDER BY id DESC LIMIT 1",Long.class,b);}
    RoomTurnoverTask task(long b){as("MANAGER");return tasks.get(jdbc.queryForObject("SELECT id FROM room_turnover_task WHERE booking_id=? ORDER BY id DESC LIMIT 1",Long.class,b));}
    long finished(){long b=stay();pay(b,"300");clock.day(3);checkout(b);return b;}
    void change(long b){var r=new ChangeRoomDuringStayRequest();r.setNewRoomId(room2);r.setReason("Guest room move");bookings.changeRoomDuringStay(b,r,uid("MANAGER"));}
    RoomTurnoverTask create(long a){return new TransactionTemplate(txManager).execute(s->tasks.createForClosedAssignment(a));}
    void secondStaff(){long id=users.registerEmployee(employeeRequest("STAFF")).getId();created.add(id);actors.put("OTHER_STAFF",id);jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",id);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code='STAFF'",id);}
    void unchanged(long b){assertEquals(2,bookingState(b));assertNull(jdbc.queryForObject("SELECT end_time FROM booking_room_assignment WHERE booking_id=?",LocalDateTime.class,b));assertEquals(4,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));assertEquals(1,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room2));assertEquals(0,count(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_history WHERE folio_id=?",Integer.class,folio(b)));assertNull(queries.byBooking(b,uid("CUSTOMER")).closedTime());invariantBooking(b);}

    @Test void migrationBackfillsClosedAssignmentsAndValidates(){flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='14'",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM booking_room_assignment a LEFT JOIN room_turnover_task t ON t.assignment_id=a.id WHERE a.end_time IS NOT NULL AND a.assignment_type IN ('CHECK_IN','ROOM_CHANGE') AND t.id IS NULL",Integer.class));for(int i=0;i<3;i++)assertEquals(i,TurnoverTaskStatus.fromCode(i).getCode());assertThrows(IllegalArgumentException.class,()->TurnoverTaskStatus.fromCode(3));}
    @Test void checkoutClosesActualStayCreatesExactlyOnePendingTask(){long b=finished();var t=task(b);assertEquals(room1,t.getRoomId());assertEquals(b,t.getBookingId());assertEquals(assignment(b),t.getAssignmentId());assertEquals(0,t.getStatus());assertNull(t.getAcceptedBy());assertNull(t.getCompletedBy());assertEquals(1,count(b));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM stay_history WHERE folio_id=?",Integer.class,folio(b)));assertEquals(arrival.plusDays(3).atTime(12,0),jdbc.queryForObject("SELECT end_time FROM booking_room_assignment WHERE booking_id=?",LocalDateTime.class,b));invariantBooking(b);}
    @Test void roomChangeThenCheckoutCreatesOneTaskForEachActualSegment(){long b=stay();long old=assignment(b);clock.day(1);change(b);assertEquals(1,count(b));assertEquals(old,task(b).getAssignmentId());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM room_turnover_task WHERE assignment_id=?",Integer.class,assignment(b)));assertEquals(3,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));assertEquals(4,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room2));pay(b,"300");clock.day(3);checkout(b);assertEquals(2,count(b));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM stay_history WHERE folio_id=?",Integer.class,folio(b)));invariantBooking(b);}
    @Test void earlyCheckoutCreatesTaskOnlyAfterActualDeparture(){long b=stay();clock.day(1);as("MANAGER");stays.apply(b,StayAdjustmentRequest.builder().type(StayAdjustmentType.EARLY_CHECKOUT).requestKey("early_001").reason("Guest departure").build());assertEquals(0,count(b));pay(b,"100");checkout(b);assertEquals(1,count(b));assertEquals(arrival.plusDays(1).atTime(12,0),jdbc.queryForObject("SELECT end_time FROM booking_room_assignment WHERE booking_id=?",LocalDateTime.class,b));invariantBooking(b);}
    @Test void generationIsIdempotentAndDatabaseRejectsDuplicateOrWrongIdentity(){long b=finished();var t=task(b);assertEquals(t.getId(),create(t.getAssignmentId()).getId());assertThrows(Exception.class,()->jdbc.update("INSERT INTO room_turnover_task(room_id,booking_id,assignment_id) VALUES(?,?,?)",room1,b,t.getAssignmentId()));jdbc.update("DELETE FROM room_turnover_task WHERE id=?",t.getId());assertThrows(Exception.class,()->jdbc.update("INSERT INTO room_turnover_task(room_id,booking_id,assignment_id) VALUES(?,?,?)",room2,b,t.getAssignmentId()));assertNull(serialized("RoomTurnoverTaskMapper.insert",()->create(t.getAssignmentId()),()->create(t.getAssignmentId())));assertEquals(1,count(b));rooms.setRoomAvailable(room1);assertNotNull(create(t.getAssignmentId()));assertEquals(1,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
    @Test void activeAssignmentAndCreationOutsideTransactionAreRejected(){long b=stay();assertThrows(BusinessException.class,()->create(assignment(b)));assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->tasks.createForClosedAssignment(assignment(b)));assertEquals(0,count(b));}
    @Test void duplicateCheckoutDoesNotCreateSecondTask(){long b=finished();try{checkout(b);}catch(BusinessException expected){}assertEquals(1,count(b));invariantBooking(b);}
    @Test void concurrentCheckoutCreatesOneTask(){long b=stay();pay(b,"300");clock.day(3);Throwable result=serialized("RoomTurnoverTaskMapper.insert",()->checkout(b),()->checkout(b));assertTrue(result==null||result instanceof BusinessException);assertEquals(1,count(b));invariantBooking(b);}
    @Test void duplicateRoomChangeCannotCloseNewAssignment(){long b=stay();clock.day(1);change(b);assertThrows(BusinessException.class,()->change(b));assertEquals(1,count(b));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM booking_room_assignment WHERE booking_id=? AND end_time IS NULL",Integer.class,b));}
    @ParameterizedTest @ValueSource(strings={"RoomTurnoverTaskMapper.insert","SysAuditLogMapper.insert"})
    void checkoutFailuresRollbackTaskHistoryRoomBookingFolioAndWallet(String statement){long b=stay();creditWallet("300");clock.day(3);gate.arm(Thread.currentThread().getName(),statement,true);assertThrows(Exception.class,()->checkout(b));unchanged(b);assertEquals(new java.math.BigDecimal("300.00"),wallets.find(wid("CUSTOMER")).getBalance());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM payment WHERE folio_id=?",Integer.class,folio(b)));}
    @ParameterizedTest @ValueSource(strings={"RoomTurnoverTaskMapper.insert","BookingRoomAssignmentMapper.insert","SysAuditLogMapper.insert"})
    void roomChangeFailuresRollbackBothRoomsAssignmentAndTask(String statement){long b=stay();clock.day(1);gate.arm(Thread.currentThread().getName(),statement,true);assertThrows(Exception.class,()->change(b));unchanged(b);assertEquals(room1,jdbc.queryForObject("SELECT assigned_room_id FROM booking WHERE id=?",Long.class,b));}
    @Test void failureAfterTaskInsertionRollsBackAllCheckoutLifecycleRows(){long b=stay();pay(b,"300");clock.day(3);gate.arm(Thread.currentThread().getName(),"SysAuditLogMapper.insert",true);assertThrows(Exception.class,()->checkout(b));unchanged(b);}
    @Test void staffAcceptThenCompleteOwnTaskPreservesMaintenance(){var t=task(finished());as("STAFF");var accepted=tasks.accept(t.getId());assertEquals(1,accepted.getStatus());assertEquals(uid("STAFF"),accepted.getAcceptedBy());assertNotNull(accepted.getAcceptedTime());assertThrows(BusinessException.class,()->tasks.accept(t.getId()));var complete=tasks.complete(t.getId(),"Cleaned");assertEquals(2,complete.getStatus());assertEquals(uid("STAFF"),complete.getCompletedBy());assertNotNull(complete.getCompletedTime());assertEquals("Cleaned",complete.getNote());assertThrows(BusinessException.class,()->tasks.accept(t.getId()));assertThrows(BusinessException.class,()->tasks.complete(t.getId(),null));assertEquals(3,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
    @Test void staffCannotDirectlyCompleteOrCompleteAnotherStaffTask(){var t=task(finished());secondStaff();as("STAFF");assertThrows(AccessDeniedException.class,()->tasks.complete(t.getId(),null));tasks.accept(t.getId());as("OTHER_STAFF");assertThrows(AccessDeniedException.class,()->tasks.complete(t.getId(),null));assertEquals(1,tasks.get(t.getId()).getStatus());}
    @ParameterizedTest @ValueSource(strings={"MANAGER","OWNER","SUPER_ADMIN"})
    void managersCanDirectlyCompleteWithoutFabricatingAcceptance(String role){var t=task(finished());as(role);var done=tasks.complete(t.getId(),null);assertEquals(2,done.getStatus());assertNull(done.getAcceptedBy());assertNull(done.getAcceptedTime());assertEquals(uid(role),done.getCompletedBy());assertEquals(3,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
    @ParameterizedTest @ValueSource(strings={"MANAGER","OWNER","SUPER_ADMIN"})
    void managersCanCompleteAnotherStaffAcceptedTask(String role){var t=task(finished());as("STAFF");tasks.accept(t.getId());as(role);assertEquals(uid(role),tasks.complete(t.getId(),null).getCompletedBy());}
    @Test void concurrentAcceptHasExactlyOneWinner(){var t=task(finished());secondStaff();assertInstanceOf(BusinessException.class,serialized("RoomTurnoverTaskMapper.accept",()->{as("STAFF");tasks.accept(t.getId());},()->{as("OTHER_STAFF");tasks.accept(t.getId());}));as("MANAGER");assertEquals(uid("STAFF"),tasks.get(t.getId()).getAcceptedBy());}
    @Test void concurrentCompletionHasExactlyOneWinner(){var t=task(finished());assertInstanceOf(BusinessException.class,serialized("RoomTurnoverTaskMapper.complete",()->tasks.complete(t.getId(),null),()->tasks.complete(t.getId(),null)));assertEquals(2,tasks.get(t.getId()).getStatus());}
    @ParameterizedTest @ValueSource(strings={"CUSTOMER","HR_ADMIN"})
    void customerAndHrHaveNoServiceOrHttpAccess(String role)throws Exception{var t=task(finished());as(role);assertThrows(AccessDeniedException.class,()->tasks.list(null,null,1,50));assertThrows(AccessDeniedException.class,()->tasks.get(t.getId()));assertThrows(AccessDeniedException.class,()->tasks.accept(t.getId()));assertThrows(AccessDeniedException.class,()->tasks.complete(t.getId(),null));mvc.perform(get(URL).with(authentication(auth(role)))).andExpect(status().isForbidden());mvc.perform(get(URL+"/"+t.getId()).with(authentication(auth(role)))).andExpect(status().isForbidden());for(String action:List.of("accept","complete"))mvc.perform(post(URL+"/"+t.getId()+"/"+action).with(authentication(auth(role)))).andExpect(status().isForbidden());}
    @ParameterizedTest @ValueSource(strings={"STAFF","MANAGER","OWNER","SUPER_ADMIN"})
    void authorizedMvcLifecycleAndFilters(String role)throws Exception{var t=task(finished());mvc.perform(get(URL).param("status","0").param("roomId",""+room1).with(authentication(auth(role)))).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(1));mvc.perform(get(URL+"/"+t.getId()).with(authentication(auth(role)))).andExpect(status().isOk());mvc.perform(post(URL+"/"+t.getId()+"/accept").with(authentication(auth(role)))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(1));mvc.perform(post(URL+"/"+t.getId()+"/complete").with(authentication(auth(role))).contentType("application/json").content("{\"note\":\"Done\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(2));as(role);assertTrue(tasks.list(0,room1,1,50).isEmpty());}
    @Test void anonymousAndInvalidRequestsAreRejected()throws Exception {
        var t=task(finished());
        org.springframework.security.test.context.TestSecurityContextHolder.clearContext();
        mvc.perform(get(URL).with(org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.anonymous())).andExpect(status().isUnauthorized());
        mvc.perform(post(URL+"/"+t.getId()+"/accept").with(org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.anonymous())).andExpect(status().isUnauthorized());
        mvc.perform(post(URL+"/"+t.getId()+"/complete").with(org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.anonymous())).andExpect(status().isUnauthorized());
        var anonymous=java.net.http.HttpRequest.newBuilder(java.net.URI.create("http://localhost:"+port+URL)).GET().build();
        assertEquals(401,java.net.http.HttpClient.newHttpClient().send(anonymous,java.net.http.HttpResponse.BodyHandlers.ofString()).statusCode());
        mvc.perform(get(URL).param("status","3").with(authentication(auth("STAFF")))).andExpect(status().isBadRequest());
        mvc.perform(post(URL+"/"+t.getId()+"/complete").with(authentication(auth("MANAGER"))).contentType("application/json").content("{\"note\":\""+"a".repeat(501)+"\"}")).andExpect(status().isBadRequest());
        as("MANAGER");assertEquals(0,tasks.get(t.getId()).getStatus());
    }
    @Test void realHttpJwtUsesExistingAuthentication()throws Exception{var t=task(finished());String token=jwt.generateToken(uid("STAFF"),"turnover@example.test","turnover-test",List.of("STAFF"));var request=java.net.http.HttpRequest.newBuilder(java.net.URI.create("http://localhost:"+port+URL+"/"+t.getId()+"/accept")).header("Authorization","Bearer "+token).POST(java.net.http.HttpRequest.BodyPublishers.noBody()).build();assertEquals(200,java.net.http.HttpClient.newHttpClient().send(request,java.net.http.HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(uid("STAFF"),tasks.get(t.getId()).getAcceptedBy());}
    @ParameterizedTest @ValueSource(booleans={true,false})
    void auditFailureRollsBackAcceptOrComplete(boolean accept){var t=task(finished());as("MANAGER");gate.arm(Thread.currentThread().getName(),"SysAuditLogMapper.insert",true);assertThrows(Exception.class,()->{if(accept)tasks.accept(t.getId());else tasks.complete(t.getId(),null);});var unchanged=tasks.get(t.getId());assertEquals(0,unchanged.getStatus());assertNull(unchanged.getAcceptedBy());assertNull(unchanged.getCompletedBy());}
}
