package com.johnny.hotel.wallet;
import com.johnny.hotel.dto.LoginRequest;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.security.AuthenticationSurface;import io.jsonwebtoken.Jwts;import io.jsonwebtoken.security.Keys;import org.junit.jupiter.api.*;import org.springframework.test.context.TestPropertySource;import java.nio.charset.StandardCharsets;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@TestPropertySource(properties={"hotel.security.public-surface.allowed-origins[0]=https://hotel.example.test","hotel.security.internal.allowed-origins[0]=https://pms.example.test"})
class SecuritySurfaceDevelopmentTest extends WalletDevelopmentFixture{
 private LoginRequest login(String role){var u=users.getUserById(uid(role));var r=new LoginRequest();r.setEmail(u.getEmail());r.setPassword("wallet-test-only");return r;}
 private String bearer(String role,AuthenticationSurface surface){var u=users.getUserById(uid(role));return "Bearer "+jwt.generateToken(u.getId(),u.getEmail(),u.getUsername(),List.of(role),surface);}
 @Test void customerAndEmployeeLoginSurfacesAreSeparated()throws Exception{var customer=users.loginCustomer(login("CUSTOMER"));assertEquals("CUSTOMER_PUBLIC",jwt.parseToken(customer.getToken()).get("surface"));assertThrows(BusinessException.class,()->users.loginInternal(login("CUSTOMER")));for(String role:List.of("STAFF","HR_ADMIN","FINANCE","MANAGER","OWNER","SUPER_ADMIN")){assertThrows(BusinessException.class,()->users.loginCustomer(login(role)));assertEquals("PMS_INTERNAL",jwt.parseToken(users.loginInternal(login(role)).getToken()).get("surface"));}mvc.perform(post("/api/public/auth/customer/login").contentType("application/json").content("{\"email\":\""+users.getUserById(uid("CUSTOMER")).getEmail()+"\",\"password\":\"wallet-test-only\"}")).andExpect(status().isOk());mvc.perform(post("/api/internal/auth/login").contentType("application/json").content("{\"email\":\""+users.getUserById(uid("CUSTOMER")).getEmail()+"\",\"password\":\"wallet-test-only\"}")).andExpect(status().isBadRequest());}
 @Test void tokenSurfaceIsEnforcedBothWays()throws Exception{mvc.perform(get("/api/public/customer/bookings/my").header("Authorization",bearer("CUSTOMER",AuthenticationSurface.CUSTOMER_PUBLIC))).andExpect(status().isOk());mvc.perform(get("/api/admin/bookings").header("Authorization",bearer("CUSTOMER",AuthenticationSurface.CUSTOMER_PUBLIC))).andExpect(status().isForbidden());mvc.perform(get("/api/public/customer/bookings/my").header("Authorization",bearer("STAFF",AuthenticationSurface.PMS_INTERNAL))).andExpect(status().isForbidden());mvc.perform(get("/api/admin/bookings").header("Authorization",bearer("STAFF",AuthenticationSurface.PMS_INTERNAL))).andExpect(status().isOk());}
 @Test void missingSurfaceAndUnknownPublicRoutesFailClosed()throws Exception{String secret="isolated-test-only-key-never-use-for-real-authentication-0123456789";var u=users.getUserById(uid("CUSTOMER"));String legacy=Jwts.builder().subject(String.valueOf(u.getId())).claim("email",u.getEmail()).claim("roles",List.of("CUSTOMER")).signWith(Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8))).compact();mvc.perform(get("/api/public/customer/bookings/my").header("Authorization","Bearer "+legacy)).andExpect(status().isUnauthorized());mvc.perform(get("/api/public/not-allowlisted")).andExpect(status().isUnauthorized());}
 @Test void publicCatalogIsAnonymousAndCorsIsOriginScoped()throws Exception{mvc.perform(get("/api/public/catalog/room-types")).andExpect(status().isOk()).andExpect(jsonPath("$.data").isArray());mvc.perform(options("/api/public/catalog/room-types").header("Origin","https://hotel.example.test").header("Access-Control-Request-Method","GET")).andExpect(status().isOk()).andExpect(header().string("Access-Control-Allow-Origin","https://hotel.example.test"));mvc.perform(options("/api/public/catalog/room-types").header("Origin","https://evil.example.test").header("Access-Control-Request-Method","GET")).andExpect(status().isForbidden()).andExpect(header().doesNotExist("Access-Control-Allow-Origin"));}
 @Test void customerOwnershipStillComesFromJwt()throws Exception{long other=uid("OTHER_CUSTOMER");mvc.perform(get("/api/public/customer/bookings/my").param("userId",Long.toString(other)).header("Authorization",bearer("CUSTOMER",AuthenticationSurface.CUSTOMER_PUBLIC))).andExpect(status().isOk());}
}
