package com.johnny.hotel.wallet;

import com.johnny.hotel.stay.*;
import com.johnny.hotel.dto.*;
import com.johnny.hotel.enums.FolioStatus;
import com.johnny.hotel.exception.BusinessException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.*;
import org.springframework.beans.factory.annotation.Autowired;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;

@org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
class StayAdjustmentDevelopmentTest extends FinancialDevelopmentFixture {
    @Autowired StayAdjustmentService stays;
    @Autowired org.flywaydb.core.Flyway flyway;
    void time(int day,int hour,int minute){clock.at(arrival.plusDays(day).atTime(hour,minute));}
    StayAdjustmentRequest adjustment(StayAdjustmentType type,LocalDate end,String key){return StayAdjustmentRequest.builder().type(type).newEnd(end).requestKey(key).reason("Guest stay change").build();}
    StayAdjustment apply(long b,StayAdjustmentType type,LocalDate end,String key){as("MANAGER");return stays.apply(b,adjustment(type,end,key));}
    StayAdjustment extend(long b,int day,String key){return apply(b,StayAdjustmentType.EXTENSION,arrival.plusDays(day),key);}
    StayAdjustment early(long b){return apply(b,StayAdjustmentType.EARLY_CHECKOUT,null,"early_001");}
    StayAdjustment late(long b,String key){return apply(b,StayAdjustmentType.LATE_CHECKOUT,null,key);}
    int financialStatus(long b){return queries.byBooking(b,uid("CUSTOMER")).status();}
    BigDecimal due(long b){return queries.byBooking(b,uid("CUSTOMER")).balanceAmount();}
    void contract(long b){var row=jdbc.queryForMap("SELECT check_in_date,check_out_date,room_type_id,total_price FROM booking WHERE id=?",b);assertEquals(arrival,((java.sql.Date)row.get("check_in_date")).toLocalDate());assertEquals(arrival.plusDays(3),((java.sql.Date)row.get("check_out_date")).toLocalDate());assertEquals(type1,((Number)row.get("room_type_id")).longValue());assertEquals(new BigDecimal("300.00"),row.get("total_price"));assertEquals(3,jdbc.queryForObject("SELECT COUNT(*) FROM booking_nightly_rate WHERE booking_id=? AND rate_amount=100",Integer.class,b));invariantBooking(b);}
    long future(int start,int end,long room){var r=new CreateBookingRequest();r.setRoomTypeId(type1);r.setGuestCount(1);r.setCheckInDate(arrival.plusDays(start));r.setCheckOutDate(arrival.plusDays(end));long id=bookings.createBooking(r,uid("OTHER_CUSTOMER")).getId();bookingIds.add(id);var a=new ApproveBookingRequest();a.setAssignedRoomId(room);bookings.approveBooking(id,a,uid("MANAGER"));return id;}
    long pendingFuture(int start,int end){var r=new CreateBookingRequest();r.setRoomTypeId(type1);r.setGuestCount(1);r.setCheckInDate(arrival.plusDays(start));r.setCheckOutDate(arrival.plusDays(end));long id=bookings.createBooking(r,uid("OTHER_CUSTOMER")).getId();bookingIds.add(id);return id;}
    void approveFuture(long b,long room){var a=new ApproveBookingRequest();a.setAssignedRoomId(room);bookings.approveBooking(b,a,uid("MANAGER"));}
    void finish(long b){var amount=due(b);if(amount.signum()>0)pay(b,amount.toPlainString());checkout(b);contract(b);}
    @Test void migrationValidateAndGeneratedFinancialStatus()throws Exception{flyway.validate();assertEquals(1,jdbc.queryForObject("SELECT success FROM flyway_schema_history WHERE version='12'",Integer.class));long b=stay();assertEquals(0,financialStatus(b));assertThrows(Exception.class,()->jdbc.update("UPDATE folio SET status=1 WHERE id=?",folio(b)));pay(b,"300");assertEquals(1,financialStatus(b));assertNull(queries.byBooking(b,uid("CUSTOMER")).closedTime());pay(b,"100");assertEquals(2,financialStatus(b));var r=requestRefund(b,"100","refund_01");as("MANAGER");refunds.confirm(folio(b),r.id(),process("process_01"));assertEquals(1,financialStatus(b));mvc.perform(get("/api/bookings/"+b+"/folio").with(authentication(auth("CUSTOMER")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value(1));}
    @Test void extensionLocksOnlyNewNightsAndNeverRepricesContract(){long b=stay();jdbc.update("UPDATE room_type SET base_price=120 WHERE id=?",type1);jdbc.update("INSERT INTO room_rate(room_type_id,rate_date,price,rate_source) VALUES(?,?,220,'MANUAL')",type1,arrival.plusDays(3));var a=extend(b,5,"extend_01");assertEquals(new BigDecimal("640.00"),due(b));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM stay_extension_nightly_rate WHERE adjustment_id=?",Integer.class,a.getId()));jdbc.update("UPDATE room_rate SET price=999 WHERE room_type_id=?",type1);assertEquals(a.getId(),extend(b,5,"extend_01").getId());assertThrows(BusinessException.class,()->extend(b,6,"extend_01"));time(5,12,0);finish(b);}
    @Test void extensionConflictRejectsWithoutAutomaticRoomChange(){long b=stay();long next=future(3,5,room1);assertThrows(BusinessException.class,()->extend(b,5,"extend_01"));assertEquals(room1,jdbc.queryForObject("SELECT assigned_room_id FROM booking WHERE id=?",Long.class,b));assertEquals(room1,jdbc.queryForObject("SELECT assigned_room_id FROM booking WHERE id=?",Long.class,next));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_adjustment WHERE booking_id=?",Integer.class,b));contract(b);}
    @Test void explicitRoomChangeOnDepartureDayThenExtension(){long b=stay();future(3,5,room1);time(3,12,0);var r=new ChangeRoomDuringStayRequest();r.setNewRoomId(room2);r.setReason("Move before extension");bookings.changeRoomDuringStay(b,r,uid("MANAGER"));extend(b,5,"extend_01");time(5,12,0);finish(b);}
    @ParameterizedTest @ValueSource(booleans={true,false}) void extensionAndRoomChangeBothOrders(boolean extensionFirst){long b=stay();if(extensionFirst)extend(b,5,"extend_01");time(extensionFirst?4:1,12,0);var r=new ChangeRoomDuringStayRequest();r.setNewRoomId(room3);r.setReason("Requested move");bookings.changeRoomDuringStay(b,r,uid("MANAGER"));if(!extensionFirst)extend(b,5,"extend_01");time(5,12,0);finish(b);}
    @ParameterizedTest @ValueSource(booleans={true,false}) void earlyDepartureUsesAppendOnlyReversalAndPaymentOrRefund(boolean prepaid){long b=stay();if(prepaid)pay(b,"300");var original=jdbc.queryForList("SELECT id,amount FROM folio_item WHERE folio_id=? ORDER BY id",folio(b));time(1,12,0);var a=early(b);assertEquals(a.getId(),early(b).getId());assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=? AND item_type='EARLY_CHECKOUT_REVERSAL'",Integer.class,folio(b)));assertEquals(original,jdbc.queryForList("SELECT id,amount FROM folio_item WHERE folio_id=? AND item_type='ROOM_CHARGE' ORDER BY id",folio(b)));if(prepaid){assertEquals(2,financialStatus(b));assertThrows(BusinessException.class,()->checkout(b));var r=requestRefund(b,"200","refund_01");as("MANAGER");refunds.confirm(folio(b),r.id(),process("process_01"));assertEquals(new BigDecimal("200.00"),wallets.find(wid("CUSTOMER")).getBalance());}else{assertEquals(new BigDecimal("100.00"),due(b));assertThrows(BusinessException.class,()->checkout(b));pay(b,"100");}checkout(b);assertEquals(arrival.plusDays(1).atTime(12,0),jdbc.queryForObject("SELECT end_time FROM booking_room_assignment WHERE booking_id=?",LocalDateTime.class,b));contract(b);}
    @ParameterizedTest @ValueSource(strings={"12:00","12:30","12:31","15:29","17:59"}) void lateTimeBoundaries(String text){long b=stay();LocalTime t=LocalTime.parse(text);time(3,t.getHour(),t.getMinute());late(b,"late_001");assertEquals(new BigDecimal(t.isAfter(LocalTime.of(12,30))?"350.00":"300.00"),due(b));finish(b);}
    @ParameterizedTest @ValueSource(strings={"18:00","18:01","23:59"}) void cutoffRequiresExplicitExtension(String text){long b=stay();LocalTime t=LocalTime.parse(text);time(3,t.getHour(),t.getMinute());assertThrows(BusinessException.class,()->late(b,"late_001"));assertThrows(BusinessException.class,()->checkout(b));extend(b,4,"extend_01");time(4,12,0);finish(b);}
    @Test void conflictAtNormalCheckinUsesOnlyFullEffectiveRate(){long b=stay();long next=future(3,5,room1);jdbc.update("INSERT INTO room_rate(room_type_id,rate_date,price,rate_source) VALUES(?,?,180,'MANUAL')",type1,arrival.plusDays(3));time(3,15,30);var a=late(b,"late_001");assertEquals(next,a.getConflictBookingId());assertEquals(new BigDecimal("480.00"),due(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=? AND item_type='LATE_CHECKOUT_FEE'",Integer.class,folio(b)));assertEquals(room1,jdbc.queryForObject("SELECT assigned_room_id FROM booking WHERE id=?",Long.class,next));finish(b);rooms.setRoomAvailable(room1);bookings.checkIn(next,uid("MANAGER"));}
    @Test void lateFeeUpgradeReversesOldFeeWithoutDoubleCharging(){long b=stay();future(3,5,room1);time(3,13,0);late(b,"late_001");time(3,15,30);assertThrows(BusinessException.class,()->checkout(b));late(b,"late_002");assertEquals(new BigDecimal("400.00"),due(b));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM folio_item WHERE folio_id=? AND item_type='STAY_FEE_REVERSAL'",Integer.class,folio(b)));finish(b);}
    @Test void extensionSupersedesLateFee(){long b=stay();time(3,13,0);late(b,"late_001");time(3,18,0);extend(b,4,"extend_01");assertEquals(new BigDecimal("400.00"),due(b));time(4,12,0);finish(b);}
    @Test void finalizerNeverGuessesAdjustments(){long b=stay();pay(b,"300");time(1,12,0);assertThrows(BusinessException.class,()->checkout(b));time(3,13,0);assertThrows(BusinessException.class,()->checkout(b));time(4,12,0);assertThrows(BusinessException.class,()->checkout(b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_adjustment WHERE booking_id=?",Integer.class,b));contract(b);}
    @ParameterizedTest @ValueSource(strings={"CUSTOMER","HR_ADMIN","STAFF","MANAGER","OWNER","SUPER_ADMIN"}) void serviceAndHttpPermissions(String role)throws Exception{long b=stay();as(role);boolean allowed=Set.of("STAFF","MANAGER","OWNER","SUPER_ADMIN").contains(role);if(allowed)stays.apply(b,adjustment(StayAdjustmentType.EXTENSION,arrival.plusDays(4),"extend_01"));else assertThrows(org.springframework.security.access.AccessDeniedException.class,()->stays.apply(b,adjustment(StayAdjustmentType.EXTENSION,arrival.plusDays(4),"extend_01")));mvc.perform(get("/api/admin/bookings/"+b+"/stay-adjustments").with(authentication(auth(role)))).andExpect(status().is(allowed?200:403));contract(b);}
    @ParameterizedTest @ValueSource(strings={"StayAdjustmentMapper.insert","StayAdjustmentMapper.insertNight","FolioItemMapper.insert","FolioMapper.updateFinancialSummary","SysAuditLogMapper.insert"}) void extensionFailuresRollbackEverything(String statement){long b=stay();gate.arm(Thread.currentThread().getName(),statement,true);assertThrows(Exception.class,()->extend(b,5,"extend_01"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_adjustment WHERE booking_id=?",Integer.class,b));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_extension_nightly_rate WHERE booking_id=?",Integer.class,b));assertEquals(new BigDecimal("300.00"),due(b));contract(b);}
    @Test void duplicateConcurrentExtensionPostsOnce(){long b=stay();assertNull(serialized("StayAdjustmentMapper.insert",()->extend(b,5,"extend_01"),()->extend(b,5,"extend_01")));assertEquals(new BigDecimal("500.00"),due(b));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM stay_adjustment WHERE booking_id=?",Integer.class,b));contract(b);}
    @ParameterizedTest @ValueSource(booleans={true,false}) void extensionVersusFutureApproval(boolean extensionFirst){long b=stay();long next=pendingFuture(3,5);if(extensionFirst)assertInstanceOf(BusinessException.class,serialized("StayAdjustmentMapper.insert",()->extend(b,5,"extend_01"),()->approveFuture(next,room1)));else assertInstanceOf(BusinessException.class,serialized("BookingMapper.approveBooking",()->approveFuture(next,room1),()->extend(b,5,"extend_01")));contract(b);}
    @Test void extensionVersusRoomChangeSerializes(){long b=stay();var r=new ChangeRoomDuringStayRequest();r.setNewRoomId(room3);r.setReason("Concurrent room change");assertNull(serialized("StayAdjustmentMapper.insert",()->extend(b,5,"extend_01"),()->bookings.changeRoomDuringStay(b,r,uid("MANAGER"))));time(5,12,0);finish(b);}
    @Test void earlyAdjustmentVersusPayment(){long b=stay();time(1,12,0);assertNull(serialized("StayAdjustmentMapper.insert",()->early(b),()->pay(b,"100")));checkout(b);contract(b);}
    @Test void lateAdjustmentVersusConflictingCheckin(){long b=stay();long next=future(3,5,room1);time(3,15,30);assertInstanceOf(BusinessException.class,serialized("StayAdjustmentMapper.insert",()->late(b,"late_001"),()->bookings.checkIn(next,uid("MANAGER"))));assertEquals(1,bookingState(next));contract(b);}
    @Test void adjustmentVersusCheckout(){long b=stay();pay(b,"300");time(3,12,0);assertInstanceOf(BusinessException.class,serialized("StayAdjustmentMapper.insert",()->extend(b,4,"extend_01"),()->checkout(b)));assertEquals(2,bookingState(b));contract(b);}
    @Test void checkedOutContractAndAdjustmentRetryRemainImmutable(){long b=stay();extend(b,4,"extend_01");time(4,12,0);finish(b);assertEquals(1,stays.list(b).size());assertNotNull(extend(b,4,"extend_01"));assertThrows(BusinessException.class,()->extend(b,5,"extend_02"));assertThrows(Exception.class,()->jdbc.update("UPDATE booking SET check_out_date=DATE_ADD(check_out_date,INTERVAL 1 DAY) WHERE id=?",b));contract(b);}

    @Test void realHttpJwtCreationAndRetry()throws Exception{long b=stay();String token=jwt.generateToken(uid("MANAGER"),"stay@example.test","stay-test",List.of("MANAGER"));String body="{\"type\":\"EXTENSION\",\"newEnd\":\"2026-10-05\",\"requestKey\":\"http_0001\",\"reason\":\"Guest extension\"}";var request=java.net.http.HttpRequest.newBuilder(java.net.URI.create("http://localhost:"+port+"/api/admin/bookings/"+b+"/stay-adjustments")).header("Authorization","Bearer "+token).header("Content-Type","application/json").POST(java.net.http.HttpRequest.BodyPublishers.ofString(body)).build();var client=java.net.http.HttpClient.newHttpClient();assertEquals(200,client.send(request,java.net.http.HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(200,client.send(request,java.net.http.HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(new BigDecimal("400.00"),due(b));contract(b);}
    @ParameterizedTest @ValueSource(strings={"{}","{\"type\":\"EXTENSION\",\"requestKey\":\"x\",\"reason\":\"test\"}","{\"type\":\"UNKNOWN\",\"requestKey\":\"request_01\",\"reason\":\"test\"}"})
    void invalidHttpRequestsHaveNoSideEffects(String body)throws Exception{long b=stay();mvc.perform(post("/api/admin/bookings/"+b+"/stay-adjustments").with(authentication(auth("STAFF"))).contentType("application/json").content(body)).andExpect(status().isBadRequest());assertEquals(new BigDecimal("300.00"),due(b));}
    @ParameterizedTest @ValueSource(strings={"EXTENSION","EARLY_CHECKOUT","LATE_CHECKOUT"}) void missingAdjustmentLedgerBlocksClosing(String type){long b=stay();switch(type){case "EXTENSION"-> {extend(b,4,"extend_01");jdbc.update("DELETE FROM stay_extension_nightly_rate WHERE booking_id=?",b);time(4,12,0);}case "EARLY_CHECKOUT"->{time(1,12,0);early(b);jdbc.update("DELETE FROM folio_item WHERE folio_id=? AND item_type='EARLY_CHECKOUT_REVERSAL'",folio(b));}default->{time(3,13,0);late(b,"late_001");jdbc.update("DELETE FROM folio_item WHERE folio_id=? AND item_type='LATE_CHECKOUT_FEE'",folio(b));}}financial.recalculateSummary(b);pay(b,due(b).toPlainString());assertThrows(BusinessException.class,()->checkout(b));assertNull(queries.byBooking(b,uid("CUSTOMER")).closedTime());}
    @Test void extensionSnapshotAndAdjustmentAreImmutable(){long b=stay();var a=extend(b,4,"extend_01");assertThrows(Exception.class,()->jdbc.update("UPDATE stay_adjustment SET new_end=DATE_ADD(new_end,INTERVAL 1 DAY) WHERE id=?",a.getId()));assertThrows(Exception.class,()->jdbc.update("UPDATE stay_extension_nightly_rate SET rate_amount=1 WHERE adjustment_id=?",a.getId()));contract(b);}
    @Test void expensesOnExtendedNightRemainInSettlement(){long b=stay();extend(b,5,"extend_01");time(4,12,0);as("MANAGER");var req=expense("20");req.setBusinessDate(arrival.plusDays(4));var fee=expenses.register(folio(b),req);expenses.confirm(folio(b),fee.id());assertEquals(new BigDecimal("520.00"),due(b));time(5,12,0);finish(b);}
    @Test void earlyAdjustmentVersusRefundConfirmation(){long b=stay();pay(b,"400");var r=requestRefund(b,"100","refund_01");time(1,12,0);assertNull(serialized("StayAdjustmentMapper.insert",()->early(b),()->refunds.confirm(folio(b),r.id(),process("process_01"))));assertEquals(new BigDecimal("-200.00"),due(b));contract(b);}
    @Test void checkoutFirstMakesLaterAdjustmentFail(){long b=stay();pay(b,"300");time(3,12,0);assertInstanceOf(BusinessException.class,serialized("FolioMapper.close",()->checkout(b),()->extend(b,4,"extend_01")));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM stay_adjustment WHERE booking_id=?",Integer.class,b));contract(b);}
    @Test void futureReservationsAlsoSerializeWithEachOther(){long a=pendingFuture(3,5),b=pendingFuture(3,5);assertInstanceOf(BusinessException.class,serialized("BookingMapper.approveBooking",()->approveFuture(a,room1),()->approveFuture(b,room1)));assertEquals(1,bookingState(a));assertEquals(0,bookingState(b));}
    @Test void futureReservationCanBeRelocatedWhileCurrentGuestStays(){long b=stay();long next=future(3,5,room1);var request=new com.johnny.hotel.dto.ReassignRoomRequest();request.setNewRoomId(room2);request.setReason("Manual relocation");bookings.reassignRoom(next,request,uid("MANAGER"));assertEquals(4,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));extend(b,5,"extend_01");contract(b);}

    @Test void overdueOccupiedNightRequiresExplicitExtension(){long b=stay();time(4,12,0);assertThrows(BusinessException.class,()->checkout(b));extend(b,4,"extend_01");assertEquals(new BigDecimal("400.00"),due(b));finish(b);}
    @Test void confirmedConflictFeeCannotBeRepricedByNewRate(){long b=stay();future(3,5,room1);jdbc.update("INSERT INTO room_rate(room_type_id,rate_date,price,rate_source) VALUES(?,?,100,'MANUAL')",type1,arrival.plusDays(3));time(3,15,30);var a=late(b,"late_001");assertTrue(a.getOperationalNotice().contains("manual relocation"));jdbc.update("UPDATE room_rate SET price=300 WHERE room_type_id=?",type1);assertThrows(BusinessException.class,()->late(b,"late_002"));assertEquals(new BigDecimal("400.00"),due(b));finish(b);}
    @Test void extensionUsesFreshPriceDespiteOuterRepeatableReadSnapshot(){long b=stay();jdbc.update("INSERT INTO room_rate(room_type_id,rate_date,price,rate_source) VALUES(?,?,100,'MANUAL')",type1,arrival.plusDays(3));var pool=java.util.concurrent.Executors.newSingleThreadExecutor();try{new org.springframework.transaction.support.TransactionTemplate(txManager).executeWithoutResult(s->{assertEquals(new BigDecimal("100.00"),jdbc.queryForObject("SELECT price FROM room_rate WHERE room_type_id=?",BigDecimal.class,type1));assertNull(result(worker(pool,"rate-writer",()->jdbc.update("UPDATE room_rate SET price=200 WHERE room_type_id=?",type1))));extend(b,4,"extend_01");});}finally{pool.shutdownNow();}assertEquals(new BigDecimal("500.00"),due(b));time(4,12,0);finish(b);}
    @Test void cleaningRejectsOuterSnapshotEvenWithFutureReservation(){long b=stay();future(3,5,room1);time(3,12,0);finish(b);assertThrows(BusinessException.class,()->new org.springframework.transaction.support.TransactionTemplate(txManager).executeWithoutResult(s->rooms.setRoomAvailable(room1)));rooms.setRoomAvailable(room1);assertEquals(1,jdbc.queryForObject("SELECT status FROM room WHERE id=?",Integer.class,room1));}
}
