package com.johnny.hotel.pricing;
import com.johnny.hotel.common.Result;import com.johnny.hotel.entity.SysAuditLog;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.mapper.*;import com.johnny.hotel.pagination.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;import static com.johnny.hotel.service.support.BillingRules.*;
@Service @RequiredArgsConstructor public class DynamicPricingService{
 private final PricingMapper db;private final PricingAccess access;private final SysAuditLogMapper audits;private final PaginationSupport pages;
 public PolicyView active(Long actor){access.read(actor);var p=db.active();return p==null?null:view(p);}
 public PolicyView get(Long id,Long actor){access.read(actor);var p=db.policy(id);require(p!=null,"Pricing policy does not exist");return view(p);}
 public PageResult<DynamicPolicy> history(Integer page,Integer size,Long actor){access.read(actor);var w=pages.window(page,size,false);int limit=pages.limit(w);return pages.result(w,limit==0?List.of():db.policies(w.offset(),limit),db.policyCount());}
 @Transactional public PolicyView create(PricingRequests.PolicySave r,Long actor){access.policyWrite(actor);db.lockControl();var p=DynamicPolicy.builder().versionNo(db.nextVersion()).name(r.getName().trim()).status(0).minimumMultiplier(r.getMinimumMultiplier()).maximumMultiplier(r.getMaximumMultiplier()).createdBy(actor).build();one(db.insertPolicy(p));replace(p,r);audit(actor,"DYNAMIC_POLICY_DRAFT","Policy "+p.getId()+" V"+p.getVersionNo());return view(p);}
 @Transactional public PolicyView save(Long id,PricingRequests.PolicySave r,Long actor){access.policyWrite(actor);db.lockControl();var p=draft(id);p.setName(r.getName().trim());p.setMinimumMultiplier(r.getMinimumMultiplier());p.setMaximumMultiplier(r.getMaximumMultiplier());one(db.updateDraft(p));db.deleteCells(id);db.deleteOccupancy(id);db.deleteWindows(id);replace(p,r);audit(actor,"DYNAMIC_POLICY_EDIT","Policy "+id);return view(p);}
 @Transactional public PolicyView copyActive(Long actor){access.policyWrite(actor);var a=db.active();require(a!=null,"No active policy to copy");var request=PricingRequests.PolicySave.builder().name(a.getName()+" copy").minimumMultiplier(a.getMinimumMultiplier()).maximumMultiplier(a.getMaximumMultiplier()).occupancyBands(db.occupancy(a.getId()).stream().map(x->PricingRequests.Occupancy.builder().label(x.getLabel()).lowerInclusive(x.getLowerInclusive()).upperExclusive(x.getUpperExclusive()).build()).toList()).bookingWindowBands(db.windows(a.getId()).stream().map(x->PricingRequests.Window.builder().label(x.getLabel()).minDays(x.getMinDays()).maxDays(x.getMaxDays()).build()).toList()).build();var os=db.occupancy(a.getId());var ws=db.windows(a.getId());var cells=db.cells(a.getId());request.setCells(cells.stream().map(c->PricingRequests.Cell.builder().occupancyIndex(index(os,c.getOccupancyBandId())).windowIndex(index(ws,c.getBookingWindowBandId())).adjustmentPercent(c.getAdjustmentPercent()).build()).toList());return create(request,actor);}
 @Transactional public PolicyView activate(Long id,Long actor){access.policyWrite(actor);db.lockControl();var p=draft(id);var v=view(p);require(v.isValid(),String.join("; ",v.getValidationErrors()));db.retireActive();one(db.activate(id,actor));audit(actor,"DYNAMIC_POLICY_ACTIVATE","Policy "+id);return view(db.policy(id));}
 @Transactional public void disable(Long actor){access.policyWrite(actor);db.lockControl();db.retireActive();audit(actor,"DYNAMIC_POLICY_DISABLE","Dynamic pricing disabled");}
 @Transactional public void delete(Long id,Long actor){access.policyWrite(actor);db.lockControl();draft(id);db.deleteCells(id);db.deleteOccupancy(id);db.deleteWindows(id);one(db.deleteDraft(id));audit(actor,"DYNAMIC_POLICY_DELETE","Policy "+id);}
 public PolicyView validate(Long id,Long actor){return get(id,actor);}
 private void replace(DynamicPolicy p,PricingRequests.PolicySave r){require(r.getMaximumMultiplier().compareTo(r.getMinimumMultiplier())>=0,"Maximum multiplier must not be below minimum");var os=new ArrayList<OccupancyBand>();for(int i=0;i<r.getOccupancyBands().size();i++){var x=r.getOccupancyBands().get(i);var b=OccupancyBand.builder().policyId(p.getId()).label(x.getLabel().trim()).lowerInclusive(x.getLowerInclusive()).upperExclusive(x.getUpperExclusive()).sortOrder(i+1).build();one(db.insertOccupancy(b));os.add(b);}var ws=new ArrayList<BookingWindowBand>();for(int i=0;i<r.getBookingWindowBands().size();i++){var x=r.getBookingWindowBands().get(i);var b=BookingWindowBand.builder().policyId(p.getId()).label(x.getLabel().trim()).minDays(x.getMinDays()).maxDays(x.getMaxDays()).sortOrder(i+1).build();one(db.insertWindow(b));ws.add(b);}for(var x:r.getCells()){require(x.getOccupancyIndex()>=0&&x.getOccupancyIndex()<os.size()&&x.getWindowIndex()>=0&&x.getWindowIndex()<ws.size(),"Matrix cell index is invalid");one(db.insertCell(DynamicPricingCell.builder().policyId(p.getId()).occupancyBandId(os.get(x.getOccupancyIndex()).getId()).bookingWindowBandId(ws.get(x.getWindowIndex()).getId()).adjustmentPercent(x.getAdjustmentPercent()).build()));}}
 private PolicyView view(DynamicPolicy p){var os=db.occupancy(p.getId());var ws=db.windows(p.getId());var cs=db.cells(p.getId());var errors=validate(p,os,ws,cs);return PolicyView.builder().policy(p).occupancyBands(os).bookingWindowBands(ws).cells(cs).valid(errors.isEmpty()).validationErrors(errors).build();}
 private List<String> validate(DynamicPolicy p,List<OccupancyBand> os,List<BookingWindowBand> ws,List<DynamicPricingCell> cs){var e=new ArrayList<String>();int next=0;for(var b:os){if(b.getLowerInclusive()!=next||b.getUpperExclusive()<=b.getLowerInclusive())e.add("Occupancy bands must be contiguous");next=b.getUpperExclusive();}if(next!=101)e.add("Occupancy bands must cover 0 through 100");next=0;for(int i=0;i<ws.size();i++){var b=ws.get(i);if(b.getMinDays()!=next)e.add("Booking window bands must be contiguous");if(i==ws.size()-1){if(b.getMaxDays()!=null)e.add("Last booking window must be open-ended");}else if(b.getMaxDays()==null||b.getMaxDays()<b.getMinDays())e.add("Only last booking window may be open-ended");else next=b.getMaxDays()+1;}if(cs.size()!=os.size()*ws.size())e.add("Pricing matrix must contain exactly one cell for every band combination");return e.stream().distinct().toList();}
 private DynamicPolicy draft(Long id){var p=db.policy(id);require(p!=null&&p.getStatus()==0,"Only draft policy can be changed");return p;}private int index(List<? extends Object> xs,Long id){for(int i=0;i<xs.size();i++){Long x=xs.get(i) instanceof OccupancyBand o?o.getId():((BookingWindowBand)xs.get(i)).getId();if(x.equals(id))return i;}throw new BusinessException("Policy matrix reference is invalid");}private void audit(Long a,String action,String d){one(audits.insert(SysAuditLog.builder().operatorId(a).action(action).detail(d).build()));}
}
