package com.johnny.hotel.pricing;
import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import com.johnny.hotel.service.PricingService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.time.LocalDate;import java.util.List;
@RestController @RequiredArgsConstructor public class PricingController{private final DynamicPricingService policies;private final ManualRateService overrides;private final PricingService engine;private Long actor(Authentication a){return(Long)a.getDetails();}
 @GetMapping("/api/admin/pricing/policies/active") @PreAuthorize("hasAnyRole('MANAGER','FINANCE','OWNER','SUPER_ADMIN')") public Result<PolicyView> active(Authentication a){return Result.success(policies.active(actor(a)));}
 @GetMapping("/api/admin/pricing/policies/{id}") @PreAuthorize("hasAnyRole('MANAGER','FINANCE','OWNER','SUPER_ADMIN')") public Result<PolicyView> policy(@PathVariable Long id,Authentication a){return Result.success(policies.get(id,actor(a)));}
 @GetMapping("/api/admin/pricing/policies") @PreAuthorize("hasAnyRole('MANAGER','FINANCE','OWNER','SUPER_ADMIN')") public Result<PageResult<DynamicPolicy>> policies(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize,Authentication a){return Result.success(policies.history(page,pageSize,actor(a)));}
 @PostMapping("/api/admin/pricing/policies") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<PolicyView> create(@Valid @RequestBody PricingRequests.PolicySave r,Authentication a){return Result.success(policies.create(r,actor(a)));}
 @PutMapping("/api/admin/pricing/policies/{id}") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<PolicyView> save(@PathVariable Long id,@Valid @RequestBody PricingRequests.PolicySave r,Authentication a){return Result.success(policies.save(id,r,actor(a)));}
 @PostMapping("/api/admin/pricing/policies/copy-active") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<PolicyView> copy(Authentication a){return Result.success(policies.copyActive(actor(a)));}
 @PostMapping("/api/admin/pricing/policies/{id}/activate") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<PolicyView> activate(@PathVariable Long id,Authentication a){return Result.success(policies.activate(id,actor(a)));}
 @PostMapping("/api/admin/pricing/policies/disable") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<Void> disable(Authentication a){policies.disable(actor(a));return Result.success();}
 @DeleteMapping("/api/admin/pricing/policies/{id}") @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')") public Result<Void> delete(@PathVariable Long id,Authentication a){policies.delete(id,actor(a));return Result.success();}
 @GetMapping("/api/admin/pricing/overrides") @PreAuthorize("hasAnyRole('STAFF','MANAGER','FINANCE','OWNER','SUPER_ADMIN')") public Result<List<ManualRateOverride>> range(@RequestParam Long roomTypeId,@RequestParam LocalDate start,@RequestParam LocalDate end,Authentication a){return Result.success(overrides.range(roomTypeId,start,end,actor(a)));}
 @PutMapping("/api/admin/pricing/overrides") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<List<ManualRateOverride>> saveOverride(@Valid @RequestBody PricingRequests.Override r,Authentication a){return Result.success(overrides.save(r,actor(a)));}
 @DeleteMapping("/api/admin/pricing/overrides/{type}/{date}") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<Void> cancel(@PathVariable Long type,@PathVariable LocalDate date,@RequestParam String reason,Authentication a){overrides.cancel(type,date,reason,actor(a));return Result.success();}
 @GetMapping("/api/admin/pricing/preview") @PreAuthorize("hasAnyRole('MANAGER','FINANCE','OWNER','SUPER_ADMIN')") public Result<List<PricingDecision>> preview(@RequestParam Long roomTypeId,@RequestParam LocalDate start,@RequestParam LocalDate end){return Result.success(engine.explain(roomTypeId,start,end));}
}
