package com.johnny.hotel.controller;
import com.johnny.hotel.common.Result;import com.johnny.hotel.mapper.RoomMapper;import com.johnny.hotel.service.*;import com.johnny.hotel.stay.RoomConflictReader;import lombok.RequiredArgsConstructor;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
@RestController @RequiredArgsConstructor @RequestMapping("/api/public/catalog") public class PublicCatalogController {
 private final RoomTypeService roomTypes;private final PricingService pricing;private final RoomMapper rooms;private final RoomConflictReader conflicts;
 public record PublicRoomType(Long id,String name,String description,BigDecimal basePrice,Integer capacity){}
 public record Availability(Long roomTypeId,LocalDate checkInDate,LocalDate checkOutDate,boolean available,int availableRoomCount){}
 public record PublicNightlyRate(LocalDate date,BigDecimal price){} public record PublicQuote(Long roomTypeId,LocalDate checkInDate,LocalDate checkOutDate,int nights,List<PublicNightlyRate> nightlyRates,BigDecimal totalPrice){}
 @GetMapping("/room-types")public Result<List<PublicRoomType>> types(){return Result.success(roomTypes.getRoomTypes().stream().filter(t->Integer.valueOf(1).equals(t.getStatus())).map(t->new PublicRoomType(t.getId(),t.getTypeName(),t.getDescription(),t.getBasePrice(),t.getCapacity())).toList());}
 @GetMapping("/quote")public Result<PublicQuote> quote(@RequestParam Long roomTypeId,@RequestParam LocalDate checkInDate,@RequestParam LocalDate checkOutDate){var q=pricing.quoteRoomType(roomTypeId,checkInDate,checkOutDate);return Result.success(new PublicQuote(q.getRoomTypeId(),q.getCheckInDate(),q.getCheckOutDate(),q.getNights(),q.getNightlyRates().stream().map(n->new PublicNightlyRate(n.getStayDate(),n.getPrice())).toList(),q.getTotalPrice()));}
 @GetMapping("/availability")public Result<Availability> availability(@RequestParam Long roomTypeId,@RequestParam LocalDate checkInDate,@RequestParam LocalDate checkOutDate){if(checkInDate==null||checkOutDate==null||!checkInDate.isBefore(checkOutDate))throw new com.johnny.hotel.exception.BusinessException("Invalid stay dates");int count=(int)rooms.sellableCandidates(roomTypeId).stream().filter(r->conflicts.overlapping(r.getId(),null,checkInDate,checkOutDate).isEmpty()).count();return Result.success(new Availability(roomTypeId,checkInDate,checkOutDate,count>0,count));}
}
