package com.johnny.hotel.invoice;
import org.apache.ibatis.annotations.*;import java.util.*;
@Mapper public interface FinanceReadMapper{
 @Select("SELECT 'bookings' domain,id,user_id user_id,reserved_room_id room_id,CAST(status AS CHAR) status,reservation_source label,create_time occurred_at,update_time updated_at FROM booking ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> bookings(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'assignments' domain,id,stay_id,room_id,CASE WHEN end_time IS NULL THEN 'ACTIVE' ELSE 'ENDED' END status,NULL label,start_time occurred_at,end_time updated_at FROM stay_room_assignment ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> assignments(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'rooms' domain,id,CAST(status AS CHAR) status,room_number label,update_time updated_at FROM room ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> rooms(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'stays' domain,id,booking_id,CAST(status AS CHAR) status,NULL label,actual_check_in_time occurred_at,update_time updated_at FROM stay ORDER BY actual_check_in_time DESC,id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> stays(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'guests' domain,id,linked_user_id user_id,CAST(status AS CHAR) status,CONCAT(first_name,' ',last_name) label,create_time occurred_at,update_time updated_at FROM guest_profile ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> guests(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'cleaning' domain,id,stay_id,room_id,task_id,CAST(cleaning_type AS CHAR) status,NULL label,completed_time occurred_at,create_time updated_at FROM cleaning_record ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> cleaning(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'inspections' domain,id,stay_id,room_id,followup_task_id task_id,CAST(status AS CHAR) status,NULL label,inspected_time occurred_at,update_time updated_at FROM housekeeping_inspection ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> inspections(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'work-orders' domain,id,room_id,task_id,CAST(status AS CHAR) status,damage_type label,create_time occurred_at,update_time updated_at FROM room_work_order ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> workOrders(@Param("offset")int offset,@Param("size")int size);
 @Select("SELECT 'turnovers' domain,id,stay_id,room_id,task_id,CAST(status AS CHAR) status,NULL label,create_time occurred_at,update_time updated_at FROM room_turnover_task ORDER BY id DESC LIMIT #{offset},#{size}")List<FinanceOperationalRecord> turnovers(@Param("offset")int offset,@Param("size")int size);
 @Select("<script>SELECT COUNT(*) FROM <choose><when test=\"table=='booking'\">booking</when><when test=\"table=='stay_room_assignment'\">stay_room_assignment</when><when test=\"table=='room'\">room</when><when test=\"table=='stay'\">stay</when><when test=\"table=='guest_profile'\">guest_profile</when><when test=\"table=='cleaning_record'\">cleaning_record</when><when test=\"table=='housekeeping_inspection'\">housekeeping_inspection</when><when test=\"table=='room_work_order'\">room_work_order</when><otherwise>room_turnover_task</otherwise></choose></script>")long count(@Param("table")String table);
}
