CREATE TABLE room_work_order (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 task_id BIGINT NOT NULL,
 room_id BIGINT NOT NULL,
 reported_by BIGINT NOT NULL,
 request_key VARCHAR(100) NOT NULL,
 damage_type VARCHAR(80) NOT NULL,
 description VARCHAR(500) NOT NULL,
 severity TINYINT NOT NULL,
 affects_sellability TINYINT NOT NULL,
 status TINYINT NOT NULL DEFAULT 0,
 estimated_cost DECIMAL(12,2) NULL,
 actual_cost DECIMAL(12,2) NULL,
 resolved_time DATETIME(6) NULL,
 cancelled_time DATETIME(6) NULL,
 create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 update_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_room_work_order_task(task_id),
 UNIQUE KEY uk_room_work_order_request(reported_by,request_key),
 KEY idx_room_work_order_room_status(room_id,status),
 CONSTRAINT fk_room_work_order_task FOREIGN KEY(task_id) REFERENCES hotel_task(id),
 CONSTRAINT fk_room_work_order_room FOREIGN KEY(room_id) REFERENCES room(id),
 CONSTRAINT fk_room_work_order_reporter FOREIGN KEY(reported_by) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
