CREATE TABLE damage_assessment (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 room_id BIGINT NOT NULL, booking_id BIGINT NOT NULL, assignment_id BIGINT NOT NULL, folio_id BIGINT NOT NULL,
 source_type TINYINT NOT NULL, source_id BIGINT NOT NULL,
 damage_description VARCHAR(500) NOT NULL,
 responsibility TINYINT NOT NULL DEFAULT 0,
 assessed_charge DECIMAL(12,2) NULL,
 reason VARCHAR(500) NULL,
 status TINYINT NOT NULL DEFAULT 0,
 folio_item_id BIGINT NULL,
 request_key VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 reported_by BIGINT NOT NULL, assessed_by BIGINT NULL,
 assessed_time DATETIME(6) NULL,
 create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 update_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_damage_source(source_type,source_id),
 UNIQUE KEY uk_damage_request(reported_by,request_key),
 UNIQUE KEY uk_damage_ledger(folio_item_id),
 KEY idx_damage_folio_status(folio_id,status,id),
 KEY idx_damage_booking_time(booking_id,create_time,id),
 KEY idx_damage_room_time(room_id,create_time,id),
 CONSTRAINT fk_damage_room FOREIGN KEY(room_id) REFERENCES room(id),
 CONSTRAINT fk_damage_booking FOREIGN KEY(booking_id) REFERENCES booking(id),
 CONSTRAINT fk_damage_assignment FOREIGN KEY(assignment_id) REFERENCES booking_room_assignment(id),
 CONSTRAINT fk_damage_folio FOREIGN KEY(folio_id) REFERENCES folio(id),
 CONSTRAINT fk_damage_ledger FOREIGN KEY(folio_item_id) REFERENCES folio_item(id),
 CONSTRAINT fk_damage_reporter FOREIGN KEY(reported_by) REFERENCES sys_user(id),
 CONSTRAINT fk_damage_assessor FOREIGN KEY(assessed_by) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
