package com.johnny.hotel.workforce;
import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.task.*;import lombok.RequiredArgsConstructor;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor @Transactional(propagation=Propagation.MANDATORY) public class WorkforceTaskService {
 private final HotelTaskMapper tasks;private final TaskAssignmentMapper assignments;private final TodoMapper todos;private final TaskRecordMapper records;private final Clock clock;
 private LocalDateTime now(){return LocalDateTime.now(clock);}
 private void one(int n){if(n!=1)throw new BusinessException(409,"Workforce workflow changed concurrently");}
 private void record(Long task,Long assignment,TaskRecordType type,Long actor,String detail){one(records.insert(TaskRecord.builder().taskId(task).assignmentId(assignment).recordType(type.getCode()).actorUserId(actor).detail(detail).build()));}
 public Long create(int type,String sourceKey,String title,String description,Long employee,WorkforceApprovalRouting.Route route){var old=tasks.bySourceForUpdate(sourceKey);if(old!=null)return old.getId();var t=HotelTask.builder().taskType(type).status(0).assignmentMode(route.pool()?0:1).executionType(0).title(title).description(description).sourceKey(sourceKey).createdBy(employee).build();one(tasks.insert(t));record(t.getId(),null,TaskRecordType.TASK_CREATED,employee,"Workforce request created via "+route.code());for(String role:route.eligibleRoles())one(tasks.addEligibleRole(t.getId(),role));if(route.approver()!=null)assign(t,route.approver(),employee,"Assigned via "+route.code(),TaskRecordType.TASK_ASSIGNED);return t.getId();}
 private void assign(HotelTask t,Long approver,Long actor,String detail,TaskRecordType event){var a=TaskAssignment.builder().taskId(t.getId()).assigneeUserId(approver).assignedBy(actor).status(0).isCurrent(1).assignmentRound(assignments.maxRound(t.getId())+1).build();one(assignments.insert(a));var todo=Todo.builder().taskId(t.getId()).assignmentId(a.getId()).userId(approver).build();one(todos.insert(todo));one(tasks.resetAssignment(t.getId(),0,1));record(t.getId(),a.getId(),event,actor,detail);record(t.getId(),a.getId(),TaskRecordType.TODO_CREATED,actor,"Todo "+todo.getId());}
 public Long claim(Long taskId,WorkforceAccess.Actor actor){var t=tasks.lock(taskId);if(t==null||!Set.of(7,8).contains(t.getTaskType())||t.getStatus()!=0||assignments.currentCount(taskId)!=0)throw new BusinessException(409,"Workforce approval task is not claimable");var roles=tasks.eligibleRoles(taskId);if(roles.isEmpty()||roles.stream().noneMatch(actor.roles()::contains))throw new AccessDeniedException("Not eligible for this approval pool");assign(t,actor.id(),actor.id(),"Approval pool claimed",TaskRecordType.TASK_CLAIMED);record(taskId,null,TaskRecordType.TASK_ACCEPTED,actor.id(),"Approver resolved by claim");return actor.id();}
 public void finish(Long taskId,Long actor,boolean cancelled,String detail){var t=tasks.lock(taskId);if(t==null)throw new BusinessException(409,"Workforce task missing");if(t.getStatus()==2||t.getStatus()==3){if(t.getStatus()!=(cancelled?3:2))throw new BusinessException(409,"Workflow result mismatch");return;}for(var todo:todos.active(taskId))if(todo.getStatus()!=2){one(todos.transition(todo.getId(),todo.getStatus(),2,now()));record(taskId,todo.getAssignmentId(),TaskRecordType.TODO_COMPLETED,actor,detail);}assignments.forceComplete(taskId,now());one(tasks.transition(taskId,t.getStatus(),cancelled?3:2,now()));record(taskId,null,cancelled?TaskRecordType.TASK_CANCELLED:TaskRecordType.TASK_COMPLETED,actor,detail);}
 public void reassign(Long taskId,Long approver,Long actor,String detail){var t=tasks.lock(taskId);if(t==null||!Set.of(7,8).contains(t.getTaskType())||!Set.of(0,1,4).contains(t.getStatus()))throw new BusinessException(409,"Workforce task is not open");todos.retire(taskId,now());assignments.endCurrent(taskId,now());assign(t,approver,actor,detail,TaskRecordType.TASK_REASSIGNED);}
}
