package com.johnny.hotel.workforce;
import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import com.johnny.hotel.workforce.WorkforceModels.*;import jakarta.servlet.http.HttpServletRequest;import lombok.RequiredArgsConstructor;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.*;
@RestController @RequestMapping("/api/workforce") @RequiredArgsConstructor
@PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN','HR_ADMIN','FINANCE')")
public class WorkforceController {
 private final AttendanceService attendance;private final LeaveService leave;private final WorkforceApprovalRouting routing;
 @PostMapping("/attendance/check-in") public Result<AttendanceSession> checkIn(@RequestHeader("X-Request-Key")String key,HttpServletRequest request){return Result.success(attendance.checkIn(key,request.getRemoteAddr(),request.getHeader("User-Agent")));}
 @PostMapping("/attendance/check-out") public Result<AttendanceSession> checkOut(@RequestHeader("X-Request-Key")String key,HttpServletRequest request){return Result.success(attendance.checkOut(key,request.getRemoteAddr(),request.getHeader("User-Agent")));}
 @GetMapping("/attendance/current") public Result<AttendanceSession> current(){return Result.success(attendance.current());}
 @GetMapping("/attendance/mine") public Result<PageResult<AttendanceSession>> mineAttendance(@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime to,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(attendance.mine(from,to,page,pageSize));}
 @GetMapping("/attendance") public Result<PageResult<AttendanceSession>> attendance(@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Long departmentId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME)LocalDateTime to,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(attendance.query(employeeId,departmentId,from,to,page,pageSize));}
 @GetMapping("/attendance/anomalies") public Result<PageResult<AttendanceSession>> anomalies(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(attendance.anomalies(page,pageSize));}
 @PostMapping("/attendance/corrections") public Result<AttendanceCorrection> correction(@RequestBody WorkforceRequests.CorrectionCreate r){return Result.success(attendance.requestCorrection(r));}
 @GetMapping("/attendance/corrections") public Result<PageResult<AttendanceCorrection>> corrections(@RequestParam(defaultValue="false")boolean pendingForMe,@RequestParam(required=false)Integer status,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(attendance.corrections(pendingForMe,status,page,pageSize));}
 @PostMapping("/attendance/corrections/{id}/approve") public Result<AttendanceCorrection> approveCorrection(@PathVariable Long id,@RequestBody(required=false)WorkforceRequests.Decision r){return Result.success(attendance.decideCorrection(id,true,r==null?null:r.getNote()));}
 @PostMapping("/attendance/corrections/{id}/reject") public Result<AttendanceCorrection> rejectCorrection(@PathVariable Long id,@RequestBody WorkforceRequests.Decision r){return Result.success(attendance.decideCorrection(id,false,r==null?null:r.getNote()));}
 @PostMapping("/attendance/corrections/{id}/claim") public Result<AttendanceCorrection> claimCorrection(@PathVariable Long id){return Result.success(attendance.claimCorrection(id));}
 @PostMapping("/admin/attendance/corrections/{id}/reassign") public Result<AttendanceCorrection> reassignCorrection(@PathVariable Long id,@RequestBody WorkforceRequests.Reassign r){return Result.success(attendance.reassignCorrection(id,r.getApproverUserId(),r.getReason()));}

 @GetMapping("/leave-types") public Result<PageResult<LeaveType>> types(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(leave.types(page,pageSize));}
 @PostMapping("/admin/leave-types") public Result<LeaveType> createType(@RequestBody WorkforceRequests.LeaveTypeWrite r){return Result.success(leave.writeType(null,r));}
 @PutMapping("/admin/leave-types/{id}") public Result<LeaveType> updateType(@PathVariable Long id,@RequestBody WorkforceRequests.LeaveTypeWrite r){return Result.success(leave.writeType(id,r));}
 @PostMapping("/admin/leave-allocations") public Result<LeaveAllocation> allocate(@RequestBody WorkforceRequests.AllocationCreate r){return Result.success(leave.allocate(r));}
 @GetMapping("/leave-balances/{typeId}") public Result<LeaveBalance> balance(@PathVariable Long typeId,@RequestParam@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate periodStart,@RequestParam@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate periodEnd){return Result.success(leave.balance(typeId,periodStart,periodEnd));}
 @GetMapping("/admin/leave-balances/{employeeId}/{typeId}") public Result<LeaveBalance> balanceFor(@PathVariable Long employeeId,@PathVariable Long typeId,@RequestParam@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate periodStart,@RequestParam@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate periodEnd){return Result.success(leave.balance(employeeId,typeId,periodStart,periodEnd));}
 @PostMapping("/leaves") public Result<LeaveRequest> createLeave(@RequestBody WorkforceRequests.LeaveCreate r){return Result.success(leave.create(r));}
 @PutMapping("/leaves/{id}") public Result<LeaveRequest> updateLeave(@PathVariable Long id,@RequestBody WorkforceRequests.LeaveCreate r){return Result.success(leave.update(id,r));}
 @PostMapping("/leaves/{id}/submit") public Result<LeaveRequest> submit(@PathVariable Long id){return Result.success(leave.submit(id));}
 @PostMapping("/leaves/{id}/cancel") public Result<LeaveRequest> cancel(@PathVariable Long id,@RequestBody WorkforceRequests.Cancel r){return Result.success(leave.cancel(id,r==null?null:r.getReason()));}
 @GetMapping("/leaves/{id}") public Result<LeaveRequest> detail(@PathVariable Long id){return Result.success(leave.detail(id));}
 @GetMapping("/leaves/mine") public Result<PageResult<LeaveRequest>> mine(@RequestParam(required=false)Integer status,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(leave.mine(status,page,pageSize));}
 @GetMapping("/leaves/pending-approval") public Result<PageResult<LeaveRequest>> pending(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(leave.pending(page,pageSize));}
 @PostMapping("/leaves/{id}/approve") public Result<LeaveRequest> approve(@PathVariable Long id,@RequestBody(required=false)WorkforceRequests.Decision r){return Result.success(leave.decide(id,true,r==null?null:r.getNote()));}
 @PostMapping("/leaves/{id}/reject") public Result<LeaveRequest> reject(@PathVariable Long id,@RequestBody WorkforceRequests.Decision r){return Result.success(leave.decide(id,false,r==null?null:r.getNote()));}
 @PostMapping("/leaves/{id}/claim") public Result<LeaveRequest> claimLeave(@PathVariable Long id){return Result.success(leave.claim(id));}
 @GetMapping("/admin/leaves") public Result<PageResult<LeaveRequest>> all(@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Integer status,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(leave.query(employeeId,status,page,pageSize));}
 @PostMapping("/admin/leaves/{id}/reassign") public Result<LeaveRequest> reassignLeave(@PathVariable Long id,@RequestBody WorkforceRequests.Reassign r){return Result.success(leave.reassign(id,r.getApproverUserId(),r.getReason()));}
 @GetMapping("/admin/approval-config") public Result<ApprovalConfig> approvalConfig(){return Result.success(routing.config());}
 @PutMapping("/admin/approval-config") public Result<ApprovalConfig> approvalConfig(@RequestBody WorkforceRequests.ApprovalConfigWrite r){return Result.success(routing.configure(r.getHrDepartmentId()));}
}
