package com.johnny.hotel.guest;
import com.johnny.hotel.common.Result;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequiredArgsConstructor public class BookingGuestController {private final GuestService service;private Long id(Authentication a){return (Long)a.getDetails();}
 @GetMapping("/api/bookings/{bookingId}/guests") @PreAuthorize("hasRole('CUSTOMER')") public Result<List<GuestViews.BookingEntry>> mine(@PathVariable Long bookingId,Authentication a){return Result.success(service.myBookingGuests(bookingId,id(a)));}
 @PostMapping("/api/bookings/{bookingId}/guests/pre-register") @PreAuthorize("hasRole('CUSTOMER')") public Result<GuestViews.BookingEntry> preregister(@PathVariable Long bookingId,@Valid @RequestBody GuestRequests.Add r,Authentication a){return Result.success(service.preRegister(bookingId,r,id(a)));}
 @GetMapping("/api/admin/bookings/{bookingId}/guests") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<List<GuestViews.BookingEntry>> list(@PathVariable Long bookingId,Authentication a){return Result.success(service.bookingGuests(bookingId,id(a)));}
 @PostMapping("/api/admin/bookings/{bookingId}/guests") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<GuestViews.BookingEntry> add(@PathVariable Long bookingId,@Valid @RequestBody GuestRequests.Add r,Authentication a){return Result.success(service.addToBooking(bookingId,r,id(a)));}
 @DeleteMapping("/api/admin/bookings/{bookingId}/guests/{relationId}") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<Void> remove(@PathVariable Long bookingId,@PathVariable Long relationId,Authentication a){service.removeFromBooking(bookingId,relationId,id(a));return Result.success(null);}
 @PostMapping("/api/admin/bookings/{bookingId}/guest-registration/confirm") @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public Result<GuestViews.Registration> confirm(@PathVariable Long bookingId,Authentication a){return Result.success(service.confirm(bookingId,id(a)));}
}
