package com.johnny.hotel.guest;
import com.johnny.hotel.entity.*;import com.johnny.hotel.enums.BookingStatus;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.mapper.*;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class GuestServiceImpl implements GuestService {
 private final GuestMapper mapper;private final BookingMapper bookings; private final com.johnny.hotel.stay.StayMapper stays;private final GuestAccess access;private final SysAuditLogMapper audit;private final com.johnny.hotel.pagination.PaginationSupport pagination;
 private GuestViews.Profile vo(GuestProfile p){if(p==null)return null;return GuestViews.Profile.builder().id(p.getId()).linkedUserId(p.getLinkedUserId()).firstName(p.getFirstName()).lastName(p.getLastName()).phone(p.getPhone()).email(p.getEmail()).gender(p.getGender()).dateOfBirth(p.getDateOfBirth()).nationality(p.getNationality()).documentType(p.getDocumentType()).documentNumber(p.getDocumentNumber()).issuingCountry(p.getIssuingCountry()).documentExpiryDate(p.getDocumentExpiryDate()).notes(p.getNotes()).status(p.getStatus()).build();}
 private GuestProfile entity(GuestRequests.Profile r,Long linked){return GuestProfile.builder().linkedUserId(linked).firstName(trim(r.getFirstName())).lastName(trim(r.getLastName())).phone(blank(r.getPhone())).email(blank(r.getEmail())).gender(blank(r.getGender())).dateOfBirth(r.getDateOfBirth()).nationality(blank(r.getNationality())).documentType(blank(r.getDocumentType())).documentNumber(blank(r.getDocumentNumber())).issuingCountry(blank(r.getIssuingCountry())).documentExpiryDate(r.getDocumentExpiryDate()).notes(blank(r.getNotes())).status(1).build();}
 private String trim(String s){return s==null?null:s.trim();}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
 public GuestViews.Profile me(Long user){access.customer(user);return vo(mapper.byUser(user));}
 @Transactional public GuestViews.Profile saveMe(Long user,GuestRequests.Profile r){access.customer(user);var p=mapper.byUser(user);if(p==null){p=entity(r,user);insert(p);}else{copy(p,r);one(mapper.updateProfile(p));}return vo(mapper.profile(p.getId()));}
 @Transactional public GuestViews.Profile create(GuestRequests.Profile r,Long actor){access.employee(actor);var p=entity(r,null);insert(p);return vo(p);}
 public GuestViews.Profile get(Long id,Long actor){access.employee(actor);return vo(requireProfile(id));}
 @Transactional public GuestViews.Profile update(Long id,GuestRequests.Profile r,Long actor){access.employee(actor);var p=requireProfile(id);copy(p,r);one(mapper.updateProfile(p));return vo(mapper.profile(id));}
 public List<GuestViews.Profile> search(String q,Long actor){access.employee(actor);return mapper.search(blank(q)).stream().map(this::vo).toList();}
 public List<GuestViews.Profile> duplicateCandidates(GuestRequests.Profile r,Long actor){access.employee(actor);var p=entity(r,null);return mapper.duplicates(p).stream().map(this::vo).toList();}
 public List<GuestViews.BookingEntry> myBookingGuests(Long b,Long user){access.customer(user);owned(b,user);return entries(b);}
 @Transactional public GuestViews.BookingEntry preRegister(Long b,GuestRequests.Add r,Long user){access.customer(user);var booking=lockMutable(b);if(!user.equals(booking.getUserId()))throw hidden();GuestProfile p;if(r.getGuestId()!=null){p=requireProfile(r.getGuestId());if(!Objects.equals(p.getLinkedUserId(),user))throw hidden();}else{if(r.getProfile()==null)throw bad("Guest profile is required");p=r.getRole()==GuestRole.PRIMARY?mapper.byUser(user):null;if(p==null){p=entity(r.getProfile(),r.getRole()==GuestRole.PRIMARY?user:null);insert(p);}else{copy(p,r.getProfile());one(mapper.updateProfile(p));}}return add(booking,p,r.getRole());}
 public List<GuestViews.BookingEntry> bookingGuests(Long b,Long actor){access.employee(actor);requireBooking(b);return entries(b);}
 @Transactional public GuestViews.BookingEntry addToBooking(Long b,GuestRequests.Add r,Long actor){access.employee(actor);var booking=lockForEmployeeAdd(b,r.getRole());GuestProfile p=r.getGuestId()!=null?requireProfile(r.getGuestId()):createDetached(r);return add(booking,p,r.getRole());}
 @Transactional public void removeFromBooking(Long b,Long relation,Long actor){access.employee(actor);lockMutable(b);if(mapper.registration(b)!=null)throw bad("Confirmed registration cannot be changed");one(mapper.remove(b,relation));}
 @Transactional public GuestViews.Registration confirm(Long b,Long actor){access.employee(actor);var booking=bookings.selectByIdForUpdate(b);if(booking==null)throw bad("Booking does not exist");if(booking.getStatus()!=BookingStatus.APPROVED.getCode())throw bad("Only approved bookings can be registered");var existing=mapper.registration(b);if(existing!=null)return registration(existing);if(stays.byBooking(b)!=null)throw bad("Registration belongs to the arrived Stay");var primary=validGuests(booking);var reg=GuestRegistration.builder().bookingId(b).primaryGuestId(primary.getGuestId()).registeredBy(actor).registeredTime(LocalDateTime.now()).registrationConfirmed(true).build();try{one(mapper.insertRegistration(reg));}catch(DataIntegrityViolationException e){var now=mapper.registration(b);if(now!=null)return registration(now);throw e;}one(audit.insert(SysAuditLog.builder().operatorId(actor).targetUserId(booking.getUserId()).action("CONFIRM_GUEST_REGISTRATION").detail("Booking id: "+b).build()));return registration(reg);}
 public List<GuestViews.Stay> stays(Long guest,Long actor){access.employee(actor);requireProfile(guest);return mapper.stays(guest);} public com.johnny.hotel.pagination.PageResult<GuestViews.Stay> stayPage(Long guest,Long actor,Integer page,Integer size){access.employee(actor);requireProfile(guest);var w=pagination.window(page,size,true);return pagination.result(w,mapper.stayPage(guest,w.offset(),pagination.limit(w)),mapper.stayCount(guest));}
 public void validateForCheckIn(Long b,Long actor){access.employee(actor);var booking=requireBooking(b);validGuests(booking);var r=mapper.registration(b);if(r==null||!Boolean.TRUE.equals(r.getRegistrationConfirmed()))throw bad("Guest registration must be confirmed before check-in");var primary=mapper.primary(b);if(!Objects.equals(r.getPrimaryGuestId(),primary.getGuestId()))throw bad("Registered primary guest no longer matches booking");}
 private BookingGuest validGuests(Booking b){var primary=mapper.primary(b.getId());if(primary==null)throw bad("Primary guest is required before check-in");int count=mapper.count(b.getId());if(count<1||count>b.getGuestCount())throw bad("Registered guest count exceeds booking guest count");var p=requireProfile(primary.getGuestId());if(blank(p.getFirstName())==null||blank(p.getLastName())==null||blank(p.getDocumentType())==null||blank(p.getDocumentNumber())==null||blank(p.getNationality())==null)throw bad("Primary guest identity information is incomplete");return primary;}
 private GuestViews.BookingEntry add(Booking b,GuestProfile p,GuestRole role){if(role==null)throw bad("Guest role is required");if(mapper.count(b.getId())>=b.getGuestCount())throw bad("Registered guest count exceeds booking guest count");var bg=BookingGuest.builder().bookingId(b.getId()).guestId(p.getId()).guestRole(role.getCode()).build();try{one(mapper.add(bg));}catch(DataIntegrityViolationException e){throw bad("Guest is already registered or a primary guest already exists");}return entry(bg,p);}
 private GuestProfile createDetached(GuestRequests.Add r){if(r.getProfile()==null)throw bad("Guest profile is required");var p=entity(r.getProfile(),null);insert(p);return p;}
 private List<GuestViews.BookingEntry> entries(Long b){return mapper.bookingGuests(b).stream().map(x->entry(x,mapper.profile(x.getGuestId()))).toList();}
 private GuestViews.BookingEntry entry(BookingGuest bg,GuestProfile p){return GuestViews.BookingEntry.builder().relationId(bg.getId()).bookingId(bg.getBookingId()).role(GuestRole.fromCode(bg.getGuestRole())).guest(vo(p)).build();}
 private GuestViews.Registration registration(GuestRegistration r){return GuestViews.Registration.builder().id(r.getId()).bookingId(r.getBookingId()).primaryGuestId(r.getPrimaryGuestId()).registeredBy(r.getRegisteredBy()).registeredTime(r.getRegisteredTime()).confirmed(Boolean.TRUE.equals(r.getRegistrationConfirmed())).build();}
 private void insert(GuestProfile p){try{one(mapper.insertProfile(p));}catch(DataIntegrityViolationException e){throw bad("User already has a linked guest profile");}}
 private void copy(GuestProfile p,GuestRequests.Profile r){var n=entity(r,p.getLinkedUserId());n.setId(p.getId());p.setFirstName(n.getFirstName());p.setLastName(n.getLastName());p.setPhone(n.getPhone());p.setEmail(n.getEmail());p.setGender(n.getGender());p.setDateOfBirth(n.getDateOfBirth());p.setNationality(n.getNationality());p.setDocumentType(n.getDocumentType());p.setDocumentNumber(n.getDocumentNumber());p.setIssuingCountry(n.getIssuingCountry());p.setDocumentExpiryDate(n.getDocumentExpiryDate());p.setNotes(n.getNotes());}
 private Booking lockMutable(Long b){var x=bookings.selectByIdForUpdate(b);if(x==null)throw bad("Booking does not exist");if(stays.byBooking(x.getId())!=null||x.getStatus()==BookingStatus.CANCELLED_BY_USER.getCode()||x.getStatus()==BookingStatus.REJECTED_BY_STAFF.getCode())throw bad("Historical booking guest list cannot be changed");if(mapper.registration(b)!=null)throw bad("Confirmed registration cannot be changed");return x;}
 private Booking lockForEmployeeAdd(Long b,GuestRole role){var x=bookings.selectByIdForUpdate(b);if(x==null)throw bad("Booking does not exist");if(stays.byBooking(x.getId())!=null||x.getStatus()==BookingStatus.CANCELLED_BY_USER.getCode()||x.getStatus()==BookingStatus.REJECTED_BY_STAFF.getCode())throw bad("Historical booking guest list cannot be changed");if(mapper.registration(b)!=null)throw bad("Confirmed registration cannot be changed");return x;}
 private Booking requireBooking(Long id){var b=bookings.selectById(id);if(b==null)throw bad("Booking does not exist");return b;}private void owned(Long b,Long u){var x=requireBooking(b);if(!u.equals(x.getUserId()))throw hidden();}private GuestProfile requireProfile(Long id){var p=mapper.profile(id);if(p==null)throw bad("Guest does not exist");return p;}private BusinessException hidden(){return new BusinessException(404,"Resource not found");}private BusinessException bad(String m){return new BusinessException(m);}private void one(int n){if(n!=1)throw bad("Guest operation failed");}
}
