package com.johnny.hotel.damage;
import com.johnny.hotel.dto.FolioItemCommand;import com.johnny.hotel.entity.*;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.inspection.*;import com.johnny.hotel.mapper.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.service.FolioService;import com.johnny.hotel.workorder.*;import lombok.RequiredArgsConstructor;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;import static com.johnny.hotel.service.support.BillingRules.*;
@Service@RequiredArgsConstructor public class DamageAssessmentServiceImpl implements DamageAssessmentService{
 private final DamageAssessmentMapper db;private final DamageAccess access;private final BookingMapper bookings;private final com.johnny.hotel.stay.StayContext stayContext;private final StayRoomAssignmentMapper assignments;private final FolioMapper folios;private final RoomWorkOrderMapper workOrders;private final InspectionMapper inspections;private final FolioService ledger;private final PaginationSupport pagination;private final Clock clock;
 private String text(String value,int max,boolean required){if(value==null||value.isBlank()){if(required)throw new BusinessException("Required text is missing");return null;}value=value.trim();require(value.length()<=max,"Text is too long");return value;}
 @Override@Transactional public DamageAssessment report(DamageRequests.Report r){var actor=access.actor();access.report(actor);require(r!=null&&r.getSourceType()!=null,"Damage report is required");String key=text(r.getRequestKey(),80,true),description=text(r.getDescription(),500,true);var prior=db.byRequest(actor.id(),key);if(prior!=null){require(sameReport(prior,r,description),"Request key already represents another damage report");return prior;}var booking=stayContext.lockReservation(r.getStayId());require(booking!=null,"Booking does not exist");var assignment=assignments.selectById(r.getAssignmentId());require(assignment!=null&&Objects.equals(assignment.getStayId(),r.getStayId()),"Assignment does not belong to booking");validateSource(r.getSourceType(),r.getSourceId(),r.getStayId(),assignment.getId(),assignment.getRoomId());var folio=folios.selectByStayIdForUpdate(r.getStayId());require(folio!=null,"Folio does not exist");var value=DamageAssessment.builder().roomId(assignment.getRoomId()).stayId(r.getStayId()).assignmentId(assignment.getId()).folioId(folio.getId()).sourceType(r.getSourceType().getCode()).sourceId(r.getSourceId()).damageDescription(description).requestKey(key).reportedBy(actor.id()).responsibility(DamageResponsibility.PENDING.getCode()).status(DamageAssessmentStatus.PENDING.getCode()).build();try{one(db.insert(value));}catch(DuplicateKeyException ex){var concurrent=db.byRequest(actor.id(),key);if(concurrent!=null&&sameReport(concurrent,r,description))return concurrent;throw new BusinessException("Damage source or request key was already reported");}return db.find(value.getId());}
 private boolean sameReport(DamageAssessment a,DamageRequests.Report r,String d){return Objects.equals(a.getStayId(),r.getStayId())&&Objects.equals(a.getAssignmentId(),r.getAssignmentId())&&a.getSourceType()==r.getSourceType().getCode()&&Objects.equals(a.getSourceId(),r.getSourceId())&&Objects.equals(a.getDamageDescription(),d);}
 private void validateSource(DamageSourceType type,Long source,Long booking,Long assignment,Long room){require(source!=null,"Damage source is required");if(type==DamageSourceType.WORK_ORDER){var w=workOrders.find(source);require(w!=null&&Objects.equals(w.getRoomId(),room),"Work order does not match the occupied room");return;}if(type==DamageSourceType.INSPECTION){var i=inspections.find(source);require(i!=null&&Objects.equals(i.getRoomId(),room)&&Objects.equals(i.getStayId(),booking)&&Objects.equals(i.getAssignmentId(),assignment),"Inspection does not match the stay");return;}var f=db.repairFacts(source);require(f!=null&&Objects.equals(f.roomId(),room)&&Objects.equals(f.stayId(),booking)&&Objects.equals(f.assignmentId(),assignment),"Repair task does not match the stay");}
 @Override@Transactional public DamageAssessment assess(Long id,DamageRequests.Assess r){var actor=access.actor();access.assess(actor);require(r!=null&&r.getResponsibility()!=null&&r.getResponsibility()!=DamageResponsibility.PENDING,"A final responsibility is required");var seed=db.find(id);require(seed!=null,"Damage assessment does not exist");require(stayContext.lockReservation(seed.getStayId())!=null,"Booking does not exist");var value=db.lock(id);require(value!=null,"Damage assessment does not exist");BigDecimal charge=null;String reason=text(r.getReason(),500,r.getResponsibility()==DamageResponsibility.CUSTOMER);if(r.getResponsibility()==DamageResponsibility.CUSTOMER){charge=money(r.getChargeAmount(),12);require(charge.signum()>0,"Customer damage charge must be positive");}else require(r.getChargeAmount()==null||r.getChargeAmount().signum()==0,"Hotel or waived responsibility cannot carry a customer charge");if(value.getStatus()!=DamageAssessmentStatus.PENDING.getCode()){require(sameDecision(value,r,charge,reason),"Damage assessment was already finalized differently");return value;}var folio=folios.selectByIdForUpdate(value.getFolioId());require(folio!=null,"Folio does not exist");int status=DamageAssessmentStatus.RESOLVED.getCode();Long item=null;if(r.getResponsibility()==DamageResponsibility.CUSTOMER){if(folio.getClosedTime()!=null){status=DamageAssessmentStatus.UNPOSTED_CLOSED_FOLIO.getCode();}else{var posted=ledger.addItem(folio.getStayId(),FolioItemCommand.builder().itemType("DAMAGE_CHARGE").description(value.getDamageDescription()).businessDate(LocalDate.now(clock)).quantity(BigDecimal.ONE.setScale(2)).unitPrice(charge).amount(charge).sourceType("DAMAGE_ASSESSMENT").sourceId(value.getId()).refundable(true).eventKey("DAMAGE_ASSESSMENT:"+value.getId()).build(),actor.id());item=posted.getId();}}one(db.resolve(id,r.getResponsibility().getCode(),charge,reason,status,item,actor.id()));return db.find(id);}
 private boolean sameDecision(DamageAssessment a,DamageRequests.Assess r,BigDecimal charge,String reason){return a.getResponsibility()==r.getResponsibility().getCode()&&Objects.equals(a.getReason(),reason)&&(charge==null?a.getAssessedCharge()==null:a.getAssessedCharge()!=null&&a.getAssessedCharge().compareTo(charge)==0);}
 @Override public DamageAssessment get(Long id){var a=access.actor();access.read(a);var value=db.find(id);require(value!=null,"Damage assessment does not exist");return value;}
 @Override public PageResult<DamageAssessment> list(Long booking,Long room,Integer status,Integer responsibility,Integer sourceType,Integer page,Integer size){var a=access.actor();access.read(a);try{if(status!=null)DamageAssessmentStatus.fromCode(status);if(responsibility!=null)DamageResponsibility.fromCode(responsibility);if(sourceType!=null)DamageSourceType.fromCode(sourceType);}catch(IllegalArgumentException e){throw new BusinessException("Invalid damage filter code");}boolean search=booking!=null||room!=null||status!=null||responsibility!=null||sourceType!=null;var w=pagination.window(page,size,search);int limit=pagination.limit(w);return pagination.result(w,limit==0?List.of():db.page(booking,room,status,responsibility,sourceType,w.offset(),limit),db.count(booking,room,status,responsibility,sourceType));}
}

