package com.johnny.hotel.group;import org.apache.ibatis.annotations.*;import java.time.*;import java.util.*;
@Mapper public interface GroupMapper{@Insert("INSERT INTO group_reservation(group_code,group_name,group_type,status,organizer_name,contact_phone,contact_email,ar_account_id,arrival_date,departure_date,currency,booking_source,billing_mode,notes,created_by) VALUES(#{groupCode},#{groupName},#{groupType},#{status},#{organizerName},#{contactPhone},#{contactEmail},#{arAccountId},#{arrivalDate},#{departureDate},#{currency},#{bookingSource},'INDIVIDUAL_PAY',#{notes},#{createdBy})")@Options(useGeneratedKeys=true,keyProperty="id")int insertGroup(GroupModels.Group x);@Select("SELECT * FROM group_reservation WHERE id=#{id}")GroupModels.Group group(Long id);@Select("SELECT * FROM group_reservation WHERE id=#{id} FOR UPDATE")GroupModels.Group lockGroup(Long id);@Update("UPDATE group_reservation SET status=#{to} WHERE id=#{id} AND status=#{from}")int transition(@Param("id")Long id,@Param("from")int from,@Param("to")int to);
@Insert("INSERT INTO group_room_block(group_id,room_type_id,start_date,end_date,blocked_quantity,rate_mode,negotiated_rate,cut_off_date,status) VALUES(#{groupId},#{roomTypeId},#{startDate},#{endDate},#{blockedQuantity},#{rateMode},#{negotiatedRate},#{cutOffDate},#{status})")@Options(useGeneratedKeys=true,keyProperty="id")int insertBlock(GroupModels.Block x);@Select("SELECT * FROM group_room_block WHERE id=#{id}")GroupModels.Block block(Long id);@Select("SELECT * FROM group_room_block WHERE id=#{id} FOR UPDATE")GroupModels.Block lockBlock(Long id);@Select("SELECT * FROM group_room_block WHERE group_id=#{id} ORDER BY id")List<GroupModels.Block> blocks(Long id);@Update("UPDATE group_room_block SET released_quantity=released_quantity+#{q} WHERE id=#{id} AND blocked_quantity-picked_up_quantity-released_quantity>=#{q}")int release(@Param("id")Long id,@Param("q")int q);@Update("UPDATE group_room_block SET picked_up_quantity=picked_up_quantity+1 WHERE id=#{id} AND blocked_quantity-picked_up_quantity-released_quantity>0")int pickup(Long id);@Update("UPDATE group_room_block SET picked_up_quantity=picked_up_quantity-1 WHERE id=#{id} AND picked_up_quantity>0")int returnSlot(Long id);
@Select("SELECT COALESCE(SUM(blocked_quantity-released_quantity),0) FROM group_room_block b JOIN group_reservation g ON g.id=b.group_id WHERE b.room_type_id=#{type} AND b.status=1 AND g.status=2 AND b.start_date<#{end} AND b.end_date>#{start}")int groupCommitted(@Param("type")Long type,@Param("start")LocalDate start,@Param("end")LocalDate end);@Select("SELECT COUNT(*) FROM booking WHERE room_type_id=#{type} AND group_block_id IS NULL AND status=1 AND check_in_date<#{end} AND check_out_date>#{start}")int normalCommitted(@Param("type")Long type,@Param("start")LocalDate start,@Param("end")LocalDate end);
@Select("SELECT b.blocked_quantity-b.released_quantity FROM group_room_block b JOIN group_reservation g ON g.id=b.group_id WHERE b.room_type_id=#{type} AND b.status=1 AND g.status=2 AND b.start_date<#{end} AND b.end_date>#{start} FOR UPDATE")List<Integer> lockedGroupCommitments(@Param("type")Long type,@Param("start")LocalDate start,@Param("end")LocalDate end);@Select("SELECT id FROM booking WHERE room_type_id=#{type} AND group_block_id IS NULL AND status=1 AND check_in_date<#{end} AND check_out_date>#{start} FOR UPDATE")List<Long> lockedNormalCommitments(@Param("type")Long type,@Param("start")LocalDate start,@Param("end")LocalDate end);
@Insert("INSERT INTO group_rooming_entry(group_id,block_id,guest_profile_id,request_key,status) VALUES(#{groupId},#{blockId},#{guestProfileId},#{requestKey},#{status})")@Options(useGeneratedKeys=true,keyProperty="id")int insertEntry(GroupModels.Entry x);@Select("SELECT * FROM group_rooming_entry WHERE request_key=#{key} FOR UPDATE")GroupModels.Entry entryByKey(String key);@Select("SELECT * FROM group_rooming_entry WHERE id=#{id} FOR UPDATE")GroupModels.Entry lockEntry(Long id);@Update("UPDATE group_rooming_entry SET guest_profile_id=#{guest},status=CASE WHEN #{guest} IS NULL THEN 0 ELSE 1 END WHERE id=#{id} AND booking_id IS NULL")int attach(@Param("id")Long id,@Param("guest")Long guest);@Update("UPDATE group_rooming_entry SET booking_id=#{booking},status=2 WHERE id=#{id} AND booking_id IS NULL")int bindBooking(@Param("id")Long id,@Param("booking")Long booking);@Select("SELECT * FROM group_rooming_entry WHERE group_id=#{group} AND (#{status} IS NULL OR status=#{status}) AND (#{block} IS NULL OR block_id=#{block}) ORDER BY id DESC LIMIT #{offset},#{size}")List<GroupModels.Entry> entries(@Param("group")Long group,@Param("status")Integer status,@Param("block")Long block,@Param("offset")int offset,@Param("size")int size);@Select("SELECT COUNT(*) FROM group_rooming_entry WHERE group_id=#{group} AND (#{status} IS NULL OR status=#{status}) AND (#{block} IS NULL OR block_id=#{block})")long countEntries(@Param("group")Long group,@Param("status")Integer status,@Param("block")Long block);
@Select("SELECT COUNT(*) FROM group_reservation WHERE (#{status} IS NULL OR status=#{status}) AND (#{q} IS NULL OR group_code LIKE CONCAT('%',#{q},'%') OR group_name LIKE CONCAT('%',#{q},'%'))")long count(@Param("status")Integer status,@Param("q")String q);@Select("SELECT * FROM group_reservation WHERE (#{status} IS NULL OR status=#{status}) AND (#{q} IS NULL OR group_code LIKE CONCAT('%',#{q},'%') OR group_name LIKE CONCAT('%',#{q},'%')) ORDER BY create_time DESC,id DESC LIMIT #{offset},#{size}")List<GroupModels.Group> page(@Param("status")Integer status,@Param("q")String q,@Param("offset")int offset,@Param("size")int size);
@Select("SELECT * FROM group_rooming_entry WHERE booking_id=#{booking} FOR UPDATE")GroupModels.Entry entryByBooking(Long booking);
@Update("UPDATE group_rooming_entry SET status=3 WHERE id=#{id} AND status=2")int releaseEntry(Long id);
@Select("SELECT * FROM booking WHERE group_id=#{group} AND (#{status} IS NULL OR status=#{status}) ORDER BY id DESC LIMIT #{offset},#{size}")List<com.johnny.hotel.entity.Booking> childBookings(@Param("group")Long group,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
@Select("SELECT COUNT(*) FROM booking WHERE group_id=#{group} AND (#{status} IS NULL OR status=#{status})")long countChildBookings(@Param("group")Long group,@Param("status")Integer status);
}

