package com.johnny.hotel.settlement;import com.johnny.hotel.payment.HotelTransactionRecord;import org.apache.ibatis.annotations.*;import java.time.*;import java.util.*;
@Mapper public interface SettlementMapper{
 @Insert("INSERT INTO gateway_settlement_batch(provider,provider_batch_id,currency,period_start,period_end,declared_gross,declared_fee,declared_net,status,reconciliation_status,posting_business_date,provider_created_at,provider_settled_at,imported_by) VALUES(#{provider},#{providerBatchId},#{currency},#{periodStart},#{periodEnd},#{declaredGross},#{declaredFee},#{declaredNet},'PROCESSING','PENDING',#{postingBusinessDate},#{providerCreatedAt},#{providerSettledAt},#{importedBy}) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)")@Options(useGeneratedKeys=true,keyProperty="id")int ensureBatch(SettlementBatch b);
 @Select("SELECT * FROM gateway_settlement_batch WHERE provider=#{provider} AND provider_batch_id=#{ref} FOR UPDATE")SettlementBatch lockBatch(@Param("provider")String provider,@Param("ref")String ref);
 @Select("SELECT * FROM gateway_settlement_batch WHERE id=#{id} FOR UPDATE")SettlementBatch lockBatchById(Long id);
 @Select("SELECT * FROM gateway_settlement_batch WHERE id=#{id}")SettlementBatch batch(Long id);
 @Update("UPDATE gateway_settlement_batch SET calculated_gross=#{gross},calculated_fee=#{fee},calculated_net=#{net},status=#{status},reconciliation_status=#{reconciliation},exception_reason=#{reason} WHERE id=#{id}")int reconcile(@Param("id")Long id,@Param("gross")java.math.BigDecimal gross,@Param("fee")java.math.BigDecimal fee,@Param("net")java.math.BigDecimal net,@Param("status")String status,@Param("reconciliation")String reconciliation,@Param("reason")String reason);
 @Insert("INSERT INTO gateway_settlement_item(batch_id,source_type,source_id,provider_payment_id,direction,gross_amount,fee_amount,net_amount,currency,status,exception_reason,provider_occurred_at) VALUES(#{batchId},#{sourceType},#{sourceId},#{providerPaymentId},#{direction},#{grossAmount},#{feeAmount},#{netAmount},#{currency},#{status},#{exceptionReason},#{providerOccurredAt})")@Options(useGeneratedKeys=true,keyProperty="id")int insertItem(SettlementItem i);
 @Select("SELECT * FROM gateway_settlement_item WHERE batch_id=#{id} ORDER BY id")List<SettlementItem> items(Long id);
 @Select("SELECT * FROM gateway_settlement_item WHERE source_type=#{type} AND source_id=#{id}")SettlementItem itemBySource(@Param("type")String type,@Param("id")Long id);
 @Select("SELECT * FROM hotel_transaction_record WHERE source_type=#{type} AND source_id=#{id}")HotelTransactionRecord moneySource(@Param("type")String type,@Param("id")Long id);
 @Select("SELECT COALESCE(MAX(attempt_no),0)+1 FROM gateway_settlement_reconciliation_attempt WHERE batch_id=#{id}")int nextAttemptNo(Long id);
 @Insert("INSERT INTO gateway_settlement_reconciliation_attempt(batch_id,attempt_no,request_key,status,calculated_gross,calculated_fee,calculated_net,exception_reason,performed_by) VALUES(#{batchId},#{attemptNo},#{requestKey},#{status},#{calculatedGross},#{calculatedFee},#{calculatedNet},#{exceptionReason},#{performedBy})")@Options(useGeneratedKeys=true,keyProperty="id")int insertAttempt(SettlementReconciliationAttempt value);
 @Insert("INSERT INTO gateway_settlement_reconciliation_item(attempt_id,settlement_item_id,status,exception_reason) VALUES(#{attemptId},#{settlementItemId},#{status},#{exceptionReason})")int insertAttemptItem(SettlementReconciliationItem value);
 @Select("SELECT * FROM gateway_settlement_reconciliation_attempt WHERE batch_id=#{id} ORDER BY attempt_no DESC")List<SettlementReconciliationAttempt> attempts(Long id);
 @Select("SELECT * FROM gateway_settlement_reconciliation_attempt WHERE batch_id=#{batch} AND request_key=#{key}")SettlementReconciliationAttempt attemptByRequest(@Param("batch")Long batch,@Param("key")String key);
 @Select("SELECT COUNT(*) FROM gateway_settlement_reconciliation_item i JOIN gateway_settlement_reconciliation_attempt a ON a.id=i.attempt_id WHERE a.batch_id=#{id} AND a.attempt_no=(SELECT MAX(x.attempt_no) FROM gateway_settlement_reconciliation_attempt x WHERE x.batch_id=#{id}) AND i.status<>'MATCHED'")int latestUnresolvedCount(Long id);
 @Insert("INSERT INTO gateway_payout(batch_id,provider,provider_payout_id,currency,amount,status,reconciliation_status,exception_reason,expected_at,paid_at,bank_reference,posting_business_date,confirmed_by) VALUES(#{batchId},#{provider},#{providerPayoutId},#{currency},#{amount},#{status},#{reconciliationStatus},#{exceptionReason},#{expectedAt},#{paidAt},#{bankReference},#{postingBusinessDate},#{confirmedBy}) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)")@Options(useGeneratedKeys=true,keyProperty="id")int ensurePayout(GatewayPayout p);
 @Select("SELECT * FROM gateway_payout WHERE provider=#{provider} AND provider_payout_id=#{ref} FOR UPDATE")GatewayPayout lockPayout(@Param("provider")String provider,@Param("ref")String ref);
 @Select("SELECT * FROM gateway_payout WHERE batch_id=#{id}")GatewayPayout payoutByBatch(Long id);
 @Select("SELECT * FROM gateway_payout WHERE batch_id=#{id} FOR UPDATE")GatewayPayout lockPayoutByBatch(Long id);
 @Select("SELECT * FROM gateway_settlement_batch ORDER BY posting_business_date DESC,id DESC LIMIT #{offset},#{size}")List<SettlementBatch>batches(@Param("offset")int offset,@Param("size")int size);@Select("SELECT COUNT(*) FROM gateway_settlement_batch")long batchCount();
 @Select("SELECT COALESCE(SUM(CASE WHEN reconciliation_status='MATCHED' THEN declared_gross ELSE 0 END),0) gross,COALESCE(SUM(CASE WHEN reconciliation_status='MATCHED' THEN declared_fee ELSE 0 END),0) processor_fee,COALESCE(SUM(CASE WHEN reconciliation_status='MATCHED' THEN declared_net ELSE 0 END),0) net,(SELECT COALESCE(SUM(amount),0) FROM gateway_payout WHERE status='COMPLETED') completed_payout,SUM(reconciliation_status='MATCHED') matched_batches,SUM(reconciliation_status IN('MISMATCH','MISSING')) exception_batches FROM gateway_settlement_batch")SettlementMetrics metrics();
}
