package com.johnny.hotel.settlement;

import com.johnny.hotel.ar.ArAccess;
import com.johnny.hotel.businessdate.BusinessDateService;
import com.johnny.hotel.entity.SysAuditLog;
import com.johnny.hotel.exception.BusinessException;
import com.johnny.hotel.mapper.SysAuditLogMapper;
import com.johnny.hotel.pagination.*;
import com.johnny.hotel.payment.*;
import com.johnny.hotel.settlement.SettlementRequests.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.Clock;
import java.util.*;

@Service @RequiredArgsConstructor
public class SettlementService {
 private final SettlementMapper db; private final ArAccess access; private final BusinessDateService dates;
 private final PaymentCoreMapper transactions; private final SysAuditLogMapper audits; private final PaginationSupport pages; private final Clock clock;
 private void req(boolean b,String m){if(!b)throw new BusinessException(m);} private void one(int n){if(n!=1)throw new BusinessException(409,"Settlement state changed");}
 private String norm(String s){return s==null?null:s.trim().toUpperCase(Locale.ROOT);} private BigDecimal money(BigDecimal x){req(x!=null&&x.scale()<=2,"Invalid settlement money scale");return x.setScale(2);}

 @Transactional public SettlementView importBatch(Import r){var actor=access.actor();String provider=norm(r.provider),currency=norm(r.currency);req(r.periodStart==null||r.periodEnd==null||!r.periodStart.isAfter(r.periodEnd),"Invalid settlement period");
  var seed=SettlementBatch.builder().provider(provider).providerBatchId(r.providerBatchId.trim()).currency(currency).periodStart(r.periodStart).periodEnd(r.periodEnd).declaredGross(money(r.grossAmount)).declaredFee(money(r.feeAmount)).declaredNet(money(r.netAmount)).postingBusinessDate(dates.postingDate()).providerCreatedAt(r.providerCreatedAt).providerSettledAt(r.providerSettledAt).importedBy(actor.id()).build();
  db.ensureBatch(seed);var batch=db.lockBatch(provider,seed.getProviderBatchId());req(batch!=null,"Settlement batch lock failed");if(!"PROCESSING".equals(batch.getStatus())){same(batch,seed);return view(batch.getId());}
  var rows=new ArrayList<SettlementItem>();for(Item item:r.items){String type=norm(item.sourceType);req(db.itemBySource(type,item.sourceId)==null,"Source event was already settled");var row=SettlementItem.builder().batchId(batch.getId()).sourceType(type).sourceId(item.sourceId).providerPaymentId(item.providerPaymentId).direction(norm(item.direction)).grossAmount(money(item.grossAmount)).feeAmount(money(item.feeAmount)).netAmount(money(item.netAmount)).currency(norm(item.currency)).providerOccurredAt(item.providerOccurredAt).build();String issue=currentIssue(batch,row);row.setStatus(issue==null?"MATCHED":db.moneySource(type,item.sourceId)==null?"MISSING":"MISMATCH");row.setExceptionReason(issue);one(db.insertItem(row));rows.add(row);}
  reconcileLocked(batch,rows,"IMPORT",actor.id());audit(actor.id(),"IMPORT_GATEWAY_SETTLEMENT",batch.getId());return view(batch.getId());}

 @Transactional public SettlementView reconcile(Long batchId,Reconcile r){var actor=access.actor();var batch=db.lockBatchById(batchId);req(batch!=null,"Settlement batch not found");if(db.attemptByRequest(batchId,r.requestKey.trim())!=null)return view(batchId);if("SETTLED".equals(batch.getStatus())&&"MATCHED".equals(batch.getReconciliationStatus()))return view(batchId);var rows=db.items(batchId);req(!rows.isEmpty(),"Settlement batch has no immutable provider items");reconcileLocked(batch,rows,r.requestKey.trim(),actor.id());audit(actor.id(),"RE_RECONCILE_GATEWAY_SETTLEMENT",batchId);return view(batchId);}

 private void reconcileLocked(SettlementBatch batch,List<SettlementItem> rows,String key,Long actor){BigDecimal gross=BigDecimal.ZERO.setScale(2),fee=BigDecimal.ZERO.setScale(2),net=BigDecimal.ZERO.setScale(2);var results=new ArrayList<SettlementReconciliationItem>();String problem=null;boolean missing=false;
  for(var row:rows){gross=gross.add("IN".equals(row.getDirection())?row.getGrossAmount():row.getGrossAmount().negate());fee=fee.add(row.getFeeAmount());net=net.add("IN".equals(row.getDirection())?row.getNetAmount():row.getNetAmount().negate());var source=db.moneySource(row.getSourceType(),row.getSourceId());String issue=currentIssue(batch,row);if(issue!=null&&problem==null)problem=issue;if(source==null)missing=true;results.add(SettlementReconciliationItem.builder().settlementItemId(row.getId()).status(issue==null?"MATCHED":source==null?"MISSING":"MISMATCH").exceptionReason(issue).build());}
  if(gross.compareTo(batch.getDeclaredGross())!=0||fee.compareTo(batch.getDeclaredFee())!=0||net.compareTo(batch.getDeclaredNet())!=0)if(problem==null)problem="Batch totals mismatch";String status=problem==null?"MATCHED":missing?"MISSING":"MISMATCH";var attempt=SettlementReconciliationAttempt.builder().batchId(batch.getId()).attemptNo(db.nextAttemptNo(batch.getId())).requestKey(key).status(status).calculatedGross(gross).calculatedFee(fee).calculatedNet(net).exceptionReason(problem).performedBy(actor).build();one(db.insertAttempt(attempt));for(var result:results){result.setAttemptId(attempt.getId());one(db.insertAttemptItem(result));}one(db.reconcile(batch.getId(),gross,fee,net,problem==null?"SETTLED":"EXCEPTION",status,problem));}

 private String currentIssue(SettlementBatch batch,SettlementItem item){var source=db.moneySource(item.getSourceType(),item.getSourceId());if(source==null)return "Source money event is missing";if(!Objects.equals(source.getProviderTransactionId(),item.getProviderPaymentId()))return "Provider reference mismatch";if(!batch.getProvider().equals(norm(source.getProvider())))return "Provider mismatch";if(!batch.getCurrency().equals(norm(item.getCurrency()))||!batch.getCurrency().equals(norm(source.getCurrency())))return "Currency mismatch";if(source.getAmount().compareTo(item.getGrossAmount())!=0)return "Gross amount mismatch";if(("IN".equals(item.getDirection())&&!"EXTERNAL_IN".equals(source.getDirection()))||("OUT".equals(item.getDirection())&&!"EXTERNAL_OUT".equals(source.getDirection())))return "Direction mismatch";if(("IN".equals(item.getDirection())&&item.getGrossAmount().subtract(item.getFeeAmount()).compareTo(item.getNetAmount())!=0)||("OUT".equals(item.getDirection())&&item.getGrossAmount().add(item.getFeeAmount()).compareTo(item.getNetAmount())!=0))return "Item net amount mismatch";return null;}

 @Transactional public GatewayPayout payout(Long batchId,Payout r){var actor=access.actor();var batch=db.lockBatchById(batchId);req(batch!=null,"Settlement batch not found");requirePayoutReady(batch);var old=db.lockPayoutByBatch(batchId);if(old!=null){req(old.getProviderPayoutId().equals(r.providerPayoutId)&&old.getAmount().compareTo(r.amount)==0&&old.getCurrency().equals(norm(r.currency)),"Payout request conflicts with existing payout");return old;}String currency=norm(r.currency);BigDecimal amount=money(r.amount);req(batch.getCurrency().equals(currency),"Payout currency mismatch");req(batch.getCalculatedNet().compareTo(amount)==0,"Payout amount mismatch");var p=GatewayPayout.builder().batchId(batchId).provider(batch.getProvider()).providerPayoutId(r.providerPayoutId.trim()).currency(currency).amount(amount).status("COMPLETED").reconciliationStatus("MATCHED").expectedAt(r.expectedAt).paidAt(r.paidAt).bankReference(r.bankReference).postingBusinessDate(dates.postingDate()).confirmedBy(actor.id()).build();db.ensurePayout(p);var locked=db.lockPayout(batch.getProvider(),p.getProviderPayoutId());req(locked!=null,"Payout lock failed");req(locked.getBatchId().equals(batchId)&&locked.getAmount().compareTo(amount)==0&&locked.getCurrency().equals(currency),"Provider payout id conflict");one(transactions.insertTransaction(HotelTransactionRecord.builder().direction("INTERNAL_TRANSFER").amount(amount).currency(currency).sourceType("PROCESSOR_PAYOUT").sourceId(locked.getId()).businessReferenceType("SETTLEMENT_BATCH").businessReferenceId(batchId).paymentMethod("BANK_TRANSFER").channel("PROCESSOR_SETTLEMENT").provider(batch.getProvider()).providerTransactionId(p.getProviderPayoutId()).initiatorType("SYSTEM").operatorUserId(actor.id()).description("Processor payout to hotel bank").occurredAt(r.paidAt).businessDate(p.getPostingBusinessDate()).build()));audit(actor.id(),"CONFIRM_GATEWAY_PAYOUT",locked.getId());return locked;}
 private void requirePayoutReady(SettlementBatch b){req("SETTLED".equals(b.getStatus())&&"MATCHED".equals(b.getReconciliationStatus()),"Settlement batch has unresolved reconciliation exceptions");req(b.getCalculatedGross().compareTo(b.getDeclaredGross())==0&&b.getCalculatedFee().compareTo(b.getDeclaredFee())==0&&b.getCalculatedNet().compareTo(b.getDeclaredNet())==0,"Settlement totals are not confirmed");req(db.latestUnresolvedCount(b.getId())==0,"Settlement items have unresolved reconciliation exceptions");}

 @Transactional(readOnly=true)public SettlementView get(Long id){access.actor();req(db.batch(id)!=null,"Settlement batch not found");return view(id);}@Transactional(readOnly=true)public PageResult<SettlementBatch> list(Integer page,Integer size){access.actor();var w=pages.window(page,size,true);return pages.result(w,db.batches(w.offset(),pages.limit(w)),db.batchCount());}@Transactional(readOnly=true)public SettlementMetrics metrics(){access.actor();return db.metrics();}
 private SettlementView view(Long id){return SettlementView.builder().batch(db.batch(id)).items(db.items(id)).reconciliationHistory(db.attempts(id)).payout(db.payoutByBatch(id)).build();}private void same(SettlementBatch a,SettlementBatch b){req(a.getCurrency().equals(b.getCurrency())&&a.getDeclaredGross().compareTo(b.getDeclaredGross())==0&&a.getDeclaredFee().compareTo(b.getDeclaredFee())==0&&a.getDeclaredNet().compareTo(b.getDeclaredNet())==0,"Provider batch id conflicts with different settlement");}private void audit(Long actor,String action,Long id){one(audits.insert(SysAuditLog.builder().operatorId(actor).action(action).detail("Settlement "+id).build()));}
}
