package com.johnny.hotel.payroll;import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import com.johnny.hotel.payroll.PayrollModels.*;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController@RequestMapping("/api/payroll")@RequiredArgsConstructor public class PayrollController{private final PayrollService service;
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PostMapping("/compensations")public Result<Compensation> compensation(@RequestBody PayrollCommands.CompensationCreate c){return Result.success(service.compensation(c));}
 @PreAuthorize("isAuthenticated()")@GetMapping("/compensations/{employee}")public Result<PageResult<Compensation>> compensation(@PathVariable Long employee,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(service.compensationHistory(employee,page,pageSize));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PostMapping("/compensations/{id}/deactivate")public Result<Compensation> deactivate(@PathVariable Long id){return Result.success(service.deactivateCompensation(id));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','FINANCE','OWNER','SUPER_ADMIN')")@GetMapping("/policy")public Result<Policy> policy(){return Result.success(service.currentPolicy());}
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PutMapping("/policy")public Result<Policy> policy(@RequestBody PayrollCommands.PolicyWrite c){return Result.success(service.policy(c));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PostMapping("/periods")public Result<Period> create(@RequestBody PayrollCommands.PeriodCreate c){return Result.success(service.createPeriod(c));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PostMapping("/periods/{id}/calculate")public Result<Period> calculate(@PathVariable Long id){return Result.success(service.calculate(id));}
 @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')")@PostMapping("/periods/{id}/approve")public Result<Period> approve(@PathVariable Long id){return Result.success(service.approve(id));}
 @PreAuthorize("hasAnyRole('OWNER','SUPER_ADMIN')")@PostMapping("/periods/{id}/close")public Result<Period> close(@PathVariable Long id){return Result.success(service.close(id));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','FINANCE','OWNER','SUPER_ADMIN')")@GetMapping("/periods")public Result<PageResult<Period>> periods(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(service.periods(page,pageSize));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','FINANCE','OWNER','SUPER_ADMIN')")@GetMapping("/periods/{id}")public Result<Period> period(@PathVariable Long id){return Result.success(service.period(id));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','FINANCE','OWNER','SUPER_ADMIN')")@GetMapping("/periods/{id}/payslips")public Result<PageResult<Payslip>> payslips(@PathVariable Long id,@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(service.payslips(id,page,pageSize));}
 @PreAuthorize("hasAnyRole('HR_ADMIN','OWNER','SUPER_ADMIN')")@PostMapping("/payslips/{id}/adjustments")public Result<Adjustment> adjustment(@PathVariable Long id,@RequestBody PayrollCommands.AdjustmentCreate c){return Result.success(service.adjustment(id,c));}
 @PreAuthorize("hasAnyRole('FINANCE','OWNER','SUPER_ADMIN')")@PostMapping("/payslips/{id}/pay")public Result<Payslip> pay(@PathVariable Long id,@RequestBody PayrollCommands.PaymentConfirm c){return Result.success(service.pay(id,c));}
 @PreAuthorize("isAuthenticated()")@GetMapping("/payslips/mine")public Result<PageResult<Payslip>> mine(@RequestParam(defaultValue="1")Integer page,@RequestParam(defaultValue="20")Integer pageSize){return Result.success(service.mine(page,pageSize));}
 @PreAuthorize("isAuthenticated()")@GetMapping("/payslips/{id}")public Result<Payslip> detail(@PathVariable Long id){return Result.success(service.detail(id));}
}
