package com.johnny.hotel.payroll;

import com.johnny.hotel.HotelBackendApplication;
import com.johnny.hotel.exception.BusinessException;
import com.johnny.hotel.support.WalletDevelopmentGuard;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.*;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(classes=HotelBackendApplication.class,properties={"hotel.wallet.dev.fixture=true","logging.level.org.springframework=WARN","logging.level.com.johnny=WARN"})
@EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
@TestInstance(TestInstance.Lifecycle.PER_CLASS) @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PayrollDevelopmentTest {
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){var e=WalletDevelopmentGuard.settings();r.add("spring.datasource.url",WalletDevelopmentGuard::url);r.add("spring.datasource.username",()->e.get("DB_USERNAME"));r.add("spring.datasource.password",()->e.get("DB_PASSWORD"));r.add("spring.data.redis.password",()->e.get("REDIS_PASSWORD"));}
 @Autowired JdbcTemplate jdbc; @Autowired PayrollService payroll; @Autowired org.flywaydb.core.Flyway flyway;
 String run="pay_"+UUID.randomUUID().toString().replace("-","").substring(0,10); int year=2200+Math.abs(run.hashCode()%500); long department,hr,owner,finance,monthly,hourly,missing,customer,inactive,plain,manager,superAdmin;
 long user(String suffix,String role){jdbc.update("INSERT INTO sys_user(department_id,username,password,real_name,email,status) VALUES(?,?,?,?,?,1)",department,run+suffix,"test",suffix,run+suffix+"@example.test");long id=jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,run+suffix);jdbc.update("INSERT INTO sys_user_role(user_id,role_id) SELECT ?,id FROM sys_role WHERE role_code=?",id,role);return id;}
 void as(long id,String role){var a=new UsernamePasswordAuthenticationToken(run,"n/a",List.of(new SimpleGrantedAuthority("ROLE_"+role)));a.setDetails(id);SecurityContextHolder.getContext().setAuthentication(a);}
 PayrollCommands.CompensationCreate comp(long employee,String type,String amount,LocalDate from,LocalDate to){var c=new PayrollCommands.CompensationCreate();c.setEmployeeId(employee);c.setPayType(type);c.setCurrency("CAD");if("MONTHLY".equals(type))c.setBaseAmount(new BigDecimal(amount));else c.setHourlyRate(new BigDecimal(amount));c.setEffectiveFrom(from);c.setEffectiveTo(to);c.setReason("Contracted compensation");return c;}
 PayrollCommands.PeriodCreate period(LocalDateTime start,LocalDateTime end,String key,Long...employees){var c=new PayrollCommands.PeriodCreate();c.setPeriodStart(start);c.setPeriodEnd(end);c.setCurrency("CAD");c.setRequestKey(run+key);c.setEmployeeIds(List.of(employees));return c;}
 @BeforeAll void seed(){assertEquals("61",flyway.info().current().getVersion().getVersion());jdbc.update("INSERT INTO department(name,status) VALUES(?,1)",run+"dept");department=jdbc.queryForObject("SELECT id FROM department WHERE name=?",Long.class,run+"dept");hr=user("hr","HR_ADMIN");owner=user("owner","OWNER");finance=user("finance","FINANCE");monthly=user("monthly","STAFF");hourly=user("hourly","STAFF");missing=user("missing","STAFF");manager=user("manager","MANAGER");superAdmin=user("super","SUPER_ADMIN");customer=user("customer","CUSTOMER");plain=user("plain","CUSTOMER");jdbc.update("DELETE FROM sys_user_role WHERE user_id=?",plain);inactive=user("inactive","STAFF");jdbc.update("UPDATE sys_user SET status=0 WHERE id=?",inactive);}
 @AfterEach void clear(){SecurityContextHolder.clearContext();}

 @Test @Order(1) void compensationVersionsPolicyAndOverlap(){as(hr,"HR_ADMIN");payroll.compensation(comp(monthly,"MONTHLY","5000.00",LocalDate.of(year,1,1),LocalDate.of(year,3,31)));payroll.compensation(comp(monthly,"MONTHLY","5500.00",LocalDate.of(year,4,1),null));assertThrows(BusinessException.class,()->payroll.compensation(comp(monthly,"MONTHLY","5200.00",LocalDate.of(year,3,1),LocalDate.of(year,5,1))));payroll.compensation(comp(hourly,"HOURLY","25.00",LocalDate.of(year,1,1),null));var p=new PayrollCommands.PolicyWrite();p.setMonthlyUnpaidMode("STANDARD_DAYS");p.setHourlyPaidLeaveMode("HOURLY_RATE");p.setStandardDays(new BigDecimal("20"));p.setStandardHoursPerDay(new BigDecimal("8"));p.setRoundingMode("HALF_UP");assertTrue(payroll.policy(p).getVersionNo()>0);assertEquals(2,payroll.compensationHistory(monthly,1,20).getTotal());}

 @Test @Order(2) void monthlyHourlySnapshotsAdjustmentsAndIdempotentCalculate(){jdbc.update("INSERT INTO attendance_session(employee_id,status,effective_check_in,effective_check_out) VALUES(?,1,?,?)",hourly,LocalDateTime.of(year,2,1,9,0),LocalDateTime.of(year,2,1,17,0));as(hr,"HR_ADMIN");var p=payroll.createPeriod(period(LocalDateTime.of(year,2,1,0,0),LocalDateTime.of(year,3,1,0,0),"p1",monthly,hourly));payroll.calculate(p.getId());assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_payslip WHERE payroll_period_id=?",Integer.class,p.getId()));long ms=jdbc.queryForObject("SELECT id FROM payroll_payslip WHERE payroll_period_id=? AND employee_id=?",Long.class,p.getId(),monthly);long hs=jdbc.queryForObject("SELECT id FROM payroll_payslip WHERE payroll_period_id=? AND employee_id=?",Long.class,p.getId(),hourly);assertEquals(0,new BigDecimal("5000.00").compareTo(jdbc.queryForObject("SELECT net_pay FROM payroll_payslip WHERE id=?",BigDecimal.class,ms)));assertEquals(0,new BigDecimal("200.00").compareTo(jdbc.queryForObject("SELECT attendance_based_pay FROM payroll_payslip WHERE id=?",BigDecimal.class,hs)));var a=new PayrollCommands.AdjustmentCreate();a.setType("BONUS");a.setDirection("ADD");a.setAmount(new BigDecimal("100.00"));a.setReason("Approved bonus");a.setRequestKey(run+"bonus");payroll.adjustment(ms,a);payroll.calculate(p.getId());payroll.calculate(p.getId());assertEquals(0,new BigDecimal("5100.00").compareTo(jdbc.queryForObject("SELECT net_pay FROM payroll_payslip WHERE id=?",BigDecimal.class,ms)));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_payslip WHERE payroll_period_id=?",Integer.class,p.getId()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_adjustment WHERE payslip_id=?",Integer.class,ms));}

 @Test @Order(3) void missingCompensationAndMissingPolicyBlockInsteadOfZero(){as(hr,"HR_ADMIN");var noRules=new PayrollCommands.PolicyWrite();noRules.setRoundingMode("HALF_UP");payroll.policy(noRules);long unpaidType; jdbc.update("INSERT INTO leave_type(code,name,unit,paid_treatment,requires_balance,requires_attachment,active,created_by,updated_by) VALUES(?,?,?,?,0,0,1,?,?)",run+"UNPAID","Unpaid","DAY","UNPAID",hr,hr);unpaidType=jdbc.queryForObject("SELECT id FROM leave_type WHERE code=?",Long.class,run+"UNPAID");jdbc.update("INSERT INTO employee_leave_request(employee_id,leave_type_id,start_at,end_at,requested_amount,reason,status,request_key,decided_by,decided_at) VALUES(?,?,?,?,?,'Approved unpaid',2,?,?,NOW(6))",monthly,unpaidType,LocalDateTime.of(year,4,2,0,0),LocalDateTime.of(year,4,3,0,0),BigDecimal.ONE,run+"leave",hr);var p=payroll.createPeriod(period(LocalDateTime.of(year,4,1,0,0),LocalDateTime.of(year,5,1,0,0),"p2",monthly,missing));payroll.calculate(p.getId());assertEquals("MISSING_MONTHLY_UNPAID_LEAVE_POLICY",jdbc.queryForObject("SELECT blocked_reason FROM payroll_payslip WHERE payroll_period_id=? AND employee_id=?",String.class,p.getId(),monthly));assertEquals("NO_ACTIVE_COMPENSATION_PROFILE",jdbc.queryForObject("SELECT blocked_reason FROM payroll_payslip WHERE payroll_period_id=? AND employee_id=?",String.class,p.getId(),missing));as(owner,"OWNER");assertThrows(BusinessException.class,()->payroll.approve(p.getId()));}

 @Test @Order(4) void approvalPaymentExpenseAndExternalOutExactlyOnce(){as(hr,"HR_ADMIN");var rules=new PayrollCommands.PolicyWrite();rules.setMonthlyUnpaidMode("STANDARD_DAYS");rules.setHourlyPaidLeaveMode("HOURLY_RATE");rules.setStandardDays(new BigDecimal("20"));rules.setStandardHoursPerDay(new BigDecimal("8"));rules.setRoundingMode("HALF_UP");payroll.policy(rules);var p=payroll.createPeriod(period(LocalDateTime.of(year,5,1,0,0),LocalDateTime.of(year,6,1,0,0),"p3",monthly));payroll.calculate(p.getId());long slip=jdbc.queryForObject("SELECT id FROM payroll_payslip WHERE payroll_period_id=?",Long.class,p.getId());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_expense WHERE category='PAYROLL' AND reference_no=?",Integer.class,"PAYSLIP-"+slip));as(owner,"OWNER");payroll.approve(p.getId());as(finance,"FINANCE");var pay=new PayrollCommands.PaymentConfirm();pay.setMethod("BANK_TRANSFER");pay.setExternalReference(run+"bank");pay.setRequestKey(run+"payment");var paid=payroll.pay(slip,pay);payroll.pay(slip,pay);assertEquals(3,paid.getStatus());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_payment WHERE payslip_id=?",Integer.class,slip));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_transaction_record WHERE source_type='EXPENSE' AND source_id=? AND direction='EXTERNAL_OUT'",Integer.class,paid.getExpenseId()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_expense WHERE id=? AND category='PAYROLL' AND status=3",Integer.class,paid.getExpenseId()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM revenue_recognition WHERE source_type='EXPENSE' AND source_id=?",Integer.class,paid.getExpenseId()));long earlier=jdbc.queryForObject("SELECT id FROM payroll_period WHERE request_key=?",Long.class,run+"p1");as(owner,"OWNER");payroll.approve(earlier);long unpaidSlip=jdbc.queryForObject("SELECT id FROM payroll_payslip WHERE payroll_period_id=? AND employee_id=?",Long.class,earlier,hourly);as(finance,"FINANCE");var cash=new PayrollCommands.PaymentConfirm();cash.setMethod("CASH");cash.setRequestKey(run+"cash");assertThrows(BusinessException.class,()->payroll.pay(unpaidSlip,cash));}

 @Test @Order(5) void salaryPrivacyAndPublishedOwnPayslip(){long paidSlip=jdbc.queryForObject("SELECT pp.id FROM payroll_payslip pp JOIN payroll_period p ON p.id=pp.payroll_period_id WHERE pp.employee_id=? AND pp.status=3 ORDER BY pp.id DESC LIMIT 1",Long.class,monthly);long leaveType=jdbc.queryForObject("SELECT id FROM leave_type WHERE code=?",Long.class,run+"UNPAID");jdbc.update("INSERT INTO employee_leave_request(employee_id,leave_type_id,start_at,end_at,requested_amount,reason,status,request_key,decided_by,decided_at) VALUES(?,?,?,?,?,'Post payroll correction',2,?,?,NOW(6))",monthly,leaveType,LocalDateTime.of(year,5,10,0,0),LocalDateTime.of(year,5,11,0,0),BigDecimal.ONE,run+"postpay",hr);as(monthly,"STAFF");assertEquals(paidSlip,payroll.detail(paidSlip).getId());assertTrue(payroll.detail(paidSlip).getSourceChangeDetected());as(hourly,"STAFF");assertThrows(AccessDeniedException.class,()->payroll.detail(paidSlip));assertThrows(AccessDeniedException.class,()->payroll.compensationHistory(monthly,1,20));as(finance,"FINANCE");assertNotNull(payroll.detail(paidSlip).getExpenseId());assertThrows(AccessDeniedException.class,()->payroll.compensation(comp(hourly,"HOURLY","30.00",LocalDate.of(year+1,1,1),null)));}
 @Test @Order(6) void onlyActiveInternalEmployeesAndBatchIsAtomic(){as(hr,"HR_ADMIN");LocalDate from=LocalDate.of(year+1,1,1);for(long invalid:new long[]{customer,inactive,plain})assertThrows(BusinessException.class,()->payroll.compensation(comp(invalid,"MONTHLY","1000.00",from,null)));for(long valid:new long[]{manager,hr,finance,owner,superAdmin})assertDoesNotThrow(()->payroll.compensation(comp(valid,"MONTHLY","1000.00",from,null)));var mixed=period(LocalDateTime.of(year+1,1,1,0,0),LocalDateTime.of(year+1,2,1,0,0),"invalid-batch",monthly,customer);assertThrows(BusinessException.class,()->payroll.createPeriod(mixed));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_period WHERE request_key=?",Integer.class,run+"invalid-batch"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_payslip WHERE employee_id IN (?,?,?)",Integer.class,customer,inactive,plain));long historical=jdbc.queryForObject("SELECT id FROM payroll_payslip WHERE employee_id=? AND status=3 ORDER BY id DESC LIMIT 1",Long.class,monthly);jdbc.update("UPDATE sys_user SET status=0 WHERE id=?",monthly);assertEquals(historical,payroll.detail(historical).getId());jdbc.update("UPDATE sys_user SET status=1 WHERE id=?",monthly);}
 @Test @Order(7) void concurrentPayExactlyOnceAndPartialPeriodWaitsForAllPayslips()throws Exception{as(hr,"HR_ADMIN");payroll.compensation(comp(missing,"MONTHLY","2000.00",LocalDate.of(year,7,1),null));var p=payroll.createPeriod(period(LocalDateTime.of(year,7,1,0,0),LocalDateTime.of(year,8,1,0,0),"p4",monthly,missing));payroll.calculate(p.getId());as(owner,"OWNER");payroll.approve(p.getId());var slips=jdbc.queryForList("SELECT id FROM payroll_payslip WHERE payroll_period_id=? ORDER BY id",Long.class,p.getId());long first=slips.get(0),second=slips.get(1);var request=new PayrollCommands.PaymentConfirm();request.setMethod("BANK_TRANSFER");request.setExternalReference(run+"concurrent-bank");request.setRequestKey(run+"concurrent-pay");var pool=Executors.newFixedThreadPool(2);try{Callable<Object> call=()->{as(finance,"FINANCE");try{return payroll.pay(first,request);}catch(Throwable e){return e;}finally{SecurityContextHolder.clearContext();}};var a=pool.submit(call);var b=pool.submit(call);assertFalse(a.get(20,TimeUnit.SECONDS) instanceof Throwable);assertFalse(b.get(20,TimeUnit.SECONDS) instanceof Throwable);}finally{pool.shutdownNow();}assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM payroll_payment WHERE payslip_id=?",Integer.class,first));long expense=jdbc.queryForObject("SELECT expense_id FROM payroll_payment WHERE payslip_id=?",Long.class,first);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_expense WHERE id=? AND category='PAYROLL'",Integer.class,expense));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM hotel_transaction_record WHERE source_type='EXPENSE' AND source_id=? AND direction='EXTERNAL_OUT'",Integer.class,expense));assertEquals(2,jdbc.queryForObject("SELECT status FROM payroll_period WHERE id=?",Integer.class,p.getId()));as(owner,"OWNER");assertThrows(BusinessException.class,()->payroll.close(p.getId()));as(finance,"FINANCE");var secondPay=new PayrollCommands.PaymentConfirm();secondPay.setMethod("OTHER");secondPay.setRequestKey(run+"second-pay");payroll.pay(second,secondPay);assertEquals(3,jdbc.queryForObject("SELECT status FROM payroll_period WHERE id=?",Integer.class,p.getId()));as(owner,"OWNER");assertEquals(4,payroll.close(p.getId()).getStatus());}}
