package com.johnny.hotel.cleaning;
import com.johnny.hotel.entity.*;import com.johnny.hotel.enums.BookingStatus;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.inspection.*;import com.johnny.hotel.mapper.*;import com.johnny.hotel.task.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
@Service @RequiredArgsConstructor public class CleaningServiceImpl implements CleaningService {
 private final CleaningMapper cleaning;private final BookingMapper bookings;private final BookingRoomAssignmentMapper assignments;private final RoomTurnoverTaskMapper turnover;private final HotelTaskService tasks;private final TaskRecordMapper records;private final HousekeepingAccess access;private final InspectionService inspections;private final Clock clock;
 private LocalDateTime now(){return LocalDateTime.now(clock).truncatedTo(ChronoUnit.MICROS);}private void require(boolean v,String m){if(!v)throw new BusinessException(m);}private void one(int n){require(n==1,"Cleaning operation failed");}
 @Override @Transactional public StayoverCleaningRequest requestStayover(Long bookingId,CleaningRequests.Create r,Long actor,boolean customer){if(customer)access.customer(actor);else access.employee(actor);require(r!=null&&r.getRequestKey()!=null&&!r.getRequestKey().isBlank(),"Request key is required");String key=r.getRequestKey().trim();require(key.length()<=60,"Request key must be at most 60 characters");var booking=bookings.selectByIdForUpdate(bookingId);require(booking!=null,"Booking does not exist");if(customer&&!booking.getUserId().equals(actor))throw new BusinessException(404,"Resource not found");require(booking.getStatus()==BookingStatus.CHECKED_IN.getCode(),"Stayover cleaning requires a checked-in booking");var assignment=assignments.selectActiveByBookingId(bookingId);require(assignment!=null,"Stayover cleaning requires an active assignment");var old=cleaning.requestByKey(actor,key);if(old!=null){require(old.getBookingId().equals(bookingId),"Request key already represents another cleaning request");return old;}var task=tasks.createCleaning(bookingId,assignment.getRoomId(),assignment.getId(),"ROOM_CLEANING:"+actor+":"+key,r.getNotes(),actor);var request=StayoverCleaningRequest.builder().taskId(task.getId()).bookingId(bookingId).assignmentId(assignment.getId()).roomId(assignment.getRoomId()).requestedBy(actor).requestKey(key).requestedTime(now()).build();one(cleaning.insertRequest(request));return request;}
 @Override @Transactional public CleaningRecord complete(Long taskId,String note,boolean force){access.current();var rw=cleaning.reworkByTask(taskId);if(rw!=null)return completeRework(rw,note,force);var c=cleaning.requestByTask(taskId);require(c!=null,"Cleaning request does not exist");var old=cleaning.byTask(taskId);if(old!=null)return old;var b=bookings.selectByIdForUpdate(c.getBookingId());require(b!=null&&b.getStatus()==BookingStatus.CHECKED_IN.getCode(),"Stayover cleaning can only complete during the active stay");var active=assignments.selectActiveByBookingId(c.getBookingId());require(active!=null&&active.getId().equals(c.getAssignmentId())&&active.getRoomId().equals(c.getRoomId()),"Stayover assignment is no longer active");Long actor=access.current().id();tasks.completeCleaning(taskId,note,force);var record=record(c,CleaningType.STAYOVER,actor,note);one(cleaning.insertRecord(record));return record;}
 private CleaningRecord completeRework(ReworkCleaningRequest c,String note,boolean force){var old=cleaning.byTask(c.getTaskId());if(old!=null)return old;Long actor=access.current().id();tasks.completeCleaning(c.getTaskId(),note,force);var r=CleaningRecord.builder().roomId(c.getRoomId()).bookingId(c.getBookingId()).assignmentId(c.getAssignmentId()).taskId(c.getTaskId()).cleaningType(CleaningType.REWORK.getCode()).requestedBy(c.getRequestedBy()).completedBy(actor).startedTime(cleaning.started(c.getTaskId())).completedTime(now()).notes(normalize(note)).build();one(cleaning.insertRecord(r));inspections.createForRework(r,c.getInspectionId());return r;}
 @Override @Transactional public void cancel(Long taskId,String note){access.current();require(cleaning.reworkByTask(taskId)==null,"Rework cleaning cannot be cancelled");var c=cleaning.requestByTask(taskId);require(c!=null,"Stayover cleaning request does not exist");require(cleaning.byTask(taskId)==null,"Completed cleaning cannot be cancelled");tasks.cancelCleaning(taskId,note);}
 @Override @Transactional public CleaningRecord completeTurnover(Long taskId,String note){var t=turnover.lockByTask(taskId);require(t!=null,"Turnover task does not exist");var old=cleaning.byTask(taskId);if(old!=null)return old;var a=access.current();tasks.completeCleaning(taskId,note,a.manager());var r=CleaningRecord.builder().roomId(t.getRoomId()).bookingId(t.getBookingId()).assignmentId(t.getAssignmentId()).taskId(taskId).cleaningType(CleaningType.TURNOVER.getCode()).completedBy(a.id()).startedTime(cleaning.started(taskId)).completedTime(now()).notes(normalize(note)).build();one(cleaning.insertRecord(r));inspections.createForTurnover(r,t.getId());return r;}
 private CleaningRecord record(StayoverCleaningRequest c,CleaningType type,Long actor,String note){return CleaningRecord.builder().roomId(c.getRoomId()).bookingId(c.getBookingId()).assignmentId(c.getAssignmentId()).taskId(c.getTaskId()).cleaningType(type.getCode()).requestedBy(c.getRequestedBy()).completedBy(actor).requestedTime(c.getRequestedTime()).startedTime(cleaning.started(c.getTaskId())).completedTime(now()).notes(normalize(note)).build();}
 private String normalize(String n){if(n==null||n.isBlank())return null;String v=n.trim();require(v.length()<=500,"Notes must be at most 500 characters");return v;}
 public List<CleaningRecord> customerHistory(Long b,Long u){access.customer(u);var booking=bookings.selectById(b);if(booking==null||!booking.getUserId().equals(u))throw new BusinessException(404,"Resource not found");return cleaning.stayoverByBooking(b);}public List<CleaningRecord> roomHistory(Long id){access.current();return cleaning.byRoom(id);}public List<CleaningRecord> bookingHistory(Long id){access.current();return cleaning.byBooking(id);}public List<CleaningRecord> assignmentHistory(Long id){access.current();return cleaning.byAssignment(id);}public CleaningRecord get(Long id){access.current();var r=cleaning.find(id);if(r==null)throw new BusinessException(404,"Cleaning record does not exist");return r;}
}
