package com.johnny.hotel.cleaning;import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.time.*;
@RestController @RequestMapping("/api/housekeeping") @RequiredArgsConstructor @PreAuthorize("hasAnyRole('STAFF','MANAGER','OWNER','SUPER_ADMIN')") public class HousekeepingController{private final CleaningService service;private Long id(Authentication a){return(Long)a.getDetails();}
 @PostMapping("/bookings/{bookingId}/cleaning-requests")public Result<StayoverCleaningRequest> request(@PathVariable Long bookingId,@Valid @RequestBody CleaningRequests.Create r,Authentication a){return Result.success(service.requestStayover(bookingId,r,id(a),false));}
 @PostMapping("/tasks/{taskId}/complete")public Result<CleaningRecord> complete(@PathVariable Long taskId,@Valid @RequestBody(required=false)CleaningRequests.Complete r){return Result.success(service.complete(taskId,r==null?null:r.getNotes(),r!=null&&Boolean.TRUE.equals(r.getForce())));}
 @PostMapping("/tasks/{taskId}/cancel")public Result<Void> cancel(@PathVariable Long taskId,@Valid @RequestBody(required=false)CleaningRequests.Cancel r){service.cancel(taskId,r==null?null:r.getNotes());return Result.success(null);}
 @GetMapping("/cleaning-records")public Result<PageResult<CleaningRecord>> records(@RequestParam(required=false)Long roomId,@RequestParam(required=false)Long bookingId,@RequestParam(required=false)Long assignmentId,@RequestParam(required=false)Long employeeId,@RequestParam(required=false)Integer type,@RequestParam(required=false)LocalDateTime from,@RequestParam(required=false)LocalDateTime to,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.page(roomId,bookingId,assignmentId,employeeId,type,from,to,page,pageSize));}
 @GetMapping("/rooms/{roomId}/cleaning-records")public Result<PageResult<CleaningRecord>> room(@PathVariable Long roomId,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.page(roomId,null,null,null,null,null,null,page,pageSize));}
 @GetMapping("/bookings/{bookingId}/cleaning-records")public Result<PageResult<CleaningRecord>> booking(@PathVariable Long bookingId,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.page(null,bookingId,null,null,null,null,null,page,pageSize));}
 @GetMapping("/assignments/{assignmentId}/cleaning-records")public Result<PageResult<CleaningRecord>> assignment(@PathVariable Long assignmentId,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.page(null,null,assignmentId,null,null,null,null,page,pageSize));}
 @GetMapping("/cleaning-records/{id}")public Result<CleaningRecord> get(@PathVariable Long id){return Result.success(service.get(id));}
}
