package com.johnny.hotel.service.impl;
import com.johnny.hotel.entity.*; import com.johnny.hotel.exception.BusinessException; import com.johnny.hotel.mapper.*; import com.johnny.hotel.service.RoomTurnoverTaskService; import com.johnny.hotel.task.*;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import org.springframework.security.core.context.SecurityContextHolder; import java.util.*;
import static com.johnny.hotel.service.support.BillingRules.*;
@Service @RequiredArgsConstructor public class RoomTurnoverTaskServiceImpl implements RoomTurnoverTaskService {
 private final RoomTurnoverTaskMapper turnover; private final BookingMapper bookings; private final BookingRoomAssignmentMapper assignments; private final RoomMapper rooms; private final HotelTaskService hotelTasks; private final SysRoleMapper roles;
 @Override @Transactional(propagation=Propagation.MANDATORY) public RoomTurnoverTask createForClosedAssignment(Long id){var identity=turnover.assignmentIdentity(id);require(identity!=null,"Assignment does not exist");return createForClosedAssignment(id,identity.getCreatedBy());}
 @Override @Transactional(propagation=Propagation.MANDATORY) public RoomTurnoverTask createForClosedAssignment(Long id,Long actorId){var identity=turnover.assignmentIdentity(id);require(identity!=null,"Assignment does not exist");var booking=bookings.selectByIdForUpdate(identity.getBookingId());var room=rooms.selectByIdForUpdate(identity.getRoomId());var assignment=assignments.selectById(id);require(booking!=null&&room!=null&&assignment!=null&&assignment.getEndTime()!=null&&!assignment.getEndTime().isBefore(assignment.getStartTime())&&Set.of("CHECK_IN","ROOM_CHANGE").contains(assignment.getAssignmentType()),"A closed actual stay assignment is required");var existing=turnover.byAssignment(id);if(existing!=null){require(existing.getBookingId().equals(booking.getId())&&existing.getRoomId().equals(room.getId()),"Task assignment identity mismatch");return existing;}require(Set.of(2,3).contains(booking.getStatus())&&room.getStatus()==3,"Closed stay must leave its room in maintenance");require(assignments.selectByBookingId(booking.getId()).stream().anyMatch(a->"CHECK_IN".equals(a.getAssignmentType())),"Actual check-in history is missing");var core=hotelTasks.createTurnover(room.getId(),id,actorId);var task=RoomTurnoverTask.builder().taskId(core.getId()).bookingId(booking.getId()).roomId(room.getId()).assignmentId(id).build();one(turnover.insert(task));return turnover.find(task.getId());}
 @Override public List<RoomTurnoverTask> list(Integer status,Long roomId,Integer page,Integer size){require(status==null||(status>=0&&status<=2),"Invalid turnover status");hotelTasks.list(status,0,page,size);int p=page==null?1:page,s=size==null?50:size;return turnover.page(status,roomId,(p-1)*s,s);}
 @Override public RoomTurnoverTask get(Long id){var task=turnover.find(id);if(task==null)throw new BusinessException(404,"Turnover task does not exist");hotelTasks.get(task.getTaskId());return task;}
 @Override public RoomTurnoverTask accept(Long id){var task=get(id);var core=hotelTasks.get(task.getTaskId()).getTask();if(core.getAssignmentMode()==TaskAssignmentMode.CLAIMABLE.getCode())hotelTasks.claim(task.getTaskId());else hotelTasks.accept(task.getTaskId());return turnover.find(id);}
 @Override public RoomTurnoverTask complete(Long id,String note){var task=get(id);var auth=SecurityContextHolder.getContext().getAuthentication();Long actor=(Long)auth.getDetails();boolean manager=roles.selectRolesByUserId(actor).stream().map(SysRole::getRoleCode).anyMatch(Set.of("MANAGER","OWNER","SUPER_ADMIN")::contains);if(manager)hotelTasks.forceComplete(task.getTaskId(),note);else hotelTasks.complete(task.getTaskId(),note);return turnover.find(id);}
}
