package com.johnny.hotel.cashier;import com.johnny.hotel.cashier.CashierModels.*;import org.apache.ibatis.annotations.*;import java.math.*;import java.time.*;import java.util.*;
@Mapper public interface CashierMapper{
 @Insert("INSERT INTO cash_drawer(code,name,currency,created_by) VALUES(#{code},#{name},#{currency},#{createdBy})")@Options(useGeneratedKeys=true,keyProperty="id")int insertDrawer(Drawer d);@Select("SELECT * FROM cash_drawer WHERE id=#{id}")Drawer drawer(Long id);@Select("SELECT * FROM cash_drawer WHERE id=#{id} FOR UPDATE")Drawer lockDrawer(Long id);
 @Insert("INSERT INTO cashier_shift(drawer_id,operator_user_id,status,opening_count,opened_at,opening_business_date) VALUES(#{drawerId},#{operatorUserId},'ACTIVE',#{openingCount},#{openedAt},#{openingBusinessDate})")@Options(useGeneratedKeys=true,keyProperty="id")int insertShift(Shift s);
 @Update("UPDATE cash_drawer SET active_shift_id=#{shift} WHERE id=#{drawer} AND active_shift_id IS NULL")int activate(@Param("drawer")Long drawer,@Param("shift")Long shift);@Update("UPDATE cash_drawer SET active_shift_id=NULL WHERE id=#{drawer} AND active_shift_id=#{shift}")int deactivate(@Param("drawer")Long drawer,@Param("shift")Long shift);
 @Select("SELECT * FROM cashier_shift WHERE id=#{id}")Shift shift(Long id);@Select("SELECT * FROM cashier_shift WHERE id=#{id} FOR UPDATE")Shift lockShift(Long id);@Select("SELECT * FROM cashier_shift WHERE operator_user_id=#{operator} AND status IN('ACTIVE','CLOSING') ORDER BY id DESC LIMIT 1 FOR UPDATE")Shift activeByOperator(Long operator);
 @Select("SELECT * FROM cashier_shift WHERE drawer_id=#{drawer} AND status='CLOSED' ORDER BY id DESC LIMIT 1")Shift previous(Long drawer);
 @Update("UPDATE cashier_shift SET status='CLOSING',closing_count=#{counted} WHERE id=#{id} AND status IN('ACTIVE','CLOSING')")int countClose(@Param("id")Long id,@Param("counted")BigDecimal counted);
 @Update("UPDATE cashier_shift SET status='CLOSED',expected_closing=#{expected},closing_count=#{counted},closing_variance=#{variance},closing_business_date=#{date},closed_at=#{at} WHERE id=#{id} AND status='CLOSING'")int close(@Param("id")Long id,@Param("expected")BigDecimal expected,@Param("counted")BigDecimal counted,@Param("variance")BigDecimal variance,@Param("date")LocalDate date,@Param("at")LocalDateTime at);
 @Select("SELECT opening_count+COALESCE(SUM(CASE WHEN m.direction='IN' THEN m.amount ELSE -m.amount END),0) FROM cashier_shift s LEFT JOIN cash_drawer_movement m ON m.shift_id=s.id WHERE s.id=#{id} GROUP BY s.id")BigDecimal expected(Long id);
 @Insert("INSERT INTO cash_drawer_movement(drawer_id,shift_id,direction,movement_type,amount,currency,source_type,source_id,request_key,operator_user_id,occurred_at,posting_business_date,note) VALUES(#{drawerId},#{shiftId},#{direction},#{movementType},#{amount},#{currency},#{sourceType},#{sourceId},#{requestKey},#{operatorUserId},#{occurredAt},#{postingBusinessDate},#{note})")@Options(useGeneratedKeys=true,keyProperty="id")int insertMovement(Movement m);
 @Select("SELECT * FROM cash_drawer_movement WHERE source_type=#{type} AND source_id=#{id}")Movement movementBySource(@Param("type")String type,@Param("id")Long id);
 @Insert("INSERT INTO cash_variance(shift_id,expected_amount,counted_amount,difference_amount,variance_type,reason,recorded_by) VALUES(#{shiftId},#{expectedAmount},#{countedAmount},#{differenceAmount},#{varianceType},#{reason},#{recordedBy})")@Options(useGeneratedKeys=true,keyProperty="id")int insertVariance(Variance v);@Select("SELECT * FROM cash_variance WHERE shift_id=#{id}")Variance variance(Long id);@Select("SELECT * FROM cash_variance WHERE id=#{id} FOR UPDATE")Variance lockVariance(Long id);
 @Update("UPDATE cash_variance SET status='REVIEWED',reviewed_by=#{actor},reviewed_at=#{at},resolution_note=#{note} WHERE id=#{id} AND status='OPEN'")int reviewVariance(@Param("id")Long id,@Param("actor")Long actor,@Param("at")LocalDateTime at,@Param("note")String note);
 @Insert("INSERT INTO cash_handover(drawer_id,previous_shift_id,next_shift_id,previous_closing_count,next_opening_count,difference_amount,recorded_by) VALUES(#{drawerId},#{previousShiftId},#{nextShiftId},#{previousClosingCount},#{nextOpeningCount},#{differenceAmount},#{recordedBy})")@Options(useGeneratedKeys=true,keyProperty="id")int insertHandover(Handover h);@Select("SELECT * FROM cash_handover WHERE next_shift_id=#{id}")Handover handover(Long id);
 @Insert("INSERT INTO cash_transfer_request(drawer_id,shift_id,task_id,request_type,amount,currency,request_key,requested_by,note) VALUES(#{drawerId},#{shiftId},#{taskId},#{requestType},#{amount},#{currency},#{requestKey},#{requestedBy},#{note})")@Options(useGeneratedKeys=true,keyProperty="id")int insertTransfer(Transfer t);@Select("SELECT * FROM cash_transfer_request WHERE request_key=#{key}")Transfer transferByKey(String key);@Select("SELECT * FROM cash_transfer_request WHERE id=#{id} FOR UPDATE")Transfer lockTransfer(Long id);
 @Update("UPDATE cash_transfer_request SET status='COMPLETED',confirmed_by=#{actor},confirmed_at=#{at} WHERE id=#{id} AND status='PENDING'")int completeTransfer(@Param("id")Long id,@Param("actor")Long actor,@Param("at")LocalDateTime at);@Update("UPDATE cash_transfer_request SET status='CANCELLED' WHERE id=#{id} AND status='PENDING'")int cancelTransfer(Long id);
 @Select("SELECT * FROM cashier_shift ORDER BY id DESC LIMIT #{offset},#{size}")List<Shift> shifts(@Param("offset")int offset,@Param("size")int size);@Select("SELECT COUNT(*) FROM cashier_shift")long shiftCount();
}
