package com.johnny.hotel.cms;
import com.johnny.hotel.cms.CmsModels.*;import com.johnny.hotel.common.Result;import com.johnny.hotel.pagination.PageResult;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController@RequiredArgsConstructor@RequestMapping("/api/admin/cms")@PreAuthorize("hasAnyRole('MANAGER','OWNER','SUPER_ADMIN')") public class CmsAdminController{private final CmsService service;
 @GetMapping("/pages")public Result<PageResult<Page>>pages(@RequestParam(required=false)String locale,@RequestParam(required=false)String query,@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.pages(locale,query,page,pageSize));}
 @PostMapping("/pages")public Result<PageView>create(@Valid@RequestBody CmsRequests.PageCreate r){return Result.success(service.create(r));}@PutMapping("/pages/{id}")public Result<PageView>edit(@PathVariable Long id,@Valid@RequestBody CmsRequests.PageEdit r){return Result.success(service.edit(id,r));}@GetMapping("/pages/{id}/preview")public Result<PageView>preview(@PathVariable Long id){return Result.success(service.preview(id));}@PostMapping("/pages/{id}/publish")public Result<PageView>publish(@PathVariable Long id){return Result.success(service.publish(id));}@PostMapping("/pages/{id}/unpublish")public Result<Void>unpublish(@PathVariable Long id){service.unpublish(id);return Result.success();}
 @PostMapping("/pages/{id}/sections")public Result<Section>section(@PathVariable Long id,@Valid@RequestBody CmsRequests.SectionWrite r){return Result.success(service.section(id,r,null));}@PutMapping("/pages/{page}/sections/{id}")public Result<Section>section(@PathVariable Long page,@PathVariable Long id,@Valid@RequestBody CmsRequests.SectionWrite r){return Result.success(service.section(page,r,id));}@DeleteMapping("/pages/{page}/sections/{id}")public Result<Void>delete(@PathVariable Long page,@PathVariable Long id){service.deleteSection(page,id);return Result.success();}@PostMapping("/pages/{id}/sections/reorder")public Result<PageView>reorder(@PathVariable Long id,@Valid@RequestBody CmsRequests.Reorder r){return Result.success(service.reorder(id,r));}
 @GetMapping("/navigation")public Result<PageResult<Navigation>>navs(@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.navs(page,pageSize));}@PostMapping("/navigation")public Result<Navigation>nav(@Valid@RequestBody CmsRequests.NavigationWrite r){return Result.success(service.navigation(null,r));}@PutMapping("/navigation/{id}")public Result<Navigation>nav(@PathVariable Long id,@Valid@RequestBody CmsRequests.NavigationWrite r){return Result.success(service.navigation(id,r));}
 @GetMapping("/promotions")public Result<PageResult<Promotion>>promos(@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.promotions(page,pageSize));}@PostMapping("/promotions")public Result<Promotion>promo(@Valid@RequestBody CmsRequests.PromotionWrite r){return Result.success(service.promotion(null,r));}@PutMapping("/promotions/{id}")public Result<Promotion>promo(@PathVariable Long id,@Valid@RequestBody CmsRequests.PromotionWrite r){return Result.success(service.promotion(id,r));}
 @PutMapping("/location")public Result<Location>location(@Valid@RequestBody CmsRequests.LocationWrite r){return Result.success(service.location(r));}
 @GetMapping("/scenes")public Result<PageResult<Scene>>scenes(@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.scenes(page,pageSize));}@PostMapping("/scenes")public Result<Scene>scene(@Valid@RequestBody CmsRequests.SceneWrite r){return Result.success(service.scene(null,r));}@PutMapping("/scenes/{id}")public Result<Scene>scene(@PathVariable Long id,@Valid@RequestBody CmsRequests.SceneWrite r){return Result.success(service.scene(id,r));}@PostMapping("/scenes/{id}/bindings")public Result<Binding>bind(@PathVariable Long id,@Valid@RequestBody CmsRequests.BindingWrite r){return Result.success(service.bind(id,r));}@GetMapping("/scenes/{id}")public Result<InternalScene>internal(@PathVariable Long id){return Result.success(service.internalScene(id));}
 @GetMapping("/media")public Result<PageResult<Media>>media(@RequestParam(required=false)Integer page,@RequestParam(required=false)Integer pageSize){return Result.success(service.media(page,pageSize));}@PostMapping(value="/media",consumes="multipart/form-data")public Result<Media>upload(@RequestParam String type,@RequestPart MultipartFile file){return Result.success(service.upload(type,file));}@PostMapping("/media/{id}/archive")public Result<Void>archive(@PathVariable Long id){service.archiveMedia(id);return Result.success();}
}
