package com.johnny.hotel.cms;
import lombok.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
public final class CmsModels {private CmsModels(){}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Page{Long id;String slug,locale;Long createdBy;LocalDateTime createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class PageVersion{Long id,pageId;Integer versionNo;String status,title,seoTitle,seoDescription;Long socialPreviewMediaId,createdBy,updatedBy;LocalDateTime publishedAt,createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Section{Long id,pageVersionId;String sectionKey,sectionType,payload,visibility,status;Integer sortOrder,version;LocalDateTime createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class PageView{Long id;String slug,locale,title,seoTitle,seoDescription;Long socialPreviewMediaId;Integer version;LocalDateTime publishedAt;List<Section> sections;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Navigation{Long id;String label,locale,targetType,targetValue,openMode,status;Integer sortOrder;Boolean visible;Long createdBy,updatedBy;LocalDateTime createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Promotion{Long id;String title,subtitle,description,locale,galleryMediaIds,status,ctaType,ctaTarget;Long coverMediaId,pricingPolicyId,createdBy,updatedBy;LocalDateTime startAt,endAt,createTime,updateTime;Integer priority;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Media{Long id;String assetType,storageKey,publicUrl,originalFilename,contentType,checksum,status;Long sizeBytes,posterMediaId,createdBy;Integer width,height;BigDecimal durationSeconds;LocalDateTime createTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Location{Long id;String locale,hotelName,address,phone,contact,displayMetadata,status;BigDecimal latitude,longitude;Long createdBy,updatedBy;LocalDateTime createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Scene{Long id;String name,locale,sceneType,visibility,interactionMode,cameraConfig,status;Long mediaAssetId,previewMediaId,createdBy,updatedBy;LocalDateTime createTime,updateTime;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class Binding{Long id,sceneId,roomId;String nodeKey,floorReference;}
 @Data@Builder@NoArgsConstructor@AllArgsConstructor public static class InternalScene{Scene scene;List<Binding> bindings;}
 public record PublicSection(String key,String type,Integer sortOrder,String payload){}public record PublicPage(String slug,String locale,String title,String seoTitle,String seoDescription,Long socialPreviewMediaId,Integer version,LocalDateTime publishedAt,List<PublicSection>sections){}public record PublicNavigation(String label,String targetType,String targetValue,Integer sortOrder,String openMode){}public record PublicPromotion(Long id,String title,String subtitle,String description,Long coverMediaId,String coverMediaUrl,String galleryMediaIds,List<String>galleryMediaUrls,LocalDateTime startAt,LocalDateTime endAt,Integer priority,String ctaType,String ctaTarget){}public record PublicLocation(String hotelName,String address,BigDecimal latitude,BigDecimal longitude,String phone,String contact,String displayMetadata){}public record PublicScene(Long id,String name,String sceneType,Long mediaAssetId,Long previewMediaId,String previewMediaUrl,String interactionMode,String cameraConfig){}
}

