package com.johnny.hotel;
import com.johnny.hotel.finance.*;import com.johnny.hotel.finance.FinanceOperationsModels.*;import com.johnny.hotel.financeexpense.HotelExpenseMapper;import com.johnny.hotel.pagination.*;import com.johnny.hotel.payment.HotelTransactionRecord;import org.junit.jupiter.api.*;import org.springframework.security.access.prepost.PreAuthorize;import java.math.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class FinanceOperationsServiceTest {
 private FinanceOperationsMapper db;private HotelExpenseMapper expenses;private com.johnny.hotel.ar.ArMapper ar;private FinanceOperationsService service;
 @BeforeEach void init(){db=mock(FinanceOperationsMapper.class);expenses=mock(HotelExpenseMapper.class);ar=mock(com.johnny.hotel.ar.ArMapper.class);when(ar.totalOutstanding()).thenReturn(BigDecimal.ZERO);var p=new PaginationProperties();p.setMaxPageSize(100);p.setBrowseLimit(100);service=new FinanceOperationsService(db,expenses,ar,new PaginationSupport(p));}
 @Test void dashboardKeepsRevenueAndRegisteredCashSeparate(){var from=LocalDate.of(2026,9,1);var to=LocalDate.of(2026,9,2);var row=Dashboard.builder().roomRevenue(new BigDecimal("100.00")).totalRecognizedRevenue(new BigDecimal("100.00")).externalInflow(new BigDecimal("300.00")).externalOutflow(new BigDecimal("20.00")).netExternalCashMovement(new BigDecimal("280.00")).moneyMovementCoverage("REGISTERED_HOTEL_TRANSACTION_RECORDS_ONLY").build();when(db.dashboard(from,to)).thenReturn(row);when(expenses.paidByCategory(from,to)).thenReturn(List.of(CategoryExpense.builder().category("SUPPLIES").amount(new BigDecimal("20.00")).build()));var got=service.dashboard(from,to);assertEquals(new BigDecimal("100.00"),got.getTotalRecognizedRevenue());assertEquals(new BigDecimal("20.00"),got.getTotalPaidExpense());assertEquals(new BigDecimal("300.00"),got.getExternalInflow());assertNotEquals(got.getTotalRecognizedRevenue(),got.getExternalInflow());}
 @Test void summariesAndRevenueUseDatabasePaginationAndFilters(){var d=LocalDate.of(2026,9,22);when(db.summaryCount(d,d)).thenReturn(1L);when(db.summaryPage(d,d,0,20)).thenReturn(List.of(DailyFinancialSummary.builder().businessDate(d).build()));assertEquals(1,service.summaries(d,d,1,20).getItems().size());when(db.revenueCount(d,d,d,d,"ROOM_REVENUE","FOLIO_ITEM",3L,4L)).thenReturn(1L);service.revenue(d,d,d,d,"room_revenue","folio_item",3L,4L,1,20);verify(db).revenuePage(d,d,d,d,"ROOM_REVENUE","FOLIO_ITEM",3L,4L,0,20);}
 @Test void movementFiltersKeepInternalTransferAsItsOwnDirection(){when(db.movementCount(isNull(),isNull(),isNull(),isNull(),eq("INTERNAL_TRANSFER"),isNull(),isNull(),isNull(),isNull(),isNull())).thenReturn(1L);when(db.movementPage(isNull(),isNull(),isNull(),isNull(),eq("INTERNAL_TRANSFER"),isNull(),isNull(),isNull(),isNull(),isNull(),eq(0),eq(20))).thenReturn(List.of(HotelTransactionRecord.builder().direction("INTERNAL_TRANSFER").build()));var page=service.movements(null,null,null,null,"internal_transfer",null,null,null,null,null,1,20);assertEquals("INTERNAL_TRANSFER",page.getItems().get(0).getDirection());}
 @Test void exceptionViewIsPagedAndPageSizeIsCapped(){when(db.exceptionCount()).thenReturn(2L);when(db.exceptionPage(0,20)).thenReturn(List.of(FinanceException.builder().exceptionType("PAYMENT_MANUAL_REVIEW").build(),FinanceException.builder().exceptionType("NIGHT_AUDIT_BLOCKED").build()));assertEquals(2,service.exceptions(1,20).getItems().size());assertThrows(RuntimeException.class,()->service.exceptions(1,101));}
 @Test void controllerRestrictsReadLayerToFinanceOwnerAndSuperAdmin(){var rule=FinanceOperationsController.class.getAnnotation(PreAuthorize.class).value();assertTrue(rule.contains("FINANCE"));assertTrue(rule.contains("OWNER"));assertTrue(rule.contains("SUPER_ADMIN"));for(String denied:List.of("CUSTOMER","STAFF","HR_ADMIN","MANAGER"))assertFalse(rule.contains("'"+denied+"'"));}
}
