package com.johnny.hotel;
import com.johnny.hotel.businessdate.BusinessDateService;import com.johnny.hotel.finance.FinanceOperationsService;import com.johnny.hotel.invoice.FinanceReadService;import com.johnny.hotel.support.WalletDevelopmentGuard;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfSystemProperty;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest(classes=HotelBackendApplication.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"hotel.wallet.dev.fixture=true","spring.cache.type=none","logging.level.org.springframework=WARN"}) @AutoConfigureMockMvc @EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
class FinanceOperationsDevelopmentTest {
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){var e=WalletDevelopmentGuard.settings();r.add("spring.datasource.url",WalletDevelopmentGuard::url);r.add("spring.datasource.username",()->e.get("DB_USERNAME"));r.add("spring.datasource.password",()->e.get("DB_PASSWORD"));r.add("spring.data.redis.password",()->e.get("REDIS_PASSWORD"));}
 @Autowired FinanceOperationsService service;@Autowired FinanceReadService reads;@Autowired BusinessDateService dates;@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @Test void realMysqlQueriesExecuteWithDatabasePagination(){var d=dates.current().getBusinessDate();assertNotNull(service.dashboard(d.minusDays(30),d));assertNotNull(service.summaries(d.minusDays(30),d,1,20));assertNotNull(service.revenue(null,null,null,null,null,null,null,null,1,20));assertNotNull(service.movements(null,null,null,null,null,null,null,null,null,null,1,20));assertNotNull(service.exceptions(1,20));}
 @Test void endpointRoleBoundaryIsExact()throws Exception{var url="/api/finance/operations/dashboard?from=2026-01-01&to=2026-12-31";for(String role:List.of("FINANCE","OWNER","SUPER_ADMIN"))mvc.perform(get(url).with(authentication(auth(role)))).andExpect(status().isOk());for(String role:List.of("CUSTOMER","STAFF","HR_ADMIN","MANAGER"))mvc.perform(get(url).with(authentication(auth(role)))).andExpect(status().isForbidden());mvc.perform(get(url)).andExpect(status().isUnauthorized());}
@Test void legacyOperationalReadIsTypedPagedAndUsesTheSameFinanceBoundary()throws Exception{for(String domain:List.of("bookings","assignments","rooms","stays","guests","cleaning","inspections","work-orders","turnovers")){SecurityContextHolder.getContext().setAuthentication(financeAuth("FINANCE"));var result=reads.read(domain,1,20);assertEquals(1,result.getPage());assertTrue(result.getTotal()>=result.getItems().size());}SecurityContextHolder.clearContext();var url="/api/finance/operations/bookings?page=1&pageSize=20";for(String role:List.of("FINANCE","OWNER","SUPER_ADMIN"))mvc.perform(get(url).with(authentication(financeAuth(role)))).andExpect(status().isOk()).andExpect(jsonPath("$.data.items").isArray());for(String role:List.of("CUSTOMER","STAFF","HR_ADMIN","MANAGER"))mvc.perform(get(url).with(authentication(auth(role)))).andExpect(status().isForbidden());mvc.perform(get("/api/finance/operations/bookings?page=1&pageSize=101").with(authentication(financeAuth("FINANCE")))).andExpect(status().isBadRequest());}
 private UsernamePasswordAuthenticationToken auth(String role){var ids=jdbc.queryForList("SELECT u.id FROM sys_user u JOIN sys_user_role ur ON ur.user_id=u.id JOIN sys_role r ON r.id=ur.role_id WHERE u.status=1 AND r.role_code=? ORDER BY u.id LIMIT 1",Long.class,role);Long id=ids.isEmpty()?jdbc.queryForObject("SELECT id FROM sys_user WHERE status=1 ORDER BY id LIMIT 1",Long.class):ids.get(0);return token(role,id);}
 private UsernamePasswordAuthenticationToken financeAuth(String presentedRole){Long id=jdbc.queryForObject("SELECT u.id FROM sys_user u JOIN sys_user_role ur ON ur.user_id=u.id JOIN sys_role r ON r.id=ur.role_id WHERE u.status=1 AND r.role_code IN ('FINANCE','OWNER','SUPER_ADMIN') ORDER BY u.id LIMIT 1",Long.class);return token(presentedRole,id);}
 private UsernamePasswordAuthenticationToken token(String role,Long id){var a=new UsernamePasswordAuthenticationToken("test","n/a",List.of(new SimpleGrantedAuthority("ROLE_"+role)));a.setDetails(id);return a;}
}
