package com.johnny.hotel;
import com.johnny.hotel.businessdate.BusinessDateService;import com.johnny.hotel.finance.FinanceOperationsService;import com.johnny.hotel.support.WalletDevelopmentGuard;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfSystemProperty;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
@SpringBootTest(classes=HotelBackendApplication.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"hotel.wallet.dev.fixture=true","spring.cache.type=none","logging.level.org.springframework=WARN"}) @AutoConfigureMockMvc @EnabledIfSystemProperty(named="hotel.wallet.dev.tests",matches="true")
class FinanceOperationsDevelopmentTest {
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){var e=WalletDevelopmentGuard.settings();r.add("spring.datasource.url",WalletDevelopmentGuard::url);r.add("spring.datasource.username",()->e.get("DB_USERNAME"));r.add("spring.datasource.password",()->e.get("DB_PASSWORD"));r.add("spring.data.redis.password",()->e.get("REDIS_PASSWORD"));}
 @Autowired FinanceOperationsService service;@Autowired BusinessDateService dates;@Autowired MockMvc mvc;
 @Test void realMysqlQueriesExecuteWithDatabasePagination(){var d=dates.current().getBusinessDate();assertNotNull(service.dashboard(d.minusDays(30),d));assertNotNull(service.summaries(d.minusDays(30),d,1,20));assertNotNull(service.revenue(null,null,null,null,null,null,null,null,1,20));assertNotNull(service.movements(null,null,null,null,null,null,null,null,null,null,1,20));assertNotNull(service.exceptions(1,20));}
 @Test void endpointRoleBoundaryIsExact()throws Exception{var url="/api/finance/operations/dashboard?from=2026-01-01&to=2026-12-31";for(String role:List.of("FINANCE","OWNER","SUPER_ADMIN"))mvc.perform(get(url).with(authentication(auth(role)))).andExpect(status().isOk());for(String role:List.of("CUSTOMER","STAFF","HR_ADMIN","MANAGER"))mvc.perform(get(url).with(authentication(auth(role)))).andExpect(status().isForbidden());mvc.perform(get(url)).andExpect(status().isUnauthorized());}
 private UsernamePasswordAuthenticationToken auth(String role){var a=new UsernamePasswordAuthenticationToken("test","n/a",List.of(new SimpleGrantedAuthority("ROLE_"+role)));a.setDetails(1L);return a;}
}
