package com.johnny.hotel;
import com.johnny.hotel.businessdate.*;import com.johnny.hotel.guest.GuestAccess;import com.johnny.hotel.nightaudit.*;import com.johnny.hotel.payment.ReservationPaymentFulfillmentService;import com.johnny.hotel.reservation.ReservationLifecycleService;import com.johnny.hotel.finance.RevenueRecognitionService;
import org.junit.jupiter.api.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class NightAuditServiceTest {
 NightAuditMapper db=mock(NightAuditMapper.class);NightAuditStateService state=mock(NightAuditStateService.class);BusinessDateService dates=mock(BusinessDateService.class);ReservationPaymentFulfillmentService fulfillment=mock(ReservationPaymentFulfillmentService.class);ReservationLifecycleService reservations=mock(ReservationLifecycleService.class);GuestAccess access=mock(GuestAccess.class);RevenueRecognitionService revenue=mock(RevenueRecognitionService.class);NightAuditService service=new NightAuditService(db,state,dates,fulfillment,reservations,access,revenue);LocalDate d=LocalDate.of(2026,9,22);NightAuditRun run=NightAuditRun.builder().id(8L).businessDate(d).status("STARTING").build();
 @BeforeEach void setup(){when(access.activeRoles(1L)).thenReturn(Set.of("MANAGER"));when(state.begin("key",1L)).thenReturn(run);when(state.claim(8L)).thenReturn("token");when(db.blockers(8L)).thenReturn(List.of());when(state.finish(8L,"token",1L)).thenReturn(NightAuditRun.builder().id(8L).businessDate(d).status("COMPLETED").build());}
 @Test void happyPathAdvancesOnlyAfterAllSteps(){var result=service.execute("key",1L);assertEquals("COMPLETED",result.run().getStatus());var order=inOrder(state,revenue);order.verify(state).step(8L,"token","PAYMENT_RECOVERY");order.verify(state).step(8L,"token","ARRIVALS");order.verify(state).step(8L,"token","REVENUE_RECOGNITION");order.verify(revenue).recognize(d);order.verify(state).step(8L,"token","DAILY_SUMMARY");order.verify(revenue).summarize(d,8L);order.verify(state).step(8L,"token","FINAL_VALIDATION");order.verify(state).finish(8L,"token",1L);}
 @Test void pendingArrivalBlocksBeforeClosingWork(){when(state.begin("key",1L)).thenReturn(NightAuditRun.builder().id(8L).businessDate(d).status("BLOCKED").build());assertEquals("BLOCKED",service.execute("key",1L).run().getStatus());verify(state,never()).claim(anyLong());verifyNoInteractions(fulfillment,reservations,revenue);}
 @Test void approvedArrivalUsesExistingNoShowDomainActionExactlyOnce(){when(db.approvedArrivals(d)).thenReturn(List.of(12L));service.execute("key",1L);verify(reservations).noShowForNightAudit(12L,1L,"Night Audit no-show for "+d,d);}
 @Test void blockedPrecheckNeverRunsClosingSteps(){when(state.begin("key",1L)).thenReturn(NightAuditRun.builder().id(8L).businessDate(d).status("BLOCKED").build());service.execute("key",1L);verify(state,never()).prepare(anyLong(),anyString());verify(state,never()).finish(anyLong(),anyString(),anyLong());}
 @Test void successfulIncompletePaymentIsFulfilledBeforeAdvance(){when(db.incompletePayments(d)).thenReturn(List.of(31L),List.of());service.execute("key",1L);verify(fulfillment).fulfill(31L);verify(state).finish(8L,"token",1L);}
 @Test void failedRecoveryBlocksAdvance(){when(db.incompletePayments(d)).thenReturn(List.of(31L));doThrow(new RuntimeException("provider recovery failed")).when(fulfillment).fulfill(31L);when(db.blockers(8L)).thenReturn(List.of(NightAuditBlocker.builder().build()));when(state.block(8L,"token")).thenReturn(NightAuditRun.builder().id(8L).businessDate(d).status("BLOCKED").build());service.execute("key",1L);verify(state,atLeastOnce()).addBlocker(eq(8L),eq("PAYMENT_FULFILLMENT"),eq("PAYMENT_ATTEMPT"),eq(31L),anyString());verify(state,never()).finish(anyLong(),anyString(),anyLong());}
 @Test void completedDuplicateRequestIsIdempotent(){when(state.begin("key",1L)).thenReturn(NightAuditRun.builder().id(8L).businessDate(d).status("COMPLETED").build());when(db.blockers(8L)).thenReturn(List.of());assertEquals("COMPLETED",service.execute("key",1L).run().getStatus());verify(state,never()).claim(anyLong());}
}
