package com.johnny.hotel;
import com.johnny.hotel.ar.*;import com.johnny.hotel.businessdate.*;import com.johnny.hotel.mapper.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.payment.*;import com.johnny.hotel.settlement.*;import com.johnny.hotel.settlement.SettlementRequests.*;import org.junit.jupiter.api.*;import java.math.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class SettlementServiceTest{SettlementMapper db;ArAccess access;BusinessDateService dates;PaymentCoreMapper tx;SysAuditLogMapper audits;SettlementService service;LocalDate businessDate=LocalDate.of(2026,9,24);
 @BeforeEach void init(){db=mock(SettlementMapper.class);access=mock(ArAccess.class);dates=mock(BusinessDateService.class);tx=mock(PaymentCoreMapper.class);audits=mock(SysAuditLogMapper.class);var p=new PaginationProperties();p.setMaxPageSize(100);p.setBrowseLimit(100);service=new SettlementService(db,access,dates,tx,audits,new PaginationSupport(p),Clock.fixed(Instant.parse("2026-09-24T02:00:00Z"),ZoneId.of("Asia/Shanghai")));when(access.actor()).thenReturn(new ArAccess.Actor(7L,Set.of("FINANCE")));when(dates.postingDate()).thenReturn(businessDate);when(audits.insert(any())).thenReturn(1);when(tx.insertTransaction(any())).thenReturn(1);when(db.ensureBatch(any())).thenAnswer(i->{var b=(SettlementBatch)i.getArgument(0);b.setId(10L);return 1;});when(db.insertItem(any())).thenReturn(1);when(db.reconcile(anyLong(),any(),any(),any(),anyString(),anyString(),nullable(String.class))).thenReturn(1);}
 private Import request(BigDecimal gross,BigDecimal fee,BigDecimal net,String currency){return Import.builder().provider("MOCK").providerBatchId("B-1").currency(currency).grossAmount(gross).feeAmount(fee).netAmount(net).items(List.of(Item.builder().sourceType("DEPOSIT_PAYMENT").sourceId(3L).providerPaymentId("PP-1").direction("IN").grossAmount(gross).feeAmount(fee).netAmount(net).currency(currency).build())).build();}
 private SettlementBatch processing(){return SettlementBatch.builder().id(10L).provider("MOCK").providerBatchId("B-1").currency("CNY").declaredGross(new BigDecimal("1000.00")).declaredFee(new BigDecimal("25.00")).declaredNet(new BigDecimal("975.00")).status("PROCESSING").build();}
 @Test void payment1000Fee25ProducesMatchedSettlementWithoutNewMoneyOrRevenue(){when(db.lockBatch("MOCK","B-1")).thenReturn(processing());when(db.moneySource("DEPOSIT_PAYMENT",3L)).thenReturn(HotelTransactionRecord.builder().direction("EXTERNAL_IN").amount(new BigDecimal("1000.00")).currency("CNY").provider("MOCK").providerTransactionId("PP-1").build());when(db.batch(10L)).thenReturn(SettlementBatch.builder().id(10L).status("SETTLED").reconciliationStatus("MATCHED").build());var got=service.importBatch(request(new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"CNY"));assertEquals("MATCHED",got.getBatch().getReconciliationStatus());verify(db).reconcile(10L,new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"SETTLED","MATCHED",null);verifyNoInteractions(tx);}
 @Test void wrongCurrencyBecomesMismatchAndMissingSourceBecomesMissing(){when(db.lockBatch("MOCK","B-1")).thenReturn(processing());when(db.batch(10L)).thenReturn(SettlementBatch.builder().id(10L).status("EXCEPTION").reconciliationStatus("MISSING").build());service.importBatch(request(new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"CNY"));verify(db).insertItem(argThat(x->"MISSING".equals(x.getStatus())));verify(db).reconcile(eq(10L),any(),any(),any(),eq("EXCEPTION"),eq("MISSING"),anyString());}
 @Test void payout975IsInternalTransferAndRetryDoesNotDuplicate(){var batch=SettlementBatch.builder().id(10L).provider("MOCK").providerBatchId("B-1").currency("CNY").declaredNet(new BigDecimal("975.00")).build();when(db.batch(10L)).thenReturn(batch);when(db.lockBatch("MOCK","B-1")).thenReturn(batch);when(db.ensurePayout(any())).thenAnswer(i->{var p=(GatewayPayout)i.getArgument(0);p.setId(20L);return 1;});var paid=GatewayPayout.builder().id(20L).batchId(10L).provider("MOCK").providerPayoutId("PO-1").currency("CNY").amount(new BigDecimal("975.00")).status("COMPLETED").postingBusinessDate(businessDate).build();when(db.lockPayout("MOCK","PO-1")).thenReturn(paid);var r=Payout.builder().providerPayoutId("PO-1").amount(new BigDecimal("975.00")).currency("CNY").paidAt(LocalDateTime.of(2026,9,24,9,0)).build();service.payout(10L,r);when(db.payoutByBatch(10L)).thenReturn(paid);service.payout(10L,r);verify(tx,times(1)).insertTransaction(argThat(x->"INTERNAL_TRANSFER".equals(x.getDirection())&&"PROCESSOR_PAYOUT".equals(x.getSourceType())));}
 @Test void completedBatchRetryIsIdempotent(){var done=processing();done.setStatus("SETTLED");done.setReconciliationStatus("MATCHED");when(db.lockBatch("MOCK","B-1")).thenReturn(done);when(db.batch(10L)).thenReturn(done);service.importBatch(request(new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"CNY"));verify(db,never()).insertItem(any());verifyNoInteractions(tx);}
}
