package com.johnny.hotel;

import com.johnny.hotel.ar.*;import com.johnny.hotel.businessdate.*;import com.johnny.hotel.exception.BusinessException;import com.johnny.hotel.mapper.*;import com.johnny.hotel.pagination.*;import com.johnny.hotel.payment.*;import com.johnny.hotel.settlement.*;import com.johnny.hotel.settlement.SettlementRequests.*;
import org.junit.jupiter.api.*;import org.junit.jupiter.params.*;import org.junit.jupiter.params.provider.*;
import java.math.*;import java.time.*;import java.util.*;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import org.springframework.security.access.prepost.PreAuthorize;

class SettlementServiceTest {
 SettlementMapper db; ArAccess access; BusinessDateService dates; PaymentCoreMapper tx; SysAuditLogMapper audits; SettlementService service;
 LocalDate businessDate=LocalDate.of(2026,9,24);
 @BeforeEach void init(){db=mock(SettlementMapper.class);access=mock(ArAccess.class);dates=mock(BusinessDateService.class);tx=mock(PaymentCoreMapper.class);audits=mock(SysAuditLogMapper.class);var p=new PaginationProperties();p.setMaxPageSize(100);p.setBrowseLimit(100);service=new SettlementService(db,access,dates,tx,audits,new PaginationSupport(p),Clock.fixed(Instant.parse("2026-09-24T02:00:00Z"),ZoneId.of("Asia/Shanghai")));when(access.actor()).thenReturn(new ArAccess.Actor(7L,Set.of("FINANCE")));when(dates.postingDate()).thenReturn(businessDate);when(audits.insert(any())).thenReturn(1);when(tx.insertTransaction(any())).thenReturn(1);when(db.ensureBatch(any())).thenAnswer(i->{var b=(SettlementBatch)i.getArgument(0);b.setId(10L);return 1;});when(db.insertItem(any())).thenAnswer(i->{((SettlementItem)i.getArgument(0)).setId(30L);return 1;});when(db.nextAttemptNo(10L)).thenReturn(1);when(db.insertAttempt(any())).thenAnswer(i->{((SettlementReconciliationAttempt)i.getArgument(0)).setId(40L);return 1;});when(db.insertAttemptItem(any())).thenReturn(1);when(db.reconcile(anyLong(),any(),any(),any(),anyString(),anyString(),nullable(String.class))).thenReturn(1);when(db.attempts(anyLong())).thenReturn(List.of());}
 private Import request(){return Import.builder().provider("MOCK").providerBatchId("B-1").currency("CNY").grossAmount(new BigDecimal("1000.00")).feeAmount(new BigDecimal("25.00")).netAmount(new BigDecimal("975.00")).items(List.of(Item.builder().sourceType("DEPOSIT_PAYMENT").sourceId(3L).providerPaymentId("PP-1").direction("IN").grossAmount(new BigDecimal("1000.00")).feeAmount(new BigDecimal("25.00")).netAmount(new BigDecimal("975.00")).currency("CNY").build())).build();}
 private SettlementBatch batch(String status,String reconciliation){return SettlementBatch.builder().id(10L).provider("MOCK").providerBatchId("B-1").currency("CNY").declaredGross(new BigDecimal("1000.00")).declaredFee(new BigDecimal("25.00")).declaredNet(new BigDecimal("975.00")).calculatedGross(new BigDecimal("1000.00")).calculatedFee(new BigDecimal("25.00")).calculatedNet(new BigDecimal("975.00")).status(status).reconciliationStatus(reconciliation).build();}
 private HotelTransactionRecord source(){return HotelTransactionRecord.builder().direction("EXTERNAL_IN").amount(new BigDecimal("1000.00")).currency("CNY").provider("MOCK").providerTransactionId("PP-1").build();}
 private SettlementItem item(){return SettlementItem.builder().id(30L).batchId(10L).sourceType("DEPOSIT_PAYMENT").sourceId(3L).providerPaymentId("PP-1").direction("IN").grossAmount(new BigDecimal("1000.00")).feeAmount(new BigDecimal("25.00")).netAmount(new BigDecimal("975.00")).currency("CNY").build();}
 private Payout payout(){return Payout.builder().providerPayoutId("PO-1").amount(new BigDecimal("975.00")).currency("CNY").paidAt(LocalDateTime.of(2026,9,24,9,0)).build();}

 @Test void matchedImportRecordsAttemptWithoutCreatingMoneyOrRevenue(){when(db.lockBatch("MOCK","B-1")).thenReturn(batch("PROCESSING","PENDING"));when(db.moneySource("DEPOSIT_PAYMENT",3L)).thenReturn(source());when(db.batch(10L)).thenReturn(batch("SETTLED","MATCHED"));service.importBatch(request());verify(db).insertAttempt(argThat(a->"MATCHED".equals(a.getStatus())&&"IMPORT".equals(a.getRequestKey())));verify(db).reconcile(10L,new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"SETTLED","MATCHED",null);verifyNoInteractions(tx);}
 @Test void missingSourceRecordsImmutableExceptionAttempt(){when(db.lockBatch("MOCK","B-1")).thenReturn(batch("PROCESSING","PENDING"));when(db.batch(10L)).thenReturn(batch("EXCEPTION","MISSING"));service.importBatch(request());verify(db).insertItem(argThat(i->"MISSING".equals(i.getStatus())));verify(db).insertAttempt(argThat(a->"MISSING".equals(a.getStatus())));verify(db).reconcile(eq(10L),any(),any(),any(),eq("EXCEPTION"),eq("MISSING"),anyString());}
 @Test void sourceLaterAppearsAndRereconcileBecomesMatchedWhileKeepingHistory(){when(db.lockBatchById(10L)).thenReturn(batch("EXCEPTION","MISSING"));when(db.items(10L)).thenReturn(List.of(item()));when(db.moneySource("DEPOSIT_PAYMENT",3L)).thenReturn(source());when(db.nextAttemptNo(10L)).thenReturn(2);when(db.batch(10L)).thenReturn(batch("SETTLED","MATCHED"));service.reconcile(10L,Reconcile.builder().requestKey("retry-1").build());verify(db).insertAttempt(argThat(a->a.getAttemptNo()==2&&"retry-1".equals(a.getRequestKey())&&"MATCHED".equals(a.getStatus())));verify(db).reconcile(10L,new BigDecimal("1000.00"),new BigDecimal("25.00"),new BigDecimal("975.00"),"SETTLED","MATCHED",null);verify(db,never()).insertItem(any());}
 @Test void rereconcileRequestKeyRetryIsIdempotent(){when(db.lockBatchById(10L)).thenReturn(batch("EXCEPTION","MISSING"));when(db.attemptByRequest(10L,"retry-1")).thenReturn(SettlementReconciliationAttempt.builder().id(40L).build());when(db.batch(10L)).thenReturn(batch("EXCEPTION","MISSING"));service.reconcile(10L,Reconcile.builder().requestKey("retry-1").build());verify(db,never()).insertAttempt(any());verify(db,never()).reconcile(anyLong(),any(),any(),any(),anyString(),anyString(),any());}
 @ParameterizedTest @ValueSource(strings={"MISMATCH","MISSING","EXCEPTION"}) void unresolvedBatchCannotPayout(String state){var b=batch("EXCEPTION",state.equals("EXCEPTION")?"MISMATCH":state);when(db.lockBatchById(10L)).thenReturn(b);assertThrows(BusinessException.class,()->service.payout(10L,payout()));verify(db,never()).ensurePayout(any());verifyNoInteractions(tx);}
 @Test void wrongAmountOrCurrencyCannotBeForcedIntoPayout(){when(db.lockBatchById(10L)).thenReturn(batch("SETTLED","MATCHED"));var wrongAmount=payout();wrongAmount.setAmount(new BigDecimal("974.00"));assertThrows(BusinessException.class,()->service.payout(10L,wrongAmount));var wrongCurrency=payout();wrongCurrency.setCurrency("USD");assertThrows(BusinessException.class,()->service.payout(10L,wrongCurrency));verify(db,never()).ensurePayout(any());verifyNoInteractions(tx);}
 @Test void matchedPayoutIsExactlyOneInternalTransferAndRetryDoesNotDuplicate(){var b=batch("SETTLED","MATCHED");when(db.lockBatchById(10L)).thenReturn(b);when(db.latestUnresolvedCount(10L)).thenReturn(0);when(db.ensurePayout(any())).thenAnswer(i->{((GatewayPayout)i.getArgument(0)).setId(20L);return 1;});var paid=GatewayPayout.builder().id(20L).batchId(10L).provider("MOCK").providerPayoutId("PO-1").currency("CNY").amount(new BigDecimal("975.00")).status("COMPLETED").postingBusinessDate(businessDate).build();when(db.lockPayout("MOCK","PO-1")).thenReturn(paid);service.payout(10L,payout());when(db.lockPayoutByBatch(10L)).thenReturn(paid);service.payout(10L,payout());verify(tx,times(1)).insertTransaction(argThat(x->"INTERNAL_TRANSFER".equals(x.getDirection())&&"PROCESSOR_PAYOUT".equals(x.getSourceType())));}
 @Test void processorFeeIsSettlementCostAndNeverRevenueOrExternalIn(){when(db.lockBatchById(10L)).thenReturn(batch("SETTLED","MATCHED"));when(db.latestUnresolvedCount(10L)).thenReturn(0);when(db.ensurePayout(any())).thenAnswer(i->{((GatewayPayout)i.getArgument(0)).setId(20L);return 1;});when(db.lockPayout("MOCK","PO-1")).thenReturn(GatewayPayout.builder().id(20L).batchId(10L).provider("MOCK").providerPayoutId("PO-1").currency("CNY").amount(new BigDecimal("975.00")).build());service.payout(10L,payout());verify(tx).insertTransaction(argThat(x->!"EXTERNAL_IN".equals(x.getDirection())&&"INTERNAL_TRANSFER".equals(x.getDirection())));}
 @Test void settlementEndpointsRemainFinanceOwnerSuperAdminOnly(){var rule=SettlementController.class.getAnnotation(PreAuthorize.class).value();for(String role:List.of("FINANCE","OWNER","SUPER_ADMIN"))assertTrue(rule.contains("'"+role+"'"));for(String role:List.of("CUSTOMER","STAFF","MANAGER","HR_ADMIN"))assertFalse(rule.contains("'"+role+"'"));}
}
